### ISSUE TITLE
Potentially use NatureServe API for some of their data

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#126]
https://services.natureserve.org/index.jsp

**Comment by ChristopherTracey** [comment]
Has there been any progress on the integration of NatureServe taxonomy into the this package?

**Comment by sckott** [comment]
thanks for your message @ChristopherTracey No, not incorporated yet. I did start playing around with it, but not in the pkg yet. I'll try to get something up in the next few days and ping you again

**Comment by ChristopherTracey** [comment]
Great! Thanks!

**Comment by sckott** [comment]
@ChristopherTracey it turned out to be a lot of XML parsing, I created a new pkg https://github.com/ropenscilabs/natserv 

Two of the three web services are not really for taxonomic data, and I really want to keep `taxize` focused on taxonomic data only. So once the new pkg is on CRAN, we could import just the taxonomy fxn here

I'll ping you on the other pkg for feedback there

I'll leave this open until imported here or not

**Comment by sckott** [comment]
natserv is now on CRAN https://cran.rstudio.com/web/packages/natserv/ 

will try to integrate here

**Comment by sckott** [comment]
@ChristopherTracey incorporated natureserve here via the `natserv` package, reinstall `devtools::install_github("ropensci/taxize")`, then see `?get_natservid` and also avail. in `classification()`, but that's it, not elsewhere in pkg

**Comment by sckott** [comment]
sorted for now
