### ISSUE TITLE
Possible bug in iucn_summary

### ISSUE THREAD

**Issue by EDiLD** [ropensci/taxize#174]
>The following code give incorrect results from iucn... any idea why? Thanks!

```
i<-"Cyclura cychlura"
j<-"Anolis_sagrei"
unlist(iucn_summary(i)) #should return VU
unlist(iucn_summary(j)) #should return nothing or LC
```

**Comment by EDiLD** [comment]
A possible workaround is to use EOL to search for the IUCN ID:

```
require(taxize)
require(XML)
require(RCurl)
# get ID from EOL
sciname <- "balaenoptera physalus"
pageid <- eol_search(sciname)$pageid[1]
out <- eol_pages(taxonconceptID=pageid)$scinames
iucn_id <- gsub('IUCN-', '', out[grepl('IUCN', out$sourceidentfier), 'sourceidentfier'])
# use this ID to query IUCN
url <- paste0('http://iucn-redlist-api.herokuapp.com/details/', iucn_id, '/0')
h <- htmlParse(url)
status <- xpathSApply(h, "//div[@id =\"red_list_category_code\"]", 
                      xmlValue)
status
```

Maybe we should implement a. iucn_summary(<id> function)....

**Comment by sckott** [comment]
@EDiLD That sounds good to me

**Comment by sckott** [comment]
It seems that even using EOL we sometimes get the wrong IUCN ID. e.g, 

```r
iucn_from_eol <- function(x) {
  pageid <- eol_search(x)$pageid[1]
  out <- eol_pages(taxonconceptID=pageid)$scinames
  gsub('IUCN-', '', out[grepl('IUCN', out$sourceidentfier), 'sourceidentfier'])
}

iucn_from_eol("Branta canadensis")
#> [1] "141453"
```

Wheres the page on IUCN http://www.iucnredlist.org/details/22679935/0 has the id `22679935`

And I've seen the wrong Ids for other taxa as well. 

I don't know how to fix this, seems that IUCN itself sometimes gives the wrong ID, and EOL and GNR don't always have the correct ID either. 

This may be drastic but at some point maybe we want to drop any IUCN fxns as it's not great to give incorrect data, even if it's not our fault.
