### ISSUE TITLE
Add some functions for text-mining of papers/websites/etc.

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#212]
- [x] There is an API for pulling species names out of documents - here: http://gnrd.globalnames.org/
- [ ] [PDFX](http://pdfx.cs.man.ac.uk/) - but haven't been able to get it to work yet. Works fine from the cli using curl, but can't get it to work using `RCurl` or `httr` - The service basically parses a pdf to structured xml, and some other file types - could be useful to have for mining taxonomic names, etc.  
- [ ] Others?

**Comment by fgabriel1891** [comment]
Hi! 
Is it possible that the 'scrapenames' function could return also the OCR version of the pdf?  number and position of species names do not match when matching to the OCR output of fulltext::ft_extract. Is this possible or depends on the API itself? 

Thanks!

**Comment by sckott** [comment]
@fgabriel1891 thanks for your question. please open a new issue and include an example with how the positions don't match
