### ISSUE TITLE
Make an API for theplantlist.org data?

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#230]
@ropensci/owners 

It doesn't look like theplantlist data will be API'd anytime soon, and I think their terms would allow it http://www.theplantlist.org/1.1/terms/#derivative

It's the best source for plant names globally...

**Comment by sckott** [comment]
various ways to access this now, they also said they are working on an API, we'll see, closing

**Comment by heidiv** [comment]
Is an API still in the works?

**Comment by sckott** [comment]
I asked them over 3 years ago about this and they said they were working on it - clearly not 

the terms aren't as open as l'd like them to be http://www.theplantlist.org/1.1/terms/ - but I could throw together the API  if you will use it

**Comment by heidiv** [comment]
@sckott Awesome Scott - I might, though you're right these terms are tight laced. Have you received permission from them to create an API?

**Comment by sckott** [comment]
sort of back 3 years ago, asked again

**Comment by sckott** [comment]
From what I've heard Theplantlist I think is being replaced by http://powo.science.kew.org/, which does have an API, though is undocumented. see open issue https://github.com/ropensci/taxize/issues/598

So probably not worth doing an API for Theplantlist especially if they haven't given me the ok
