### ISSUE TITLE
Wikispecies?

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#317]
@EDiLD  There is the in dev `WikipediaR` package here 

However, it doesn't help that much. It just gets the html of the page, then we have to parse the html to something useful, here's a partial attempt

``` r
devtools::install_github("Ironholds/WikipediR")
library("WikipediR")
con <- wiki_con(language = "en", project = "species")
res <- wiki_page(con, "Helianthus")
html <- htmlParse(res$parse$text[[1]])
block <- xpathApply(html, "//td[contains(., 'Classification')]")
block
```

There seems to be little to no structure to wikipedia pages, meaning the code would be fragile I think. Unless perhaps each Wikispecies page is exactly the same format, then one parser could work for all of them perhaps. If we did this, doesn't seem worth including another pkg dependency (WikipediaR) if it just gets the page, which we could do with a one liner ourselves (i think at least)

**Comment by sckott** [comment]
Okay, the above eg is old, here's a new attempt, try again soon:

```r
bb <- WikipediR::page_content("en", domain = "species.wikimedia.org", page_name = "Helianthus")
html <- htmlParse(bb$parse$text$`*`)
xpathSApply(html, '//table[@class="wikitable mw-collapsible mw-collapsed"]')
```

```r
[[1]]
<table class="wikitable mw-collapsible mw-collapsed">
  <tr><th>Taxonavigation: <a href="/wiki/Asterales" title="Asterales">Asterales</a></th>
</tr>
  <tr><td>Classification System: APG III (down to family level)
<p><a href="/wiki/Main_Page" title="Main Page">Main Page</a><br/>
Regnum: <a href="/wiki/Plantae" title="Plantae">Plantae</a><br/>
Cladus: <a href="/wiki/Magnoliopsida" title="Magnoliopsida">Angiosperms</a><br/>
Cladus: <a href="/wiki/Eudicots" title="Eudicots">Eudicots</a><br/>
Cladus: <a href="/wiki/Core_eudicots" title="Core eudicots">Core eudicots</a><br/>
Cladus: <a href="/wiki/Asterids" title="Asterids">Asterids</a><br/>
Cladus: <a href="/wiki/Euasterids_II" title="Euasterids II">Euasterids II</a><br/>
Ordo: <a href="/wiki/Asterales" title="Asterales">Asterales</a><br/></p>
</td>
</tr>
</table> 
```

**Comment by sckott** [comment]
decided to move wikipedia taxonomy stuff to another pkg cause it's more work/code than I thought it would be, will integrate here later when that's available

**Comment by sckott** [comment]
in repo https://github.com/ropenscilabs/wikitaxa

**Comment by ezwelty** [comment]
I've been developing R code as part of an effort to mass-translate species common names for fallingfruit.org. I just discovered taxize (doh!) but I may have some code of interest. At least for extracting (aka guessing from html formatting) common names and language from wikipedia, wikicommons, and wikipedia, you can see what I have so far here: https://github.com/falling-fruit/falling-fruit/blob/master/util/fruitr/R/wiki.R

For our purposes of mass automation, this is followed up by a large amount of data filtering and cleaning, but the results are generally quite good.
https://github.com/falling-fruit/falling-fruit/blob/master/util/fruitr/scripts/type_translations.R#L189

**Comment by sckott** [comment]
hi @ezwelty - thanks for your message!

I'll have a look. I lean towards putting wikipedia taxonomy stuff in this package https://github.com/ropenscilabs/wikitaxa - and then we can import it here, as `taxize` is already too bloated. Would you be interested in contributing to the `wikitaxa` package?

**Comment by ezwelty** [comment]
Happy to contribute to the wikitaxa package if you can give some direction on the overall code architecture (since you'll know best about importing into taxize later). Are you intent on using WikipediR, or is say making api calls using httr (as I have) an acceptable direction to take?

**Comment by sckott** [comment]
Great. 

Not necessarily tied to using `WikidataR` (not wikipedia, but wikidata). 

I'll have a look at what you have an make some suggestions for PR's

**Comment by sckott** [comment]
@ezwelty I've looked over what you have in the `fruitr` pkg. 

Can you send a pull request to `wikitaxa` repo with modifications to the functions in `wiki.R`? 

I want to change a few things, but I can do so after merging too

* check http status codes, via `stop_for_status` or a custom error catcher if there's useful error messages from wikimedia
* `curl` package has `curl::curl_unescape()` so we don't need to import `RCurl` (`httr` depends on `curl`, so that's a more natural fit)
* want to make the parsing more general, to not just common names, but can add that after merging

**Comment by sckott** [comment]
any thoughts @ezwelty

**Comment by ezwelty** [comment]
Here you go:
https://github.com/ropenscilabs/wikitaxa/pull/3

**Comment by sckott** [comment]
pkg pushed to CRAN - will incorporate here soon

**Comment by sckott** [comment]
sorted
