### ISSUE TITLE
AOU codes

### ISSUE THREAD

**Issue by davharris** [ropensci/taxize#353]
The American Ornithologists' Union has codes for bird species that are used in the BBS database, among other places.  I thought it could be useful to tie them to species names.

There's a list [here](ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/SpeciesList.txt) from the Breeding Bird Survey, which people might find useful, or there might be better lists elsewhere.

The BBS list has at least one error (the column labeled "Spanish common name" should actually be "Latin name"), but that doesn't really affect the content.

Is this something worth exploring more?

**Comment by sckott** [comment]
closing, inactivity

**Comment by davharris** [comment]
Makes sense.  Sorry for the runaround.

**Comment by davharris** [comment]
@sckott Figured it out.  The "AOU" column in the BBS data set refers to internal codes used at USGS.  The codes used by the actual American Ornithologists' Union are in the "seq" column. 😑

**Comment by sckott** [comment]
Okay, so do you think its worth re-considering including here? or no

**Comment by davharris** [comment]
Not a priority. I just thought it made sense to document it in case the BBS/AOU stuff pops up again...

Dave
