### ISSUE TITLE
`classification` assumes all numeric ids are tsn regardless of db

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#376]
`classification` seems to assume that any id that can be coreced to numeric is a tsn, even if the `db` option says otherwise. This is implemented in the `process_ids` function used in `classification.default`:

```
process_ids <- function(input, fxn, ...){
  g <- tryCatch(as.numeric(as.character(input)), warning=function(e) e)
  if(is(g,"numeric")){
    id <- input
    class(id) <- "tsn"
  } else {
    id <- eval(fxn)(input, ...)
  }
  id
}
```

Im not sure that  `class(id) <- "tsn"` was meant to be hard-wired to "tsn". I imagine that `process_ids` could use another argument that specified the class to set the result if it matches the taxon id pattern for a given database. Although taxon ids are numeric in most databases, they can be otherwise in "nbn", so Im not sure how best to approch automatically distinguishing between taxon ids and taxon names. 
Perhaps the problem could be avoided by `classification` having `name` and `id` arguments that can be used in place of current `x` argument (like in `ncbi_children`). If a user has taxon names they use the `name` argument and if they had taxon ids, they use the `id` argument.

**Comment by sckott** [comment]
@zachary-foster sorry forgot about this, added to current milestone, will get this sorted

**Comment by sckott** [comment]
I thin this is sorted out now, probably forgot to close this, closing now
