### ISSUE TITLE
Parallel data retrieval

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxize#399]
I have several thousands of species names and would like to use some taxize functions, e.g. tnrs, tax_name,... But getting the data is so slow. You seem to have incorporated a parallel argument in some functions, like iucn_summary(). Is there any prospect a parallel option will be added to other commands?

I tried using plyr's parallel option but had no luck:

```r
a <- c("AAA","CCC", "Abies alba", "Accer", "Cladonia fimbriata", "Claadonia")
require(doParallel)
require(foreach)
require(plyr)

cl <- makeCluster(6)
registerDoParallel(cl) 

ptm <- proc.time()
tnrs1 <-llply(a, 
              function(x) tnrs(query=x, source="iPlant_TNRS"),
              .parallel=TRUE, .paropts = list(.packages = "taxize", .export="a")) 
diff1 <-  proc.time() - ptm

stopCluster(cl) 

tnrs1

<anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
```

**Comment by Alectoria** [comment]
Thanks for the quick reply. I will see whether I can get the DBs in file format.

**Comment by sckott** [comment]
hi @Alectoria - Thanks for your question. @EDiLD is right that the data providers don't want requests to come too quickly as most scientific data providers are not that well funded, and even if they were, they'd still have higher, but existing limits on how many calls to their API per time period. 

This is the unfortunate downside to using web APIs is that if your data needs are large, you may be better off trying to get data dumps.  But then you are sort of on your own for querying that data. What I'd love is to have functions in `taxize` able to query web APIs and also a local database, when the data provider allows download of their data. However, this requires significant work to get `taxize` functions to behave the same regardless of the web API or a local database, and the user has to have some knowledge of databases, command line, etc.  We did start this with ITIS data a few years ago, but sort of left it incomplete. You can see that progress here, e.g., : https://github.com/ropensci/taxize/blob/sql/R/itis.R#L13-L18

Looking around at the various data providers, many do provide a data dump, so we could give a bigger push to having `taxize`  functions work with local databases if there is a significant demand from users.

**Comment by sckott** [comment]
added some notes here https://github.com/sckott/taxize_sql

**Comment by Alectoria** [comment]
Thanks, @sckott. I looked into some of the data dumps but didn't find their structure straightforward. For now, it will be faster for me to use web APIs than to figure out how to use locally installed DBs. 

But in the longterm I can see a demand for taxize functions that work with local databases.

**Comment by Alectoria** [comment]
Now think of it: I will am planning to give an R course next summer that will explore different tools for taxonomic name resolution + spelling checking in large vegetation databases. I think a taxize function that can match names fast via local databases will be much appreciated by the participants.

**Comment by sckott** [comment]
@Alectoria Thanks for the feedback. Is that R course summer 2015?  What month?

Like I pointed out, we have done this with just ITIS data, so it can be done, though surely won't be available for all data sources, and would be hard for more basic R users to use. BUT, would be great for more advanced users that have big data needs. 

I'll start playing with this and ping you for some testing/feedback.

**Comment by Alectoria** [comment]
The course will be in July 2015. - Having local access to the ITIS database is great but the database unfortunately does not have a very good cover, at least not for European species. COL is more comprehensive but I failed to install the local database. I wrote the administrator and am hoping for a reply.

**Comment by sckott** [comment]
Im working on integration of local search for itis and col right now, and ncbi, theplantlist, and others

We should have integration of local db search before july :-)

**Comment by Alectoria** [comment]
Sounds great! Let me know if I can be of any help.

**Comment by EDiLD** [comment]
Alternatives (for plants) would be theplantlist (`tpl_*()` in taxize, or better : Taxonstand package), which let's you query a bunch of plant names with one query. (Though i don't know if there are any limitations).

Or take a look at vegdata-package (I have no experience with it), which uses german data (but may also be suitable for czech republic).

**Comment by Alectoria** [comment]
Thanks, @EDiLD . ThePlantList and taxonstand are great but do not cover fungi and do not check for errors in genus names. ncbi & col would be the the best options, as they have a global cover and are comprehensive.

**Comment by sckott** [comment]
@EDiLD good point about theplantlist

@Alectoria good to know what you're preference is - we can focus on getting ncbi and col done...

**Comment by sckott** [comment]
closing, starting to work on sql stuff in new pkg `ropenscilabs/taxizedb` that will focus on interacting with SQL dbs - so we'll give up on replicating the functions here I think
