### ISSUE TITLE
Return to doing local sql queries where possible

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#400]
see #399

**Comment by sckott** [comment]
- [ ] ITIS: mostly sorted, just need to finish off the sql verions of each function
- [ ] NCBI: got data, just need to get sorted in the pkg
- [ ] COL: big dataset, using mysql for now, ask ing if they can provide postgresql downloads, still working on download scripts
- [ ] plantlist: have code for download data, create database, need to put those together - also, there's no API calls really to match, so just do a simple search I guess, or maybe try to copy SQL queries in some ITIS functions

**Comment by sckott** [comment]
Try to consolidate all local SQL Dbs within postgres, as it seems the best option. 

ITIS in sqlite right now, Col in MySQL, plantlist will be in postgres (working on now)

**Comment by Alectoria** [comment]
I found another DB that is easy to download (GRIN Taxonomy, .dbf format) and might be interesting for you: http://www.ars-grin.gov/misc/tax/

Thanks for your effort! Can't wait to use these functions.

**Comment by sckott** [comment]
@Alectoria Great, thanks for that!  I'll look into using that too

**Comment by sckott** [comment]
@Alectoria Curious - Do you have a problem if you have to use different databases locally on your computer?  I ask because the data providers provide data in different database dump formats, so it's easiest to then get users of this pkg to get in those database formats - BUT they are in different database formats, one so far in SQLite, one in MySQL, and one in PostgreSQL. I'd like if all could be in PostgreSQL, but not sure if that will be a feasible workflow if a user has to convert e.g, a MySQL db into postgres, etc.

**Comment by Alectoria** [comment]
I can see the advantage of having a single format for a local query but my sense is that the different conversions required might deter users....unless there is a single (free, cross-plattform) solution that does the job for them. I bumped into pgloader (https://github.com/dimitri/pgloader). Should I check it out?

I am sure you have your reasons for using postgres but I am curious whether you have considered to base the local query on some dplyr-functions (http://cran.r-project.org/web/packages/dplyr/vignettes/databases.html)? They support access to all of your mentioned sql-formats.

**Comment by sckott** [comment]
@Alectoria  We are indeed using `dplyr` to make it easier to connect to databases, but in the end, a database must be used with `dplyr` (unless the data is in R memory, which won't with these large datasets). So the question is which database?  Hadley recommends PostgreSQL, and b/c I am no expert, I think we should go with that.

**Comment by EDiLD** [comment]
I am using postgreSQL because of it's GIS capabilities (PostGis). However, I don't know if this scales to other ecologists...

**Comment by sckott** [comment]
@EDiLD cool, i like postgres too - now to see if I can get COL/ITIS/NCBI to provide their DB dumps as Postgres -

we can just do the conversion ourselves, but that means we have to host files to serve to people, or users can do it themselves locally, but then they have to have both postgres and mysql, and the know how to do it

**Comment by Alectoria** [comment]
@sckott Thanks for clarifying. It would be great if the data would be provided as postgres-dumps, from the start. This would make life much easier for everybody. - BTW, I spotted ITIS in postgres here (seems that recently added it): http://www.itis.gov/downloads/

**Comment by sckott** [comment]
@Alectoria  right, i just noticed the postgres version for ITIS, will use that. now to convince other providers to give postgres dumps

**Comment by sckott** [comment]
closing, working on `ropenscilabs/taxizedb`
