### ISSUE TITLE
gbif - fuzzy search

### ISSUE THREAD

**Issue by EDiLD** [ropensci/taxize#409]
e.g.:

http://api.gbif.org/v1/species/match?name=Papilio%20machon

is this already implemted?

**Comment by sckott** [comment]
we use the `/suggest` route https://github.com/ropensci/taxize/blob/master/R/get_gbifid.R#L149 - should we change that?

**Comment by sckott** [comment]
@EDiLD any thoughts on this?

**Comment by EDiLD** [comment]
Hmm, maybe add these 2 search types:
`/species/match` and `/species/search` ? As alternative routes to `gbif_name_suggest`?

**Comment by sckott** [comment]
@EDiLD the `/suggest` route does do fuzzy matching. Can you give some egs that aren't currently handled well by `get_gbifid()`
