### ISSUE TITLE
missing documentation for apg_families?

### ISSUE THREAD

**Issue by wcornwell** [ropensci/taxize#418]
Where does this look-up come from?  Is there a versioning to the family in order lookup?

0b9fbbfe183ec75f93c3ff6fdd3dd42a8b9c0c17

**Comment by sckott** [comment]
hi @wcornwell - thanks for the message. `apg_families` is a dataset that comes with `taxize` - it is documented, but not very well, in the package. If you do `?apg_families`, you should get the man page for it. that dataset is mostly used internally, but users can use it too of course.

I'll add better documentation to that and other datasets now...

**Comment by sckott** [comment]
@wcornwell what do you mean by versioning?

**Comment by wcornwell** [comment]
Thanks for the speedy reply!  

Just a bit of background: @richfitz and I were trying to get some kind of dynamic workflow that creates a taxonomy lookup that tracks back to canonical sources with information about versioning, but it's proving tricky.  Plant taxonomy is messy and APGIII != http://www.mobot.org/MOBOT/research/APweb/ . APG-III is static as defined in http://onlinelibrary.wiley.com/doi/10.1111/j.1095-8339.2009.00996.x/full On the other hand Peter Stevens dynamically updates http://www.mobot.org/MOBOT/research/APweb/ based on his view of recent developments so there are some things on http://www.mobot.org/MOBOT/research/APweb/ that don't line up with APG-III (e.g. Sabiales).  Also Peter has put some other non angiosperm clades on his website.

So anyway http://www.mobot.org/MOBOT/research/APweb/ is a great source, but it's changing all the time.  Did you construct `apg_familes` from scraping http://www.mobot.org/MOBOT/research/APweb/?  I guess best solution for us would be a script that scrapes http://www.mobot.org/MOBOT/research/APweb.  Second best I guess would just be able to document `apg_familes` so that source and version is clear?

Any thoughts?

**Comment by sckott** [comment]
woops, i didn't know that APGIII wasn't http://www.mobot.org/MOBOT/research/APweb/ my bad. 

Is there a already scraped/tidied version of the static APGIII data? I can include that in this pkg

Good idea to scrape, that sounds like it's more appropriate since that data changes often enough - that means I'll take those `apg_*` datasets out and replace with functions to scrape the data.

**Comment by sckott** [comment]
@wcornwell see https://github.com/ropensci/taxize/blob/master/R/apg.R do these get the data you want? the scraping is ugly b/c the html is very ugly :/

no fxn for genera yet, can't remember now where I got that data previously...

**Comment by sckott** [comment]
@wcornwell how do these functions work for you?

also, know where to get genus level data?  can't remember now where I got it before.

**Comment by wcornwell** [comment]
Working well.  I'm getting the genus-level using `tpl_get`

If you're curious check out: https://github.com/wcornwell/TaxonLookup

**Comment by sckott** [comment]
@wcornwell great, thanks for feedback. 

Nice, looking good.

I'll keep this open to see if I can find that old genus data

**Comment by sckott** [comment]
Turns out the generic data is from Theplantlist, woopsy. 
Updating that dataset to v1.1 now.

**Comment by sckott** [comment]
@wcornwell i think this is taken care of for now. 

From the MOBOT site, we have the two scraping functions to get up to date data, and we have the `tpl_` functions to get Theplantlist data, and a few datasets included in the package from each source that need to be updated manually occassionally.

**Comment by wcornwell** [comment]
I agree! plant biodiversity emojis might be appropriate here :maple_leaf: :palm_tree: :rose: :tulip:

**Comment by sckott** [comment]
:cactus: :evergreen_tree:
