### ISSUE TITLE
tpl_get should have showWarnings=FALSE option

### ISSUE THREAD

**Issue by wcornwell** [ropensci/taxize#419]
Downloading into existing directories is going to be useful sometimes, so being able to suppress the warning from dir.create here would be nice.

**Comment by sckott** [comment]
thanks @wcornwell 

i wonder if it would be better, in the use case where the directory given already exists, to check if it exists, and only run `dir.create()` if it doesn't exist

**Comment by wcornwell** [comment]
that issue was actually @richfitz logged in on my computer, so maybe he has some thoughts...

**Comment by sckott** [comment]
@richfitz ....

**Comment by richfitz** [comment]
`dir.create(x, FALSE, TRUE)` is mildly faster than

```
if (!dir.exists(x)) { 
   dir.create(x, recursive = TRUE)
}
```

but it's also fewer lines so that's nice.  I'd suggest updating https://github.com/ropensci/taxize/blob/ec8f45a7c807f2bd19dc85496253fcac26819a50/R/tpl_get.r#L58

**Comment by sckott** [comment]
that works, will do

**Comment by sckott** [comment]
okay, @wcornwell reinstall

**Comment by wcornwell** [comment]
Great!  Thanks!
