### ISSUE TITLE
Typo in apg_lookup description?

### ISSUE THREAD

**Issue by johnbaums** [ropensci/taxize#422]
Description for `apg_lookup` is "Lookup in the APGII taxonomy and replace family names."

Should APGII read APGIII, as per other `apg_*` objects?

**Comment by sckott** [comment]
yep, typo, fixing noq

**Comment by sckott** [comment]
see also: https://github.com/ropensci/taxize/issues/418

**Comment by johnbaums** [comment]
Thanks @sckott :)
