### ISSUE TITLE
umlauts, the plant list, and tpl_get()

### ISSUE THREAD

**Issue by wcornwell** [ropensci/taxize#424]
`tpl_families()` and `tpl_get()` seem to do different things with umlauts which leads to some issues.

Also github-markdown does another set of strange things with umlauts which makes it hard to discuss here.  

I'm trying to get http://www.theplantlist.org/1.1/browse/P/Iso%C3%ABtaceae/Iso%C3%ABtaceae.csv (imagine those strange characters as an umlaut over an e) to act like all the rest of them, but `tpl_families()` returns IsoÃ«taceae and `tpl_get()` then doesn't match the right url via `tpl_get()`.  

Any ideas?

**Comment by jarioksa** [comment]
There was a similar problem in **Taxonstand** in September 2014. Then it turned out to be a problem in the encoding used by the server. More specifically, the `ThePlantlistList` server defined an explicit text encoding in its header files, but did not use that specified encoding (probably due to underlying database engine settings).

**Comment by sckott** [comment]
hi @wcornwell - thanks for the issue.  I'll have a look and get back to you here soon. (thanks for the info @jarioksa )

**Comment by sckott** [comment]
@wcornwell what operating system are you on?

**Comment by sckott** [comment]
@wcornwell still not sure what to do here - if any windows people know the solution to this, do chime in

**Comment by wcornwell** [comment]
Thanks for checking into this.  It was on mac osx 10.9, but does seem to be specific to my work machine which the university people set up with some windows-like settings.   So I bet I can find a local fix.

**Comment by sckott** [comment]
What does `Sys.getlocale()` give you?

**Comment by wcornwell** [comment]
"en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"

**Comment by wcornwell** [comment]
Still don't know exactly why the problem occurs on some machines; my best guess is that it relates to the point @jarioksa made; I think there is some interaction between the specific settings on the machine for how much they trust server text encoding specifications with the mismatch on the TPL servers.  But anyway I think I've got a fix.  

In the calls to `htmlParse` the encoding can be specified, and if you do so then the behavior gets a lot more understandable--and hopefully consistent across machines.  

If you change `htmlParse(url)` to `htmlParse(url,encoding="UTF-8")` to *both* functions `tpl_get()` and `tpl_families()` and probably wherever else `htmlParse` is called, then I *think* that will work without breaking anything else...

**Comment by sckott** [comment]
@wcornwell reinstall and see if that works now

**Comment by wcornwell** [comment]
works!  Thanks @sckott !!!

**Comment by sckott** [comment]
great!
