### ISSUE TITLE
change synonyms default to `accepted = FALSE`?

### ISSUE THREAD

**Issue by davharris** [ropensci/taxize#425]
The Breeding Bird Survey refers to the Pine Siskin as *Spinus pinus*, which is now an invalid name.  I wanted to use `synonyms` to find the updated name, but it didn't work with the default arguments:

```
> synonyms("Spinus pinus", "itis")

Retrieving data for taxon 'Spinus pinus'

Not found. Consider checking the spelling or alternate classification
$`Spinus pinus`
[1] NA
```
If I set `accepted = FALSE`, however, the call to `get_tsn` inside `synonyms` no longer fails, and I get my answer: 

```
> synonyms("spinus pinus", accepted = FALSE, db = "itis")

Retrieving data for taxon 'spinus pinus'

$`spinus pinus`
     name    tsn
1 nomatch 179246
```

It seems like this would be a more reliable default behavior for `synonyms` (or perhaps for `get_tsn` more generally).  What do you think?

**Comment by sckott** [comment]
hey dave, thanks for this. 

I agree that `accepted  = FALSE` seems like a better default for the `synonyms()` function - and perhaps for `get_tsn()` too 

pushing commit soon

**Comment by sckott** [comment]
testing other functions that use `get_tsn` to make sure this doesn't mess anythign up

**Comment by sckott** [comment]
@davharris can you reinstall and try again?

**Comment by davharris** [comment]
@sckott Works for me now.  Thanks!

**Comment by sckott** [comment]
cool cool
