### ISSUE TITLE
Find valid name from invalid name?

### ISSUE THREAD

**Issue by davharris** [ropensci/taxize#426]
[The ITIS page for the invalid name *Spinus pinus*](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=950104) links to the correct/valid name, which is *Leiothlypis luciae*.

Even with the changes in #425, however, I get a `nomatch` when I try to get at this name change using `synonym`.

Is there currently a way to get at the valid name? If not, should we patch `getsynonymnamesfromtsn` so that it looks in more than one place for synonyms?

Thanks!

**Comment by sckott** [comment]
thanks, just a sec, working on an encoding problem #424

**Comment by sckott** [comment]
@davharris yeah, so ITIS doesn't give back anything but the tsn for the accepted name, e.g., 

http://www.itis.gov/ITISWebService/services/ITISService/getSynonymNamesFromTSN?tsn=179246

```
<ns:getSynonymNamesFromTSNResponse xmlns:ns="http://itis_service.itis.usgs.gov">
   <ns:return xmlns:ax21="http://data.itis_service.itis.usgs.gov/xsd" xmlns:ax26="http://itis_service.itis.usgs.gov/xsd" xmlns:ax23="http://metadata.itis_service.itis.usgs.gov/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SvcSynonymNameList">
   <ax21:tsn>179246</ax21:tsn>
  <ax21:synonyms xsi:nil="true"/>
  </ns:return>
</ns:getSynonymNamesFromTSNResponse>
```

thinking

**Comment by sckott** [comment]
@davharris umm, isn't that first link (invalid page for spinus pinus) this page http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=179246 ?

**Comment by sckott** [comment]
@davharris does this behavior make sense:

```r
synonyms("Spinus pinus", db="itis")
```

```r
Retrieving data for taxon 'Spinus pinus'

Accepted name is 'Carduelis pinus'
Using tsn 179233

$`Spinus pinus`
          name    tsn
1 Spinus pinus 179246
```

**Comment by davharris** [comment]
Sorry about the link, you're right.

Your suggested behavior doesn't quite address my use case (finding other possible names for 50 species in the Breeding Bird Survey that aren't found in birdtree.org). regardless of whether BBS used the accepted names or not, I always want the names *other than* the ones I typed in.

Does the following behavior make sense?

* If I type in the accepted name, I want the names listed as "synonyms" as output (current behavior) 
* If I type a non-accepted name I want the name listed as "accepted" as output (along with any other synonyms that happen to exist).

Thanks again

**Comment by sckott** [comment]
> If I type a non-accepted name I want the name listed as "accepted" as output (along with any other synonyms that happen to exist).

As a single `data.frame`?

**Comment by sckott** [comment]
@davharris thoughts?

**Comment by davharris** [comment]
Sorry, was distracted with other projects.  Still should have gotten back to you sooner.

Yes, in a single `data.frame`.  My reasoning is that (for my current project, at least), I'd like the format of the returned object to be as consistent as possible.  If some list elements return a `data.frame` and other ones return lists of `data.frames` or some other data structures, that creates more work downstream.

**Comment by sckott** [comment]
@davharris no worries about time. I gots lots of other pkgs to work on, so the asynchrony in feedback works out fine. 

Right, I'll try to make it a single data.frame.
