### ISSUE TITLE
Cheatsheet feedback

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#427]
https://discuss.ropensci.org/t/cheatsheets-feedback/195

Started a cheatsheet for taxize. Thoughts anyone?

@ibartomeus 
@EDiLD 
@zachary-foster
@fmichonneau
@dlebauer
@davharris
@wcornwell 
@scelmendorf

**Comment by ibartomeus** [comment]
Thats very cool, a silly thing: You use both "name" and "names".
Standardise.




On Tue, May 19, 2015 at 7:29 PM, Scott Chamberlain <notifications@github.com
> wrote:

> https://discuss.ropensci.org/t/cheatsheets-feedback/195
>
> Started a cheatsheet for taxize. Thoughts anyone?
>
> @ibartomeus <https://github.com/ibartomeus>
> @EDiLD <https://github.com/EDiLD>
> @zachary-foster <https://github.com/zachary-foster>
> @fmichonneau <https://github.com/fmichonneau>
> @dlebauer <https://github.com/dlebauer>
> @davharris <https://github.com/davharris>
> @wcornwell <https://github.com/wcornwell>
> @scelmendorf <https://github.com/scelmendorf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/taxize/issues/427>.
>



-- 
Ignasi Bartomeus PhD
www.bartomeuslab.com
@ibartomeus
Skype: nachobartomeus

Dpto. Ecología Integrativa
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio s/n
Isla de la Cartuja
41092, Sevilla (Spain)

**Comment by sckott** [comment]
@ibartomeus thanks! will fix

**Comment by sckott** [comment]
@ibartomeus  you can see the diff in the jpg version of the changes i made  https://github.com/ropensci/cheatsheets/commit/7d86576b448247e379ea1c96228bb8c0e310f634 - pretty fun

**Comment by zachary-foster** [comment]
Its looking good! The only thing I saw was that your `cbind` example has `taxize::rbind` in the code.

**Comment by sckott** [comment]
fixed, thanks @zachary-foster

**Comment by scelmendorf** [comment]
Great idea!
Minor comment, I don’t think col_search(names) gets the synonyms –doesn’t synonyms(names) do that?

**Comment by sckott** [comment]
thanks @scelmendorf ! fixed, see https://github.com/ropensci/cheatsheets/commit/301c674609af24deac19a2ae67dc61bdf1556e96

**Comment by sckott** [comment]
thanks y'all, closing

**Comment by fmichonneau** [comment]
It looks great and will be useful for people to get started!

My only comment is the use of "target taxon" in the column at the right. I think of "target" as what the function will output. Maybe use just "taxon" or "taxon = names in query below".

**Comment by sckott** [comment]
thanks @fmichonneau - Would _input taxon_ be better? I think just _taxon_ isn't specific enough

**Comment by fmichonneau** [comment]
Yes, that works!

**Comment by sckott** [comment]
okay, thanks @fmichonneau

**Comment by sckott** [comment]
fixed https://github.com/ropensci/cheatsheets/blob/master/taxize/taxize-cheatsheet.pdf

**Comment by fmichonneau** [comment]
:+1:
