### ISSUE TITLE
Error : object 'progress' is not exported by 'namespace:httr'

### ISSUE THREAD

**Issue by nmatzke** [ropensci/taxize#428]
Hi,

taxize from CRAN seems to install fine, but when I do library(taxize), I get this error:

==========
Error : object 'progress' is not exported by 'namespace:httr'
==========

When I install from github I get:

===============
> install_github("taxize", username="ropensci")
Installing github repo taxize/master from ropensci
Downloading master.zip from https://github.com/ropensci/taxize/archive/master.zip
Installing package from /var/folders/j1/xzx2gv_x27x3j3lgs5npp_700000gn/T//RtmpNTthqM/master.zip
arguments 'minimized' and 'invisible' are for Windows only
Installing taxize
Installing dependencies for taxize:
roxygen2, knitr, knitr
also installing the dependencies ‘mime’, ‘brew’, ‘evaluate’, ‘formatR’, ‘highr’, ‘markdown’, ‘yaml’

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/mime_0.3.tgz'
Content type 'application/x-gzip' length 22900 bytes (22 KB)
opened URL
==================================================
downloaded 22 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/brew_1.0-6.tgz'
Content type 'application/x-gzip' length 98041 bytes (95 KB)
opened URL
==================================================
downloaded 95 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/evaluate_0.7.tgz'
Content type 'application/x-gzip' length 34791 bytes (33 KB)
opened URL
==================================================
downloaded 33 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/formatR_1.2.tgz'
Content type 'application/x-gzip' length 43716 bytes (42 KB)
opened URL
==================================================
downloaded 42 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/highr_0.5.tgz'
Content type 'application/x-gzip' length 26145 bytes (25 KB)
opened URL
==================================================
downloaded 25 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/markdown_0.7.7.tgz'
Content type 'application/x-gzip' length 168776 bytes (164 KB)
opened URL
==================================================
downloaded 164 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/yaml_2.1.13.tgz'
Content type 'application/x-gzip' length 168108 bytes (164 KB)
opened URL
==================================================
downloaded 164 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/roxygen2_4.1.1.tgz'
Content type 'application/x-gzip' length 377489 bytes (368 KB)
opened URL
==================================================
downloaded 368 KB

trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/knitr_1.10.5.tgz'
Content type 'application/x-gzip' length 601772 bytes (587 KB)
opened URL
==================================================
downloaded 587 KB

The downloaded binary packages are in
	/var/folders/j1/xzx2gv_x27x3j3lgs5npp_700000gn/T//RtmpNTthqM/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD  \
  build  \
  '/private/var/folders/j1/xzx2gv_x27x3j3lgs5npp_700000gn/T/RtmpNTthqM/devtools242b1aa1fbd0/taxize-master'  \
  --no-manual --no-resave-data 

* checking for file '/private/var/folders/j1/xzx2gv_x27x3j3lgs5npp_700000gn/T/RtmpNTthqM/devtools242b1aa1fbd0/taxize-master/DESCRIPTION' ... OK
* preparing 'taxize':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'taxize' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object 'progress' is not exported by 'namespace:httr'
ERROR: lazy loading failed for package 'taxize'
* removing '/private/var/folders/j1/xzx2gv_x27x3j3lgs5npp_700000gn/T/RtmpSLFr31/Rinst24b8493d88e7/taxize'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
> 
===============

...so it's the same issue.

I'm using a Mac OS X 10.9, my Sys.info():

Sys.info()
                                                                                            sysname 
                                                                                           "Darwin" 
                                                                                            release 
                                                                                           "13.3.0" 
                                                                                            version 
"Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64" 
                                                                                           nodename 
                                                                        "587213511.guest.umich.net" 
                                                                                            machine 
                                                                                           "x86_64" 

Cheers!
Nick

**Comment by nmatzke** [comment]
Oops, meant to do sessionInfo():

R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.4 (Mavericks)


locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_1.5       RColorBrewer_1.1-2 treebase_0.0-7.1   rfishbase_0.2-2    TreeSim_2.1        laser_2.4-1       
 [7] geiger_2.0.3       phytools_0.4-31    maps_2.3-7         OUwie_1.45         nloptr_1.0.4       ape_3.2           

loaded via a namespace (and not attached):
 [1] animation_2.3           assertthat_0.1          chron_2.3-45            clusterGeneration_1.3.1 coda_0.16-1            
 [6] codetools_0.2-10        corpcor_1.6.7           data.table_1.9.4        deSolve_1.10-9          digest_0.6.4           
[11] evaluate_0.7            expm_0.99-1.1           fastmatch_1.0-4         foreach_1.4.2           grid_3.1.3             
[16] httr_0.3                igraph_0.7.1            iterators_1.0.7         jsonlite_0.9.16         knitr_1.10.5           
[21] lattice_0.20-30         MASS_7.3-39             Matrix_1.1-5            memoise_0.2.1           mnormt_1.5-1           
[26] msm_1.4                 mvtnorm_1.0-0           nlme_3.1-120            numDeriv_2012.9-1       parallel_3.1.3         
[31] phangorn_1.99-7         plotrix_3.5-7           plyr_1.8.1              Rcpp_0.11.3             RCurl_1.95-4.1         
[36] reshape2_1.4.1          scatterplot3d_0.3-35    splines_3.1.3           stringr_0.6.2           subplex_1.1-4          
[41] survival_2.38-1         Taxonstand_1.7          tools_3.1.3             whisker_0.3-2           XML_3.98-1.1

**Comment by nmatzke** [comment]
Hi again -- never mind, the issue was that I had version 0.3 of package "httr" installed, when I update to current (httr version 0.6.1), library(taxize) works fine.

**Comment by sckott** [comment]
hi @nmatzke thanks for the report. Sounds like we should make more recent version of httr required, i'll figure out what that is

**Comment by sckott** [comment]
@EDiLD i played around with installing diff. versions of httr, and there were problems even with v0.4, v0.5 worked, but just to be sure, I bumped to require the most recent CRAN version, b/c why not. 

also bumped to require most recent XML version
