### ISSUE TITLE
IUCN numeric ID

### ISSUE THREAD

**Issue by davharris** [ropensci/taxize#431]
Do any existing functions return IUCN's numeric IDs (e.g. [22679935 for the Canada Goose](http://api.iucnredlist.org/details/22679935/0))? I'm finding that I need them for the `birdlife_*` functions in the traits package.

If there isn't currently a way to get them, what would the best option be? I could create a new function (either here or in the traits package), or if you'd prefer, maybe I could add it to an IUCN-related function here.

Thanks!

**Comment by davharris** [comment]
This code (based on `iucn_summary`) pulls out the numeric ID.

```
spec <- tolower(sciname)
spec <- gsub(" ", "-", spec)
url <- paste("http://api.iucnredlist.org/go/", spec, sep = "")
e <- try(h <- readLines(url), silent = silent)

id_plus = grep("http://www.iucnredlist.org/apps/redlist/details/", e, value = TRUE)
gsub(".*/", "", id_plus)
```

**Comment by sckott** [comment]
nice work answering your own question.  

Do you thin it warrants a new fxn in taxize?

**Comment by davharris** [comment]
That's what I wasn't sure about.  Whichever approach you prefer.

**Comment by sckott** [comment]
Sure, I think a `iucn_id()` function is warranted.

**Comment by EDiLD** [comment]
See also issue https://github.com/ropensci/taxize/issues/174.
