### ISSUE TITLE
Possible bug in gnr_resolve (EOL)

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxize#450]
I get the following error when I run

    gnr_resolve("Metzgeria", data_source_ids = c(12), stripauthority = T)   
    
    Error in data.frame(name_string = "metzgeria", data_source_title = "EOL",  : 
    arguments imply differing number of rows: 1, 0

The issue might be related to #432 but my example occurred particularly with data_source_title="EOL" (haven't checked all sources systematically).

    sessionInfo()
    R version 3.2.1 (2015-06-18)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.9.5 (Mavericks)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] taxize_0.6.0     magrittr_1.5     stringi_0.5-5    Taxonstand_1.7   reshape2_1.4.1   
     dplyr_0.4.2             plyr_1.8.3       stringr_1.0.0    data.table_1.9.5
    
    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.0      rstudioapi_0.3.1 ape_3.3          lattice_0.20-31  R6_2.1.0         foreach_1.4.2        
     httr_1.0.0       tools_3.2.1      bold_0.2.6      
    [10] parallel_3.2.1   grid_3.2.1       nlme_3.1-121     DBI_0.3.1        iterators_1.0.7  lazyeval_0.1.10      
    assertthat_0.1   bitops_1.0-6     codetools_0.2-11
    [19] curl_0.9.1       RCurl_1.95-4.7   mime_0.3         XML_3.98-1.3     reshape_0.8.5    jsonlite_0.9.16  
    chron_2.3-47

**Comment by EDiLD** [comment]
Thanks for reporting this bug!
This happens when no canonical form was returned.

Fixes are already there (#453). Will merge, when tests finish.

**Comment by EDiLD** [comment]
Merged into the master branch.
Note, that the argument name `stripauthority` has been changed to `canonical`.
The currently version on github now returns:

```r
> gnr_resolve("Metzgeria", data_source_ids = c(12), canonical = T)   
$results
  submitted_name data_source_title score matched_name2
1      Metzgeria               EOL  0.75     Metzgeria
3      Metzgeria               EOL  0.50          <NA>

$preferred
NULL

$not_known
character(0)
```

**Comment by EDiLD** [comment]
Thanks @Alectoria for reporting this bug!
