### ISSUE TITLE
gnr_resolve() strips too much information when 'stripauthority=T'

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxize#451]
When using argument 'stripauthority = T', gnr_resolve() strips not only author names but also taxonomic abbreviations (e.g. 'subsp.', 'var.') in the 'matched_name' output.

    library(taxize)

    # This works well:

    gnr_resolve(c("Abies alba", "Stipa pennata var. anomala", "Silene otites ssp. pseudo-otites"), #443    
    data_source_ids = c(1,5))

    $results
    submitted_name                                                          matched_name data_source_title
    1                       Abies alba                                                      Abies alba Mill. Catalogue of Life
    4 Silene otites ssp. pseudo-otites Silene otites subsp. pseudotites (Rchb.) Graebner &amp;  
    Graebner   fil. Catalogue of Life
    2       Stipa pennata var. anomala                       Stipa pennata var. anomala (P.A.Smirn.) Tzvelev     
    Catalogue of Life
    3       Stipa pennata var. anomala        Stipa pennata subsp. anomala (P.A.Smirn.) F.M.Vázquez & 
    M.Gut. Catalogue of Life
    score
    1 0.988
    4 0.540
    2 0.999
    3 0.999
  
    $preferred
    NULL
  
    # This does not give the expected outcome (notice missing 'var' and 'ssp' in matched_name2):

    gnr_resolve(c("Abies alba", "Stipa pennata var. anomala", "Silene otites ssp. pseudo-otites"),   
    data_source_ids = c(1,5), stripauthority = T)

    $results
    submitted_name data_source_title score             matched_name2
    1                       Abies alba Catalogue of Life 0.988                Abies alba
    4 Silene otites ssp. pseudo-otites Catalogue of Life 0.540 Silene otites pseudotites
    2       Stipa pennata var. anomala Catalogue of Life 0.999     Stipa pennata anomala
    3       Stipa pennata var. anomala Catalogue of Life 0.999     Stipa pennata anomala
  
    $preferred
    NULL

    sessionInfo()
    R version 3.2.1 (2015-06-18)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.9.5 (Mavericks)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] taxize_0.6.2     magrittr_1.5     stringi_0.5-5    Taxonstand_1.7   reshape2_1.4.1   dplyr_0.4.2          
    plyr_1.8.3      
    [8] stringr_1.0.0    data.table_1.9.5
    
    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.0      rstudioapi_0.3.1 ape_3.3          lattice_0.20-31  R6_2.1.0         foreach_1.4.2    
    httr_1.0.0      
     [8] tools_3.2.1      bold_0.2.6       parallel_3.2.1   grid_3.2.1       nlme_3.1-121     DBI_0.3.1        
    iterators_1.0.7 
    [15] lazyeval_0.1.10  assertthat_0.1   bitops_1.0-6     codetools_0.2-11 curl_0.9.1       RCurl_1.95-4.7   
     mime_0.3        
    [22] XML_3.98-1.3     reshape_0.8.5    jsonlite_0.9.16  chron_2.3-47

**Comment by EDiLD** [comment]
I think the argument name `'stripauthority'` is misleading -
actually it is the canonical form.
From http://resolver.globalnames.org/about:

>Name strings are often supplied with complex authorship information [e.g. Racomitrium canescens f. epilosum (H. Müll. ex Milde) G. Jones in Grout]. The Global Name parser strips authorship and rank information from names [e.g. Racomitrium canescens epilosum], which makes it possible to compare the string with other variants of the same name. Resulting canonical forms are checked for exact matches against canonical forms in specified data sources or in the entire resolver database. All found names are removed from the process at the completion of this step. 

@sckott What do you think? Change  the argument name from `'stripauthority'` to `'canocial'`?

**Comment by sckott** [comment]
@Alectoria thx for the report!

@EDiLD yes, I think we should change it to `canonical`

**Comment by EDiLD** [comment]
OK, will do...

**Comment by Alectoria** [comment]
@EDiLD @sckott Thanks for clarifying. I noticed that the problem is actually with GNR. I made a request for an alternative output: https://github.com/GlobalNamesArchitecture/gni/issues/43

**Comment by sckott** [comment]
thanks for the report on the GNI repo @Alectoria

**Comment by dimus** [comment]
There is new option in GNR -- with_canonical_ranks=true to keep infraspecific ranks
https://github.com/GlobalNamesArchitecture/gni/issues/43

**Comment by Alectoria** [comment]
@dimus: This is a super cool option that will save me many hours of work. Thanks for the quick implementation!

and thanks to @sckott and @EDiLD for clarifying the canonical output.

**Comment by EDiLD** [comment]
Supercool @dimus. Thanks!

**TODO**
- [ ] add `with_canonical_ranks=true` functionality to taxize

**Comment by EDiLD** [comment]
** More Info***

It fails because the genus is not in theplantlist$genus.
This returns NA:

```
taxa_genus <- "Lapsanastrum"
theplantlist[ match(taxa_genus, theplantlist$genus), "family" ]
```

and causes downstream problems.
Still don't know what the difference between linux and/or current-R....

**Comment by EDiLD** [comment]
On windows:
```
> x <- "Lapsanastrum takasei"
> phylomatic_format(x, format = 'isubit', db = 'apg')
 Hide Traceback
 
 Rerun with Debug
 Error in if (nchar(as.character(dd$that)) == 0) { : 
  missing value where TRUE/FALSE needed 
4 FUN(X[[i]], ...) 
3 lapply(X = X, FUN = FUN, ...) 
2 sapply(taxa, foo, USE.NAMES = FALSE) at phylomatic_format.R#43
1 phylomatic_format(x, format = "isubit", db = "apg") 
```

**Comment by sckott** [comment]
@EDiLD did you mean to put the `phylomatic_format` comment in #454 ?

**Comment by sckott** [comment]
thanks so much @dimus 

@EDiLD are you taking care of adding that param? or should i?

**Comment by EDiLD** [comment]
@sckott Please do it - I wont have time next week...

**Comment by sckott** [comment]
Will do
