### ISSUE TITLE
request consistent var names in value from downstream(...,intermediate=TRUE)

### ISSUE THREAD

**Issue by philippi** [ropensci/taxize#460]
A call to downstream() with intermediate=TRUE returns a list for each submitted tsn, with "target" a data.frame, and "intermediate" a list of 1 or more data.frames.
The variables in target are
tsn, parentname, parenttsn, taxonname, rankid, rankname.  
The variables in an intermediate data.frame are
tsn, parentname, parenttsn, taxonname, rankId, rankName.  

The last 2 variables have slightly different names.  
I'm trying to expand a name/tsn to all possible downstream names that might have been used for species occurrences, which should be a mainstream usage.  If the variable names were consistent, I could use rbindlist.  But "rankid" v "rankId" and "rankname" v "rankName" require several more steps.

**Comment by philippi** [comment]
library(taxize)
testTSN <- get_tsn("Corynorhinus",accepted=TRUE)
testdown <- downstream(testTSN,db='itis',downto='Subspecies',intermediate=TRUE)
str(testdown)

**Comment by philippi** [comment]
note that this is no biggie, just a request for consistency.  As far as I can tell, the last listed data.frame within each intermediate list appears to be the same as the corresponding target data.frame, so I can just discard target and parse intermediate.

**Comment by EDiLD** [comment]
Thanks phillipi for reporting this.
Should be fixed now.

@sckott Shouldn't we make all thorughout taxize lowercase? Then we don't have to care...
 I am not a fan of camelCase. This means a lot of changes and may be a midterm goal?
What do you think is it worth the time? It will be only an internal change and not user visible...

**Comment by EDiLD** [comment]
Closing this and opened a new issue #462 .

**Comment by sckott** [comment]
Sorry. On vacation  now. Back to computer in a few days
