### ISSUE TITLE
plantminer API

### ISSUE THREAD

**Issue by gustavobio** [ropensci/taxize#464]
Hello,

I moved the entire plantminer codebase from ruby to R. This included the API (plumber), which now returns text/json instead of text/plain:

http://www.plantminer.com/flora?taxon=Coffea%20arabica (Brazilian Flora Checklist)
http://www.plantminer.com/tpl?taxon=Coffea%20arabica (The Plant List)

There is only that one querystring. You can find info on fields at http://www.plantminer.com. The API is backwards compatible, so current code should continue working normally if you decide not to update plantminer() in taxize:

http://www.plantminer.com/search/coffea/arabica
http://www.plantminer.com/search/coffea/arabica?api_key=youdontneedthisanymore

I dropped the need for an api key from both the old and the new api.

Best,

Gustavo.

**Comment by sckott** [comment]
Thanks, the API was gone over the past few days when I was running tests, and the website only had the shiny app, so I thought you had removed the API. Glad to see it's up!

I'll change the URL's. I imagine it would make sense to have an argument for user to search either Brazilian Flora or The Plant List?

**Comment by gustavobio** [comment]
Yeah, my old server was behaving badly and I got tired of having to fix the code every time I'd update a gem. Got a new server and moved the whole thing to R, including the API. So far plumber seems more than capable of handling the amount of traffic plantminer normally gets.

The /search method is just a nginx rewrite that points to /tpl, which in turn uses basically the same data as the old version of the API. I'll leave it there for backwards compatibility since some people are still using it.

**Comment by gustavobio** [comment]
Thanks for putting plantminer back in.

Just to be clear as it might have gone unnoticed in my first message: users don't need an API key anymore. You can keep the query string there if you want, but it will be ignored.

**Comment by sckott** [comment]
ah, okay, I'll remove the `key` parameter, thanks!
