### ISSUE TITLE
Explore EU BON for worms/pesi replacement

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#466]
http://cybertaxonomy.eu/eubon-utis/doc.html 

Even if it doesn't have all capabilities of WORMS/PESI SOAP services, better than nothing. 

They have COL too apparently, but COL services seem adequate.

**Comment by EDiLD** [comment]
Looks, very interesting.
From Germany...

It would be a pleasure for me to implement this ;)

**Comment by sckott** [comment]
Okay. I would probably make internal helper function to work with the service, then have exported functions for each of PESI and WORMS 

The developer I heard from said that they use the SOAP services of these, and just turn it into REST service. I had done this but with a non open source tool so I gave up on it. And I wasn't sure if PESI/WORMS would give their blessing anyway.

**Comment by sckott** [comment]
We can mention this in the docs, from the EU BON via email

> Pesi and WORMS do not need to be updated on our side since we are using the original PESI SOAP service from VLIZ. We do not cache their data on our servers. It is always life data from the original PESI checklist.
 
They also said this (another reason to not use Col through them)

> For Col however this is different. This data is in fact imported in our servers. It is updated every time when the new annual checklist of Col is published.

**Comment by sckott** [comment]
not a super big hurry, but do you know when you'll be able to get to this @EDiLD  ?

**Comment by EDiLD** [comment]
At earliest next month (holidays  :boat:  :smile: ) - you can also start with this...

**Comment by sckott** [comment]
assigned to you, if we need to push next version before its done no worries, can just push to next milestone

**Comment by sckott** [comment]
No paging is done right now on their side, so they only return the first chunk of up to 50 results, make note in docs

they said they'd add paging later, as early as Dec

**Comment by sckott** [comment]
closing for now, some work to do still, but waiting on changes in their API
