### ISSUE TITLE
iucn fxns are a bit broken right now

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#475]
Sorry all, I thought I had this fixed, but not.  Was getting IUCN Ids from global names Api, but it turns out that the Ids are not always correct.   We could just use the IUCN API but it is one of the slowest APIs I've seen, so very painful for users, and tests take forever, or completely fail, etc. 

Looking into fixes via global names

**Comment by sckott** [comment]
For IUCN fxns, falling back to what we had at the last version of this package that went to CRAN.  

Hopefully by the next version we put out, there will be a solution to the broken IUCN problems

**Comment by rossmounce** [comment]
@sckott How bad is it atm?
I'd like to check ~160,000 plant taxa using taxize at some point before Christmas (heads-up!).

I read the warning in the docs: "Beware: IUCN functions can give back incorrect data". Do you have any examples (of incorrect data returns) so I might know what to look for? Or are there really ZERO tell-tale clues when it fails to return correct data?

**Comment by sckott** [comment]
In the current dev version, I switched back to using code that shouldn't return incorrect data (uses IUCN directly), __BUT__ the current code uses the IUCN API, which is sometimes fast, sometimes very very very slow.

**Comment by rossmounce** [comment]
OK, so I should checkout the dev code then in the mean time if I want to be safe(r).

Thanks

**Comment by sckott** [comment]
yeah

**Comment by sckott** [comment]
using new IUCN red list API now #492 closing
