### ISSUE TITLE
Customize the "fuzziness" of name matching

### ISSUE THREAD

**Issue by ashiklom** [ropensci/taxize#485]
First off, great package! I never imagined fixing species names could be this easy.

That said, I was wondering if it would be possible to allow users to tweak the "fuzziness" of name searches (for instance, like the R `agrep` function, which allows you to set levels of addition, deletion, and substitution as well as a distance metric).

I came across this issue while trying to match the Black locust tree (*Robinia pseudoacacia*) which is incorrectly entered in my dataset as "Rob**ina**" rather than "Rob**inia**". The search (both `tnrs` and `gnr_resolve`) for the incorrect form in my dataset only returns "Robina", which is unrelated, but a search for the correctly spelled "Robinia" gives multiple correct results. It seems like the fuzzy search should be able to pick up on the single letter misspelling (based on the vignette), but for some reason it's unable to.

EDIT: I just realized this is probably mostly an issue on the API side of the services your functions call and you can't really do anything about it...but on the off chance that there is, I'll leave this open.

**Comment by sckott** [comment]
@ashiklom  Thanks for the kind words :)

> That said, I was wondering if it would be possible to allow users to tweak the "fuzziness" of name searches (for instance, like the R agrep function, which allows you to set levels of addition, deletion, and substitution as well as a distance metric).

We focus mostly on working with web services - However, I am thinking of including more local (non-web API) based tools for name cleaning/parsing  For example, working on https://github.com/sckott/splister for matching a user's species list against a local reference list/table

> I came across this issue while trying to match the Black locust tree (Robinia pseudoacacia) which is incorrectly entered in my dataset as "Robina" rather than "Robinia". The search (both tnrs and gnr_resolve) for the incorrect form in my dataset only returns "Robina", which is unrelated, but a search for the correctly spelled "Robinia" gives multiple correct results. It seems like the fuzzy search should be able to pick up on the single letter misspelling (based on the vignette), but for some reason it's unable to.

So I don't know if docs state this, but `tnrs` only does fuzzy matching for plants. see also `iplant_resolve()` which `tnrs` uses for plants in the backend. If you use NCBI or MSW3 as a source with `tnrs` there's no fuzzy matching. That's weird that GNR doesn't do fuzzy correctly there. I thought it did.  This is more reason to get some better fuzzy matching. 

> EDIT: I just realized this is probably mostly an issue on the API side of the services your functions call and you can't really do anything about it...but on the off chance that there is, I'll leave this open.

Right, when working with APIs, we don't maintain any of them, so can't really change them. Though we can give feedback based on user's thoughts, like yours

-------

The challenge with local fuzzy matching is that we have to match against something, and we can't distribute the huge set of names that e.g., Global Names has.  It's easier if a user wants to fuzzy match against their own reference taxon list, but then again, there you have to account for all the variations of data a user may have. Anyway, it seems like we need local matching

**Comment by sckott** [comment]
closing, re-open @ashiklom if you want to chat more about this - the `splister` package mentioned above is where I'll be working on doing matching to a local taxon list if you're interested.
