### ISSUE TITLE
gnr_resolve(): Keep case of author names

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxize#486]
It seems that gnr_resolve() converts all author rnames to lower case. Would it be possible to keep the case in submitted_name? This would make it easier to merge results with the original dataset.

Example:

    gnr_resolve("Acroptilon reeepens (L.)DC.", data_source_ids = c(165,167))

               submitted_name               matched_name                    data_source_title score
    1 Acroptilon reeepens (l.)dc. Acroptilon repens (L.) DC. Tropicos - Missouri Botanical Garden  0.75
    2 Acroptilon reeepens (l.)dc. Acroptilon repens (L.) DC.  The International Plant Names Index  0.75

Working with taxize_0.7.0. Thanks for the nice package.

**Comment by EDiLD** [comment]
Thanks for reporting.

This bug was introduced recently (did not happen with v0.6.6). Will check - the problem is in `taxize_capwords()` ...

**Comment by EDiLD** [comment]
A temporary work-around (until taxize_capwords is fixed) would be to use `cap_first = FALSE`:

```
gnr_resolve("Acroptilon reeepens (L.)DC.", data_source_ids = c(165,167), cap_first = FALSE)
               submitted_name               matched_name                    data_source_title score
1 Acroptilon reeepens (L.)DC. Acroptilon repens (L.) DC. Tropicos - Missouri Botanical Garden  0.96
2 Acroptilon reeepens (L.)DC. Acroptilon repens (L.) DC.  The International Plant Names Index  0.96
```

**Comment by EDiLD** [comment]
OK, I don't think we need to fix anything here, but need to be more explicit in the docs (may add taxize_capwords to @seeAlso and @param cap_first).
Maybe @sckott has an opinion here?

**Comment by sckott** [comment]
This bit `tolower(substring(x, 2))` in `taxize_capwords()` lowercases the remainder of the name after the first letter. We need to not do that to the authority though. However, we'd need a robust way to separate the authority. There are web API options, but ideally we'd have something locally and fast - essentially TAXAMATCH ported to R, which I've thought about, but is a lot of work and C as well. We could try parsing off authority name with one of the web API name parsers

**Comment by Alectoria** [comment]
Thanks for the suggestion! 'cap_first = FALSE' saved me a bunch of time today.
I noticed, that spaces are also trimmed in 'submitted_name':

    test <- gnr_resolve("Poa annua ", with_canonical_ranks=T, cap_first = FALSE)
    test$submitted_name %>% unique()
    [1] "Poa annua"

It's not a big deal to fix it before you submit the name (e.g. with str_trim) but it would be really neat to just have the original spelling in "submitted_name". Maybe split it into two columns: 'original_name' (incl. original spelling) and 'submitted_name' (original spelling prepared for submission)?

**Comment by EDiLD** [comment]
@alectoria : +1,  that's a good idea

**Comment by sckott** [comment]
sorry for delay... good idea @Alectoria

**Comment by sckott** [comment]
I'll like make the fix you suggested @Alectoria  and get it in the `0.7.2` submission coming up soon

**Comment by sckott** [comment]
@Alectoria try it now after reinstalling `devtools::install_github("ropensci/taxize")`

**Comment by Alectoria** [comment]
@sckott Thanks for implementing "user_supplied_name". Works like a charm.

**Comment by sckott** [comment]
great, glad it works
