### ISSUE TITLE
get_uid() returns mismatch between vector and match attribute?

### ISSUE THREAD

**Issue by millerjef** [ropensci/taxize#489]
```r
get_uid("Hepatitis type B")

```
```
Retrieving data for taxon 'Hepatitis type B'

[1] NA
attr(,"class")
[1] "uid"
attr(,"match")
[1] "found"
```
Returns `NA`; however, the attribute is set to `found`

Is this this the expected behavior?

On a 500 row sample of my original data set of pathogens (mostly bacteria and fungi but also a few parasites and viruses) `table(attr(x, which = "match"))` lists:

```
              found           NA due to ask=FALSE 
                493                           7
```

Note that none are listed as `not found` as I anticipated should occur with my first example based on the documentation for the returned value. Furthermore, the documentation is inconsistent with the returned results in that the documentation lists `multi match` not `NA due to ask=FALSE`.

**Comment by sckott** [comment]
@millerjef thanks very much for the report. sorry for the inconsistent behavior and incorrect output attributes. Looking at it now

**Comment by sckott** [comment]
@millerjef Try it again after installing from github `devtools::install_github("ropensci/taixze")`

i've fixed that attribute problem, and made the docs consistent and correctly state that we give back `'NA due to ask=FALSE'` when `ask=FALSE`

Let me know if your concerns have been addresed

**Comment by millerjef** [comment]
Thanks for your prompt response. The attributes are now correctly set when not found. However...
```R
?get_uid
```
Results in:
```R
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/taxize/help/taxize.rdb' is corrupt
```

**Comment by sckott** [comment]
Hmm, try restarting the R session, Then load `taxize` again, then try `?get_uid`

**Comment by millerjef** [comment]
That worked. Thanks.
