### ISSUE TITLE
Problem pulling ranks below species from tropicos

### ISSUE THREAD

**Issue by scelmendorf** [ropensci/taxize#491]
Hi,
I'm trying to pull info for a variety, that is in tropicos.  

Here's an example:
Acroporium fuscoflavum var. baldwinii

If you follow the code below I think it illustrated the problem better than my verbal description could.

library (taxize)
thisWorksWell<-get_tpsid(sciname='Pinus contorta')
thisWorksWell
thisFailsEntirely<-get_tpsid(sciname='Acroporium fuscoflavum var. baldwinii')
thisFailsEntirely
thisAlmostWorks<-get_tpsid(sciname=gsub (' var\\.', '', 'Acroporium fuscoflavum var. baldwinii'))
thisAlmostWorks

#why can't I get all of this?
#change API key before runningexample
XMLq<-'http://services.tropicos.org/Name/Search?name=Acroporium+fuscoflavum+baldwinii&type=wildcard&apikey=MyAPIKeyThatImNotPostingOnGit&format=xml'
dataQ<-xmlParse(XMLq)
xmlData <- xmlToList(dataQ)
dataQ<-as.data.frame(t(data.frame(as.list(xmlData))))
dataQ$V1['Name.ScientificName']

**Comment by sckott** [comment]
Hi @scelmendorf - Thanks for the report. Tropicos has a few problems:

1. They don't allow a period in the query, even if it's URL encoded. The query fails on their server with a period. So i'm fixing that to replace periods with the url encoded equivalent. However, see 2 below
2. Tropicos doesn't like sub-specific rank names. That is, _Acroporium fuscoflavum var. baldwinii'_ isn't found at all, but _Acroporium fuscoflavum baldwinii'_ is found. 

I am putting in some warnings to catch when users include periods and when var/subsp/etc. are included and updating documentation

**Comment by scelmendorf** [comment]
Thanks - that sounds great.
While you're at it wrt the warnings, I would look for 
terminal:
sp.
sp

all forms of subspecies abbreviation
ssp.
subsp.
subspecies

all forms of variety
var.
varietas

and all forms of form
fo.
f.
forma

**Comment by sckott** [comment]
thanks for the additional things to look for, will do

**Comment by sckott** [comment]
@scelmendorf try again after reinstalling. let me know if it works as expected now
