### ISSUE TITLE
use new IUCN API

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#492]
from #472

**Comment by sckott** [comment]
http://apiv3.iucnredlist.org/

**Comment by Rekyt** [comment]
Using their API you need to apply for a token and explain your project. Then its humand validated before you actually get your token. Do you think it will be applicable to taxize given the License Restrictions?

**Comment by EDiLD** [comment]
Well, at least we could provide the functionality...
And the users have try to get their token .

I see only minor problems here (examples need `\dontrun` and we cannot test without exposing a key).

**Comment by sckott** [comment]
There are a few other services in `taxize` that require API keys. It's not hard to deal with in terms of testing, etc. It is a bit of a hurdle for users. After implementing some code, we'll see if it's that much better than the old that it's worth it. Right now, the IUCN code we have now is pretty fragile (not our code, but their services) - so if their new API is that much better I definitely want to move to that 

We aren't distributing any data, just code to get their data, so no licensing problems 

We can definitely suggest they open up more

**Comment by sckott** [comment]
new pkg at https://github.com/ropenscilabs/rredlist - i think it's nearly done, though need to add tests and a bit of documentation, pretty light weight pkg, then we can use it here in the current iucn fxns

**Comment by sckott** [comment]
implemented use of new IUCN API via the new `rredlist` package on CRAN now

- `iucn_id()` - uses `rredlist` now
- `iucn_summary()` - uses `rredlist` in part and the old API in part - we should watch this fxn though  b/c IUCN folks are deprecating/defuncting the old API soon
- `iucn_getname()` - no fuzzy search in the new IUCN API, so this fxn is unchanged, still using the global names API to do search

**Comment by sckott** [comment]
closing
