### ISSUE TITLE
itis query breaks for some taxa

### ISSUE THREAD

**Issue by ashenkin** [ropensci/taxize#495]
itis must be returning some unexpected data that breaks classification, tax_name, and perhaps other functions in taxize.  Any way to handle this more gracefully?
```
> classification("Saurauia",db = "itis")

Retrieving data for taxon 'Saurauia'

Error in `[.data.frame`(out, 1:which(out$tsn == x), c("taxonname", "rankname",  : 
  undefined columns selected
```

**Comment by sckott** [comment]
Thanks for the report @ashenkin That surely can fail better. I'll have a look
