### ISSUE TITLE
Lowest common function 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#505]
via https://discuss.ropensci.org/t/taxize-get-rank-of-lowest-common-taxon/300/

**Comment by sckott** [comment]
@jimmyodonnell anything else that you want to do on this function? 

some things we should do:

* see about adding methods for other data sources. we have itis, ncbi, and gbif. see about adding: eol, col, tropicos, nbn, bold
* write tests

**Comment by jimmyodonnell** [comment]
I've never written tests (that I'm aware of), so I can't lead that effort but would love to learn the process. I can check for consistency with eol, col, tropicos, nbn, and bold

**Comment by sckott** [comment]
There's a good chapter here http://r-pkgs.had.co.nz/tests.html on testing. 

I'll write a few tests, and ping here, and feel free to add any more - hard to have too many tests (though one caveat is we don't want too many long running tests, an ideal test suite is comprehensive but quick)

**Comment by jimmyodonnell** [comment]
Awesome; this chapter is great. I'll check out the first few and then try
to jump in.

**Comment by sckott** [comment]
great, thanks

**Comment by sckott** [comment]
I'll add some tests, then I think we should let this fly for the version im pushing to CRAN hopefully today (https://github.com/ropensci/taxize/milestones/v0.7.4) - and we can add other data sources and tests for next version

**Comment by jimmyodonnell** [comment]
Sounds like a great plan!
