### ISSUE TITLE
genbank2uid does not handle errors well

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#506]
`genbank2uid` works in batches of 100 to allow it to progress at a reasonable speed. However, if `genbank2uid` is given an invalid ID then the entire batch is returned as NA. The problem is that the NCBI Eutility elink does not return an error if it receives an unknown ID; it just returns less results than IDs submitted and there is no way I can see to match the successful queries with their result. This can be fixed by making the batch size 1, but this slows things down significantly. 

I have looked into using esummary or esearch and both have their own issues. Esummary throws errors, but will not accept accession numbers (e.g. JQ347180), only gi numbers (e.g. 401836503). Esearch also throws errors and can accept both types of ID, by combining terms with "JQ347180[ACCN]+OR+401836503[GI]", but does not return the result in the order the input IDs are in. I have not seen a way to submit multiple separate searches at once. 

I guess we could check that the IDs exist first, but I cant seem to find a fast way to do that either. The only thing I know if is Esearch, and it can only search one at a time. 

I am not sure what to do about this for now. It seems that getting the taxon ID from the accession/gi ID should a fast, robust process, but I do not know have to make it so. Any ideas?

**Comment by sckott** [comment]
I'll have a look, not sure right now.

**Comment by sckott** [comment]
any insight on this @dwinter ? trying to sort this out too, but no progress yet

**Comment by dwinter** [comment]
Hi both, 

I don't think there is a way around this. The  accession numbers aren't in what the NCBI returns from elink, so if they are used as input there is no way to match them later on. 

So, at some stage you are going to have to do a one-query-per-ID request. The only guidance I can give is that the "lightest" way to do that is with efetch and `rettype=uilist":

http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgidb=nucleotide&id=X78312&rettype=uilist

Maybe the best solution from the R-side is to  document this problem and provide a useful error message when the number of <IdLists> elements is less than the number of IDs. 

You could also provide a function to identify invalid IDs and filter them out before you make the larger cal:

```{r}
is_valid_genbank_id <- function(id){
    q <- paste0("http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=", id)
    response <- httr::GET(q)
    Sys.sleep(1/3) #keep within NCBI rate limits
    response$status_code < 400
}

sapply( c('X78312', 'X121', 'JQ347180'),  is_valid_genbank_id)

```
```
  X78312     X121 JQ347180 
    TRUE    FALSE     TRUE 
```


BTW, thanks for bringing this up @zachary-foster, it will effect the way my  package `rentrez` deals with elink too.

**Comment by sckott** [comment]
thanks @dwinter ! 

this is so madenning that they don't return the input value with matches (and that non matches are dropped)

It seems that elink just drops invalid IDs, so internally in this fxn we can just return those that did match, and warn when there are some that don't match. However, is that not worth it, since users won't know for sure which outputs match which inputs?

**Comment by dwinter** [comment]
I'm pretty sure this is a bug ont eh NCBI side. 

Searching my email I find an (unanswered) message I sent in August last year about these no longer containing an error. One of us should try  reporting it again. 

Can you help us @ncbi? I've tried eutilities@ncbi.nlm.nih.gov but never got a useful reply from that address?

**Comment by sckott** [comment]
Who is best to contact for this?

**Comment by dwinter** [comment]
Wish I knew... The listed email is eutilities@ncbi.nlm.nih.gov  but I've never got a reply from that address. I guess I can try One More Time?

**Comment by sckott** [comment]
I'll ask around to see if anyone knows folks there

**Comment by zachary-foster** [comment]
Thanks for looking into this @dwinter and @sckott! You have confirmed my suspicions that this is not a problem with an easy solution.  

I think the best strategy is to check the validity of each id before looking up the taxonomy information, using something like what @dwinter demonstrated. To avoid unnecessary checking, we could have a boolean variable in the class that stores genbank id (im a little rusty on the particulars of this part of taxize) that stores whether or not the ID has been checked. Then, once it has been verified once, it will not be checked again in future function calls. If the ID came from a trusted source (e.g. an esearch call to ncbi) we can assume it is verified from the start. That way, each function that uses IDs as input could check them, but only if a previously run function has not checked them. In many cases, where the ids have been obtained by querying online databases, checking will not be necessary and there will no performance loss.

**Comment by sckott** [comment]
@zachary-foster good idea that we could have the function not have to check on certain inputs that are already verified

what do you mean by this 

> To avoid unnecessary checking, we could have a boolean variable in the class that stores genbank id

**Comment by zachary-foster** [comment]
Sorry for not explaining more fully. It would be nice each id used by taxize had a variable associated with it that was TRUE if it has been verified and FALSE if not.  Im not sure how hard this would be to implement. To do it elegantly would probably require making the IDs S4 or RC classes, which would likely require minor changes to many functions. If I remember correctly, IDs are currently S3 classes?
For example, if the IDs were S4 classes, we could add a slot called `valid` that could be `NA` if it has not been verified:

```r
setClass("seq_id", slots = list(id = "character", source = "character", valid = "logical"))

verify_id <- function(id) {
  if (is.na(id@valid)) { # has not been checked
    id@valid <- is_valid_genbank_id(id) #return TRUE or FALSE
  }
  if (id@vaid == FALSE) {
    warning("Invalid id detected...")
  }
  return(id)
}

an_id <- new("seq_id", id = "XN2234", source = "genbank", valid = NA)
id <- verify_id(id)
```
This works, but the user has to call the verifying function them self, since R's "copy on modify" behaviour prevents functions from changing their inputs variables in a way that persists after the function ends. RC classes allows objects to be changed in functions:

```r
seq_id <- setRefClass("seq_id",
                      fields = list(id = "character", source = "character", valid = "logical"),
                      methods = list(
                        verify = function() {
                          if (is.na(valid)) { # has not been checked
                            valid <<- is_valid_genbank_id(id) 
                          }
                          if (valid == FALSE) {
                            warning("Invalid id detected...")
                          }
                        }
                      ))

an_id <- seq_id$new(id = "XN2234", source = "genbank", valid = NA)

genbank2uid <- function(id) {
  id$verify()
  # rest of function...
  # ...
}

other_function_using_ids <- function(id) {
  id$verify()
  # rest of function...
  # ...
}


print(an_id$valid)
genbank2uid(an_id) # The first time, an_id$valid is NA, so it queries ncbi. an_id is modified
print(an_id$valid)
other_function_using_ids(an_id) # Now an_id$valid is TRUE or FALSE, so it will not query ncbi
```

**Comment by sckott** [comment]
just saw your email dwinter - i was told about https://twitter.com/Klortho so I tweeted at him on twitter - no response yet 

@dwinter @zachary-foster

**Comment by dwinter** [comment]
The NCBI itself (or it's twitter self) told me that email address. Must be legit :)

**Comment by sckott** [comment]
nice, bueno

**Comment by Klortho** [comment]
Hi, I haven't read this whole ticket in depth but maybe what you're looking for is the "one-to-one" response format, described in the [elink book](http://www.ncbi.nlm.nih.gov/books/NBK25499/). Compare:

* http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=protein&db=gene&id=15718680,157427902,119703751&retmode=json
* http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=protein&db=gene&id=15718680&id=157427902&id=119703751&retmode=json

**Comment by zachary-foster** [comment]
Thanks for the info @Klortho! Yes, I saw and tried that. The problem is that when an invalid ID is given, fewer results are returned and there is no way to match up successful results to their queries.

**Comment by zachary-foster** [comment]
@Klortho. Odd, I tried your example, and when the protein database was used there was a place holder in the results for an invalid ID, but when I used the taxonomy database, no place holder was added. 

Compare:

http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=nucleotide&db=taxonomy&id=AJ748748&id=notavalidid&id=X78312&retmode=json

http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=protein&db=gene&id=15718680&id=notavalidid&id=119703751&retmode=json

**Comment by Klortho** [comment]
Maybe esearch? If you try [this](http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?term=AJ748748[accession]%20OR%20notvalid[accession]%20OR%20X78312[accession]%20OR%20&retmode=json), you get the list of UIDs, and you could parse the `queryTranslation` field to see the valid accessions. I'm sorry -- I'm not an expert, I don't work on the eutils team. Other folks are looking at it here , and you should hear something soon.

**Comment by zachary-foster** [comment]
@Klortho: Thanks for the suggestion! I had not considered that we could use esearch to verify the accession numbers this way. This could be used to verify many accession numbers at once before submitting them to elink. Thanks!

**Comment by sckott** [comment]
@zachary-foster thanks for the clarification.  I think using S4 etc. classes is a bit heavy for this use case, and given performance penalties, seems like we'd need them badly.  We can attach an attribute that states whether an ID is valid or not on the current S3 classes, e.g.,  `attr(x, "valid") <- TRUE #  (or FALSE)` (and we do this now with id objects for other variables). If we did use a class system, i'd prefer to go with R6 :)

**Comment by zachary-foster** [comment]
@sckott I agree it might be overkill to use RC, although more from an implementation rather than performance standpoint. I expect (but I don’t really know) that database querying would be the limiting factor to performance and limiting database queries by identifying valid IDs should take precedence over local machine performance. I had considered using attributes; they seem perfect since they are so lightweight and compatible with the current S3 implementation, but I found out they are lost when subsetting the vector they apply to:
```
> x = 1:10
> attr(x, "valid") <- rep(TRUE, 10)
> x
 [1]  1  2  3  4  5  6  7  8  9 10
attr(,"valid")
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> x[2:4]
[1] 2 3 4
```
I expect that users will be subsetting their ID lists often, so Im not sure we can rely on attributes. 
Perhaps for operations internal to taxize. 
However, it would require a lot of work and a backwards-compatibility-breaking update to use a different class system, so yes, Im not convinced it is worth it either. 

I had not heard of S6. Thanks for the reference! I dont know anything about it, but if it a lighter weight version of RC, it sounds good to me.

**Comment by dwinter** [comment]
Hi all, 

Had a reply from NCBI help desk, who asked for some example XMLs. Have send themalong, so will keep you in the loop if I hear anything more.

**Comment by sckott** [comment]
thanks david

**Comment by sckott** [comment]
@zachary-foster see #508

**Comment by dwinter** [comment]
FWIW, NBCI says 

> 
> Genbank accessions are not valid input for elink. You must input GI numbers for an elink request.
> 
> Best Regards,

To which I replied

> Hi,
> 
> Thanks for the answer, 
> 
> I have to say I find it a little counter-intuitive that genbank acessions could be invalid input but still appear to work as expected without raising a warning or error.  
> 
> If accessions are all that a user has, what it is the most efficient way to bulk convert genbank accessions to GI numbers? (i..e without making 1 request per acession)?
> 

If NCBI doesn't have a good way to do the conversion, it might be possible via bioMart or some other ID translation. I think people will often come with only accessions, and concerting a bunch of them one at a time would be pretty painful.

**Comment by sckott** [comment]
Bummer. 

I am working on an API https://github.com/sckott/gbcheck/tree/dropwebdis that's super fast, cause it just stores all the keys in Redis, so it's just a key-value lookup. I just have it setup right now to check that acc. numbers exist, but could easily have one route to get GI (value) from acc. (key) and another to get acc. (value) from GI (key)

thoughts?

**Comment by dwinter** [comment]
Well, it looks awesome! 

Inter-conversion of IDs is about 20% of bioinformatics, so it's possible another service already exists, though the ones I'm familiar with handle between-database conversions. I'm sure you could get fast conversions with `dropwebids`, just thinking about the time and effort required to code/host/maintain it..

**Comment by sckott** [comment]
> just thinking about the time and effort required to code/host/maintain it.. 

right, i've considered that, but it does seem like there's no good sol'n now, correct?  so there is a need. and in terms of cost, a reserved micro instance is pretty cheap. in terms of code, it's pretty simple :)

**Comment by dwinter** [comment]
Yeah, as far as I know there is no fat web service for checking/converting within NCBI (will see if they can provide any insight). So this would definitely serve a purpose. If it's not too painful to build I think it would help a lot of users.

**Comment by sckott** [comment]
cool, well I'll get it up soon and see what the response is like from folks

**Comment by sckott** [comment]
okay, see readme, api is up, see what you think https://github.com/sckott/gbcheck

**Comment by sckott** [comment]
@dwinter @zachary-foster

**Comment by sckott** [comment]
Note there's just a tiny bit of data in there

**Comment by zachary-foster** [comment]
@sckott Good idea! It would be nice to have this functionality work fast.

I am not familiar with the tools you used to make it. How often would it be updated from NCBI? 

I tried out a few of the examples, but got the following error:

```
09:28:26~> curl 'http://52.33.101.178:8877/acc/AACY024124486,AACY024124483,asdfd,asdf,AACY024124476'
curl: (7) couldn't connect to host
```

Am I doing something wrong?

**Comment by sckott** [comment]
@zachary-foster sorry, down right now trying to fix some things, i'll put back up in a bit

**Comment by sckott** [comment]
@zachary-foster okay, try again, there's 3 million loaded in there

**Comment by zachary-foster** [comment]
Ok, its working now. Its fast; nice! So is this what we will use for genbank2id then?

**Comment by sckott** [comment]
> How often would it be updated from NCBI?

they update the dump once a week on Sunday, so i'd get a chron job setup to just grab that and refresh data

> So is this what we will use for genbank2id then?

maybe, i need to re-architect a bit as the database I used is the wrong choice, but it shouldn't take too long. it might be a bit slower with the new setup, but will be more affordable (the current database Redis, is all in memory, so really fast, but to get lots of memory on a server is expensive), will move to storing data in SQL db, then just use Redis for caching

**Comment by mpnelsen** [comment]
I'm also having trouble with JQ004924 (using taxize_0.7.4.9300): 

> genbank2uid("JQ004924")
[1] NA
attr(,"class")
[1] "uid"
attr(,"match")
[1] "not found"
attr(,"uri")
[1] NA
Warning message:
In func(unique_input, ...) : An error occured looking up taxon ID(s).

I think I'd tried this same accession a couple of weeks ago w/o problems, but it looks like the accession was updated on 22 Mar 2016.   http://www.ncbi.nlm.nih.gov/nuccore/JQ004924

Is this something that will likely work itself out in a week or so, once databases are refreshed/updated?  Thanks - Matt

**Comment by zachary-foster** [comment]
I have had issues like this too, where accessions that I know worked months ago no longer work. Very odd...

**Comment by mpnelsen** [comment]
thanks, @zachary-foster - i see JQ347180 (the one you initially wrote about) works now - so i'll try the batch with my problematic accession again later.

**Comment by mpnelsen** [comment]
...and...JQ004924 now works again.

> genbank2uid("JQ004924")
[1] "4868"
attr(,"class")
[1] "uid"
attr(,"match")
[1] "found"
attr(,"uri")
[1] "http://www.ncbi.nlm.nih.gov/taxonomy/4868"

**Comment by sckott** [comment]
I've taken the API down - anyone have sol'n for this?

**Comment by zachary-foster** [comment]
@dwinter Did you ever get a response to your question to NCBI helpdesk? 

> If accessions are all that a user has, what it is the most efficient way to bulk convert genbank accessions to GI numbers? (i..e without making 1 request per acession)?

It seems like this is an NCBI problem in regards to bulk verification. I find it especially odd that they said:

> Genbank accessions are not valid input for elink. You must input GI numbers for an elink request.

when GI numbers are being phased out. 

In the short term, we can fix this problem, by setting the batch size to one:

https://github.com/ropensci/taxize/blob/master/R/genbank2uid.R#L30

This will slow the function down significantly, but at least the users will know which queries failed. 
Alternatively, we can expose the batch size option to the user, set the default to 100, and issue a warning message saying that they should rerun the query with a batch size of one to identify the invalid accessions when there is a failed query and the batch size is greater than one.

**Comment by sckott** [comment]
> Alternatively, we can expose the batch size option to the user, set the default to 100...

this seems reasonable

**Comment by zachary-foster** [comment]
Want me to implement that?

**Comment by sckott** [comment]
@zachary-foster @dwinter 

Good news , just got a $500 grant from Amazon research for this, so i'll get it up soon, and this should mean it can be up for the long term - by the time the 500 runs out will figure out something else

**Comment by sckott** [comment]
@zachary-foster @dwinter okay, the API is back up  gbids.xyz is back up https://github.com/sckott/gbids docs: http://recology.info/gbidsdocs/  hopefully for good now,

**Comment by zachary-foster** [comment]
I did not notice your last comment on Jun 30 until now. Nice!

**Comment by sckott** [comment]
closing - please do open new issues as you see fit if there are still unresolved issues within this
