### ISSUE TITLE
ID class

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#508]
moved from #506 

e.g using `R6`

``` r
library('R6')

MultiTaxonId <- R6Class(
  "MultiTaxonId",
  #inherit = TaxonId,
  public = list(
    ids = NA,
    print = function() {
      cat(paste0("<NCBI IDs> ", paste0(self$fetch_ids(), collapse = ", ")), sep = "")
      invisible(self)
    },
    get_ids = function(x) {
      tmp <- unclass(get_uid(x))
      taxa <- list()
      for (i in seq_along(tmp)) {
        taxa[[i]] <- TaxonId$new(tmp[i], x[i], attr(tmp, "uri")[i], attr(tmp, "match")[i])
      }
      self$ids <- taxa
    },
    fetch_uris = function() {
      res <- c() 
      for (i in seq_along(self$ids)) res[i] <- self$ids[[i]]$uri
      return(res)
    },
    fetch_matches = function() {
      res <- c() 
      for (i in seq_along(self$ids)) res[i] <- self$ids[[i]]$match
      return(res)
    },
    fetch_taxa = function() {
      res <- c() 
      for (i in seq_along(self$ids)) res[i] <- self$ids[[i]]$taxa
      return(res)
    },
    fetch_ids = function() {
      res <- c() 
      for (i in seq_along(self$ids)) res[i] <- self$ids[[i]]$id
      return(res)
    }
  )
)

TaxonId <- R6Class(
  "TaxonId",
  public = list(
    id = NA,
    taxa = NA,
    uri = NA,
    match = NA,
    initialize = function(id, taxa, uri, match) {
      if (!missing(id)) self$id <- id
      if (!missing(taxa)) self$taxa <- taxa
      if (!missing(uri)) self$uri <- uri
      if (!missing(match)) self$match <- match
    },
    print = function() {
      cat(paste0("<NCBI ID> ", self$id), "\n")
      cat(paste0("  taxon: ", self$taxa), "\n")
      cat(paste0("  match: ", self$match), "\n")
      cat(paste0("  uri: ", self$uri), "\n")
      invisible(self)
    }
  )
)

`[.MultiTaxonId` <- function(x, i) {
  x$ids[i]
}

`[[.MultiTaxonId` <- function(x, i) {
  x$ids[[i]]
}

`[.TaxonId` <- function(x, i) {
  x$id[i]
}
```

Using it

``` r
x <- MultiTaxonId$new()
x$get_ids(c("Chironomus riparius", "Quercus douglasii", "Poa annua"))
x
#> <NCBI IDs> 315576, 465759, 93036
x$ids
#> [[1]]
#> <NCBI ID> 315576 
#>   taxon: Chironomus riparius 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/315576 
#> 
#> [[2]]
#> <NCBI ID> 465759 
#>   taxon: Quercus douglasii 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/465759 
#> 
#> [[3]]
#> <NCBI ID> 93036 
#>   taxon: Poa annua 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/93036 

x$fetch_ids()
#> [1] "315576" "465759" "93036" 
x$fetch_uris()
#> [1] "http://www.ncbi.nlm.nih.gov/taxonomy/315576" "http://www.ncbi.nlm.nih.gov/taxonomy/465759"
#> [3] "http://www.ncbi.nlm.nih.gov/taxonomy/93036" 
x$fetch_matches()
#> [1] "found" "found" "found"
x$fetch_taxa()
#> [1] "Chironomus riparius" "Quercus douglasii"   "Poa annua"          

# subset
x$ids[[1]]
#> <NCBI ID> 315576 
#>   taxon: Chironomus riparius 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/315576 
x$ids[3]
#> [[1]]
#> <NCBI ID> 93036 
#>   taxon: Poa annua 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/93036 

x$ids[[3]]
#> <NCBI ID> 93036 
#>   taxon: Poa annua 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/93036 
x$ids[2:3]
#> [[1]]
#> <NCBI ID> 465759 
#>   taxon: Quercus douglasii 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/465759 
#> 
#> [[2]]
#> <NCBI ID> 93036 
#>   taxon: Poa annua 
#>   match: found 
#>   uri: http://www.ncbi.nlm.nih.gov/taxonomy/93036 
```

**Comment by sckott** [comment]
@zachary-foster

**Comment by zachary-foster** [comment]
@sckott Thanks for the demonstration. I will look at it more closely soon; I have been busy this week. Are you considering implementing R6 classes in taxize? I am considering using a class system for IDs in my [metacoder](https://github.com/grunwaldlab/metacoder) package. Perhaps we can use the same classes. Probably should, since metacoder uses taxize and traits to parse and fill in gaps in taxonomic metadata associated with samples. Im not sure if two packages can depend upon eacother, but if so, metacoder has a plotting function that could be used to make a default `plot.taxize_id_class` for a list of taxon ids, so users could type `plot(taxon_list)` and get a tree back with color/size relative to taxon abundance:

![rplot02](https://cloud.githubusercontent.com/assets/6090555/13333019/93031686-dbb9-11e5-8724-dab17d3cbcee.png)

**Comment by sckott** [comment]
> Thanks for the demonstration. I will look at it more closely soon; I have been busy this week. Are you considering implementing R6 classes in taxize? 

Possibly. It could lead to breaking changes, which I want to avoid, but if it's compelling enough then it may be worth it. I'll have to think more about this. Spec out how things would work

> I am considering using a class system for IDs in my metacoder package. Perhaps we can use the same classes. 

Yeah, makes sense

> Im not sure if two packages can depend upon eacother, but if so, metacoder has a plotting function that could be used to make a default plot.taxize_id_class for a list of taxon ids, so users could type plot(taxon_list) and get a tree back with color/size relative to taxon abundance:

I would probably want to point users to your package instead of trying to integrate your functions here since yeah best to avoid one requiring the other. Though we could put metacoder into `Enhances` (so users would have to explicitly load metacoder to use the plot method) and use in a vignette here e.g., which wouldn't lead to problems i dont think. 

> By the way, I am updating metacoder right now, so trying to build the vignettes probably wont work for a few days. Should have used a dev branch, but forgot.

Okay, thanks

**Comment by zachary-foster** [comment]
> Though we could put metacoder into Enhances (so users would have to explicitly load metacoder to use the plot method) and use in a vignette here e.g., which wouldn't lead to problems i dont think. 

Thats a good idea. If an ID class is implemented that stores the parent id (thus constituting an edge list), then I can add a plot method for that class to metacoder, so when both packages are loaded, `plot(taxon_id_list)` would work

**Comment by sckott** [comment]
nice, sounds good. 

> If an ID class is implemented that stores the parent id

so for your purposes then every object needs to have the parent id?

**Comment by sckott** [comment]
@zachary-foster i've started a sep. repo https://github.com/ropenscilabs/taxa so we can more freely explore taxon classes - we may not end up wanting to have a sep. pkg, but maybe we will.

**Comment by zachary-foster** [comment]
> so for your purposes then every object needs to have the parent id?

Yes, or some other information from which a graph structure can be inferred. In my package, I keep taxon information in a data frame; one row per unique taxon id and its parent taxon id. Other columns store information relating to the taxon. This formats reduces the tree structure to a 2-dimensional table, making it much easier to manipulate in R. It is also not reliant on an explicit rank (e.g. genus, family), which is useful for less orderly data.  If there are items (e.g. sequences) assigned to that taxonomy, then their information is in an other data frame, one row per item, with the taxon id they are assigned to.

I could parse taxonomic information from other formats (e.g. one data frame per taxon, each row or column corresponding to a taxonomic rank) or look up information from taxon ids on a per-item basis, but this would be less efficient for graphing purposes. 


>@zachary-foster i've started a sep. repo https://github.com/ropenscilabs/taxa so we can more freely explore taxon classes - we may not end up wanting to have a sep. pkg, but maybe we will. 

Great! I have been thinking about this problem for the past few weeks and I think I have an idea of one way to go about it. Basically the taxon table and item table described above wrapped in a class with some sub setting functions defined. I will put some test code there soon so we can discuss it.

**Comment by sckott** [comment]
> I will put some test code there soon so we can discuss it.

great, sounds good

**Comment by zachary-foster** [comment]
Hi @sckott, I am just getting back to this. This looks like a good way to go about making a class for a taxon id. I was originally talking about making a class of item (e.g. sequence) ids, rather than taxon ids, but the same idea could be adapted to item ids. I will brainstorm more about this on the `taxa` repository.

**Comment by sckott** [comment]
Okay, sounds good

**Comment by sckott** [comment]
Now that `taxa` is on CRAN - start playing with using probably `taxa::taxon` for output of `get_*()` functions - already can think of two changes we probably need to make to `taxa::taxon`:

- allow arbitrary attributes to be assigned
- probably explicitly add a `uri` field for a uri pointing to that taxon on the web somewhere

**Comment by sckott** [comment]
started working on incorporating `taxa` classes in `taxa-ids` branch

**Comment by sckott** [comment]
notes on taxa integration: 

- is there any way from a `Taxa` object to get all ids, or all ranks, etc. across all `Taxon`'s within it
- ...

**Comment by zachary-foster** [comment]
yes, on the `eval` branch `taxon_ids`, `taxon_names`, and `taxon_ranks` are character-based S3 getters/setters. `obj$ids`, `obj$ranks`, and `obj$names` are R6 object-based getters/setters (active bindings).

**Comment by sckott** [comment]
ok, thanks

**Comment by sckott** [comment]
@zachary-foster looking at taxa integration again, where are you at on the `eval` and `vectorize` branches, and how do those two branches relate to one another?  i can't remember now exactly what I needed for this taxa/taxize integration to work, but thought id start with seeing where you are for pusingh to CRAN so I can build on something that won't change a huge amount

**Comment by zachary-foster** [comment]
Hi @sckott, I just got back to working on it this the last few weeks.  I have a pretty good idea now of how things should work, but I need to finish changing the code so that all of the new vector-based classes can accept names, and make the `taxon` class support synonyms. In another week or so I should have most of the classes relevant to `taxize` done and I don't expect there to be any large changes after that. I cant push to CRAN yet though because the code currently needs the github versions of `vctrs` and `tibble`.

The `vectorize` branch will be the one that replaces `master` eventually. 

I looked through all of the exported `taxize` functions and took some notes on how their output could be encoded with the new `taxa` vectors. You can see the notes here:

https://github.com/ropensci/taxa/blob/vectorize/notes/taxize_integration.Rmd

They are just some rough ideas that I considered when I was rewriting the classes. All of the classes besides `taxonomy` and `taxmap` will now behave like base R vectors, so you can use them as columns in data.frames and tibbles, which should make them easier to integrate with other information.

**Comment by sckott** [comment]
Thanks for the update and those notes, will have a good look at thhose. Any idea when those versions of vctrs and tibble you need will be on CRAN?

**Comment by zachary-foster** [comment]
I dont know when they will be on CRAN, but there seem to be a lot of work going on for `vctrs`, so I expect they will update it often.

**Comment by sckott** [comment]
okay, for the next milestone https://github.com/ropensci/taxize/milestone/20 want to release v1, and for obvious reasons want to make sure stuff is stable in the taxa things we depend on here before releasing that

**Comment by sckott** [comment]
closing - work on taxa-work - will open new issues as needed - getting close to finishing off
