### ISSUE TITLE
Return of synonyms instead of accepted names in CoL

### ISSUE THREAD

**Issue by JoStaerk** [ropensci/taxize#511]
I am working on the DISKo project, using taxize to get the accepted names for a large number of species names from the Catalogue of Life (CoL).
I found for at least 5% of the species the new taxize version returns synonyms instead of accepted names from CoL. However, the returned Genus is the accepted Genus. I noticed, because Genus and Species name did not match. Attached are some returned example species. I further compared some of the species names that were retrieved with the previous version of taxize and noticed that this issue only occurs since we are using the new version. 
Any help on this issue would be very much appreciated. 

[ColCheckTaxize.xlsx](https://github.com/ropensci/taxize/files/150828/ColCheckTaxize.xlsx)

**Comment by sckott** [comment]
Hi @JoStaerk - Thanks for the issue.  I'll have a look. What version of `taxize` are you using?  And what R version?

**Comment by JoStaerk** [comment]
Hi @sckott I am using taxize version 0.5.2 and R version 3.2.0 with R Studio version 0.99.441.
Thank you.

**Comment by sckott** [comment]
most recent version is `0.7`  https://cran.rstudio.com/web/packages/taxize/, can you try it and let me know if the same problems happen

**Comment by JoStaerk** [comment]
I updated R to version 3.2.1 (It did not work in 3.2.2) and taxize to the most recent and it returns the correct names  if I run them separately in the classification function. When I run them with the code we used before,  it works for a while but then breaks off after a couple of species. It also returns "No encoding supplied: defaulting to UTF-8" after each species. Any idea what might be the problem? Thank you

**Comment by sckott** [comment]
> When I run them with the code we used before, it works for a while but then breaks off after a couple of species. 

What breaks?  Can you paste in the error messages?

> It also returns "No encoding supplied: defaulting to UTF-8" after each species.

that's  problem in the new `httr`, there's a problem where it prints that, but it's just a warning, nothing to worry about

**Comment by JoStaerk** [comment]
Sorry for being unclear, it seems to be only a problem for particular species:

Warning messages:
1: In FUN(X[[i]], ...) : Species 'Agelaius cyanopus' not found!
 Returning NA!
2: In FUN(X[[i]], ...) : Species 'Agelaius flavus' not found!
 Returning NA!
3: In FUN(X[[i]], ...) : Species 'Agelaius icterocephalus' not found!
 Returning NA!
4: In FUN(X[[i]], ...) : Species 'Agelaius ruficapillus' not found!
 Returning NA!
5: In FUN(X[[i]], ...) : Species 'Agelaius thilius' not found!
 Returning NA!
6: In FUN(X[[i]], ...) : Species 'Agelaius xanthophthalmus' not found!
 Returning NA!
7: In FUN(X[[i]], ...) : Species 'Ajaia ajaja' not found!
 Returning NA!

**Comment by sckott** [comment]
Thanks for errors, what function was called, can you give an example with some taxa inputs

**Comment by JoStaerk** [comment]
Hi, 
it seems to work now. There are just some species that cannot be found even though they are in CoL, e.g. when I run:
classification(c("Abeillia abeillei", "Acanthopagrus australis", "Acipenser medirostris", "Aetobatus flagellum"), db="col")

And as a minor issue, for some species only the epithet is returned instead of the complete species name, e.g.
> classification(c("Agkistrodon howardgloydi", "Agkistrodon russeolus", "Amaurornis moluccanus"), db="col")

Retrieving data for taxon 'Agkistrodon howardgloydi'

No encoding supplied: defaulting to UTF-8.

Retrieving data for taxon 'Agkistrodon russeolus'

No encoding supplied: defaulting to UTF-8.

Retrieving data for taxon 'Amaurornis moluccanus'

No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
No encoding supplied: defaulting to UTF-8.
$`Agkistrodon howardgloydi`
                                 name         rank                               id
1                            Animalia      Kingdom 5ede24b0534ebd5e1f552d5b9f874a6a
2                            Chordata       Phylum 4313bc7637e1fc1feb316a4dea2b668b
3                            Reptilia        Class f2e91eb663bb9950c972474f65d2693b
4                            Squamata        Order d324f3777e98688584cf8b68d0f06e5f
5                           Viperidae       Family 1bbbbf277a74ddcfe10e66424a7fbfde
6                         Agkistrodon        Genus bb53f9f1c1dc3a46e208cddf0fe3cbfc
7                          bilineatus      Species ecf716d37a422bc89d1f5d8d9a4df878
8 Agkistrodon bilineatus howardgloydi Infraspecies 1824e859f8d462b78c62b3ee660e6221

$`Agkistrodon russeolus`
                              name         rank                               id
1                         Animalia      Kingdom 5ede24b0534ebd5e1f552d5b9f874a6a
2                         Chordata       Phylum 4313bc7637e1fc1feb316a4dea2b668b
3                         Reptilia        Class f2e91eb663bb9950c972474f65d2693b
4                         Squamata        Order d324f3777e98688584cf8b68d0f06e5f
5                        Viperidae       Family 1bbbbf277a74ddcfe10e66424a7fbfde
6                      Agkistrodon        Genus bb53f9f1c1dc3a46e208cddf0fe3cbfc
7                       bilineatus      Species ecf716d37a422bc89d1f5d8d9a4df878
8 Agkistrodon bilineatus russeolus Infraspecies 29d35be61ff86b966d516ced4281bbee

$`Amaurornis moluccanus`
                           name         rank                               id
1                      Animalia      Kingdom 5ede24b0534ebd5e1f552d5b9f874a6a
2                      Chordata       Phylum 4313bc7637e1fc1feb316a4dea2b668b
3                          Aves        Class 67847d320573ff18b0384e22afe97ed8
4                    Gruiformes        Order 703418678f52f060e497572c65627777
5                      Rallidae       Family 868091891654ced2dac2e81f5caa36c3
6                    Amaurornis        Genus 706471bf6b1f98f46a65781de4431808
7                      olivacea      Species 15fba9d4712f55f93e8367df6ca49b5a
8 Amaurornis olivacea moluccana Infraspecies 451a411ff296852436b21f5e3bf1abad

attr(,"class")
[1] "classification"
attr(,"db")
[1] "col"
>

**Comment by sckott** [comment]
Thanks for this, i'll have a  look and get back to you

**Comment by sckott** [comment]
@JoStaerk there's a bug introduced in `col_search` parsing because COL has another category I haven't seen `misapplied name` for the name status, fixing that now

**Comment by sckott** [comment]
yeah, the XML COL returns only has the epithet alone without the genus name

```
<taxon>
    <id>ecf716d37a422bc89d1f5d8d9a4df878</id>
    <name>bilineatus</name>
    <rank>Species</rank>
    <name_html>
        <i>Agkistrodon bilineatus howardgloydi</i>
        Conant, 1984
    </name_html>
    <url>
        http://www.catalogueoflife.org/col/details/species/id/ecf716d37a422bc89d1f5d8d9a4df878
    </url>
</taxon>
```

**Comment by sckott** [comment]
@JoStaerk try again after reinstalling from github, `devtools::install_github("ropensci/taxize")`

let me know if you get results you expect now

**Comment by sckott** [comment]
closing inactivity
