### ISSUE TITLE
Add open tree of life as a data source

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/taxize#517]
Would it make sense to add the Open Tree of Life TNRS as a data source to taxize?

**Comment by sckott** [comment]
good idea, don't know anything about it. can you point me to the docs? i imagine it's already in `rotl`?

**Comment by fmichonneau** [comment]
Yes, it's already in `rotl`. The functions are prefixed with `tnrs_` and the relevant one for `taxize` is probably only `tnrs_match_names`. The documentation for the API endpoint is: https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#match_names

Let me know if/how I can help!

**Comment by sckott** [comment]
Cool, will ping you with questions :)

**Comment by sckott** [comment]
@fmichonneau first draft of the function in, does it look okay?

**Comment by fmichonneau** [comment]
Yes, that looks good. :+1: 

  Thanks!

**Comment by sckott** [comment]
@fmichonneau added `get_tolid()`, and can do `classification(..., db = "tol")` now, let me know if you have any thoughts on those

**Comment by sckott** [comment]
see https://github.com/ropensci/rotl/issues/86
