### ISSUE TITLE
get_colid warning

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#523]
Hi @sckott, is the warning below supposed to happen? It does not appear using `get_uid`. Thanks!

```
> taxize::get_colid(c("Carnivora"), ask = FALSE, rows = 1)

Retrieving data for taxon 'Carnivora'

[1] "29ff0553e8930d7e79b3ff4d1a753f62"
attr(,"class")
[1] "colid"
attr(,"match")
[1] "found"
attr(,"uri")
[1] "http://www.catalogueoflife.org/col/browse/tree/id/29ff0553e8930d7e79b3ff4d1a753f62"
Warning message:
In data.frame(..., check.names = FALSE) :
  row names were found from a short variable and have been discarded
```

**Comment by sckott** [comment]
@zachary-foster install again and see if that warning goes away - I actually got an error on that call, so i made a fix for that, hopefully fixes your warning

**Comment by zachary-foster** [comment]
@sckott Ok, after `devtools::install_github("ropensci/taxize")`, the warning went away. I also ran into the error when I updated to the newest CRAN version. Thanks for the fast response!

**Comment by sckott** [comment]
cool, glad it worked
