### ISSUE TITLE
COI matches COII

### ISSUE THREAD

**Issue by tpaulson1** [ropensci/taxize#524]
I'm trying to pull in COI sequences for Apis mellifera, and the best hit is actually a COII sequence:

`ncbi_byname(taxa="Apis mellifera",gene=c("COI"),seqrange = "1:5000")`

```
           taxon
1 Apis mellifera
                                                                                                                                                                                          gene_desc
1 Apis mellifera haplotype M4c''' tRNA-Leu (trnL) gene, partial sequence; trnL-COII intergenic spacer, complete sequence; and cytochrome oxidase subunit II (COII) gene, partial cds; mitochondrial
      gi_no     acc_no length
1 313671827 HQ260378.1   1228
```

Looking at the [genbank file](http://www.ncbi.nlm.nih.gov/nuccore/HQ260378.1) it's clearly trnLeu-COII, not cytochrome oxidase I. My guess is that "COI" is matching "COII".

**Comment by sckott** [comment]
Thanks for the issue. However, we have made the ncbi gene seq functions defunct in this package - see https://github.com/ropensci/taxize/blob/master/NEWS.md#deprecated-and-defunct - And those fxns are now in `traits` package - Can you open this issue in that repo https://github.com/ropensci/traits/issues  and we'll address it there.
