### ISSUE TITLE
fix examples in `rankagg`

### ISSUE THREAD

**Issue by jangorecki** [ropensci/taxize#529]
There is an attempt to load `vegan` namespace in examples [rankagg.Rd#L23](https://github.com/ropensci/taxize/blob/5ad078c918a07552b392f9b89354fec357b4eb03/man/rankagg.Rd#L23), code below is the results from examples.
As `vegan` is suggested dependency, it should not be required to run examples according to [R-exts](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages). This can be conditionally escaped with `requireNamespace`.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

```
* checking examples ... ERROR
Running examples in ‘taxize-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: rankagg
> ### Title: Aggregate data by given taxonomic rank
> ### Aliases: rankagg
> 
> ### ** Examples
> 
> library("vegan")
Error in library("vegan") : there is no package called ‘vegan’
Execution halted
```

**Comment by sckott** [comment]
Thanks for this. Will fix
