### ISSUE TITLE
tax_name() not working in last update

### ISSUE THREAD

**Issue by ibartomeus** [ropensci/taxize#537]
In the last update itis_acceptnames and tax_name were updated, but tax_name() stop working with a cryptic message (at least in my computer).

```
devtools::install_github("ropensci/taxize", force = TRUE)
library(taxize)
species <- c("Osmia rufa", "osmia bicornis", "Osmia ruffa", 
                         "Osmia wikifluqie", "watermelon pie", "Osmia sp.")
itis_acceptname(get_tsn(species)) #works great!
tax_name(species, get = "genus") #fails
tax_name("Osmia rufa", get = "genus") #fails
```

The error is: 

```
Error in lapply(X = X, FUN = FUN, ...) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/taxize/data/Rdata.rdb' is corrupt
In addition: Warning messages:
1: In lapply(X = X, FUN = FUN, ...) :
  restarting interrupted promise evaluation
2: In lapply(X = X, FUN = FUN, ...) : internal error -3 in R_decompress1
```

I tried deleting the corrupt file and loading again taxize, but nothing changes.
Thanks in advance!

Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.891)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Madrid               
 date     2016-05-21                  

Packages -----------------------------------------------------------------------------
 package    * version    date       source                          
 ape          3.4        2015-11-29 CRAN (R 3.2.3)                  
 assertthat   0.1        2013-12-06 CRAN (R 3.2.0)                  
 bold         0.3.5      2016-03-29 CRAN (R 3.2.4)                  
 brew         1.0-6      2011-04-13 CRAN (R 3.2.0)                  
 chron        2.3-47     2015-06-24 CRAN (R 3.2.0)                  
 codetools    0.2-14     2015-07-15 CRAN (R 3.2.3)                  
 curl         0.9.7      2016-04-10 CRAN (R 3.2.4)                  
 data.table   1.9.6      2015-09-19 CRAN (R 3.2.0)                  
 devtools   * 1.10.0     2016-01-23 CRAN (R 3.2.3)                  
 digest       0.6.9      2016-01-08 CRAN (R 3.2.3)                  
 foreach      1.4.3      2015-10-13 CRAN (R 3.2.0)                  
 git2r        0.13.1     2015-12-10 CRAN (R 3.2.3)                  
 github     * 0.9.7      2016-05-12 Github (cscheid/rgithub@b4aaa23)
 httr         1.1.0      2016-01-28 CRAN (R 3.2.3)                  
 iterators    1.0.8      2015-10-13 CRAN (R 3.2.0)                  
 jsonlite     0.9.20     2016-05-10 CRAN (R 3.2.5)                  
 knitr        1.12.3     2016-01-22 CRAN (R 3.2.3)                  
 lattice      0.20-33    2015-07-14 CRAN (R 3.2.3)                  
 magrittr     1.5        2014-11-22 CRAN (R 3.2.0)                  
 memoise      1.0.0      2016-01-29 CRAN (R 3.2.3)                  
 nlme         3.1-126    2016-03-14 CRAN (R 3.2.4)                  
 plyr         1.8.3      2015-06-12 CRAN (R 3.2.0)                  
 R6           2.1.2      2016-01-26 CRAN (R 3.2.3)                  
 Rcpp         0.12.4     2016-03-26 CRAN (R 3.2.4)                  
 reshape      0.8.5      2014-04-23 CRAN (R 3.2.0)                  
 reshape2     1.4.1      2014-12-06 CRAN (R 3.2.0)                  
 rncl         0.6.0      2015-07-22 CRAN (R 3.2.0)                  
 Rook         1.1-1      2014-10-20 CRAN (R 3.2.0)                  
 rotl         3.0.0      2016-04-26 CRAN (R 3.2.5)                  
 rredlist     0.1.0      2016-01-26 CRAN (R 3.2.3)                  
 stringi      1.0-1      2015-10-22 CRAN (R 3.2.0)                  
 stringr      1.0.0      2015-04-30 CRAN (R 3.2.0)                  
 taxize     * 0.7.6.9157 2016-05-21 Github (ropensci/taxize@0f8e6ac)
 withr        1.0.1      2016-02-04 CRAN (R 3.2.3)                  
 xml2         0.1.2      2015-09-01 CRAN (R 3.2.0)

**Comment by sckott** [comment]
tested under that R version 3.2.3, still works for me. Can you restart R session, and try again to be sure that's not it?

**Comment by ibartomeus** [comment]
You were right! I re-started R and it complained about Rcpp. After updating
Rcpp it runs smoothly. Thanks a lot for the fast troubleshooting!

On Sat, May 21, 2016 at 9:43 AM Scott Chamberlain <notifications@github.com>
wrote:

> tested under that R version 3.2.3, still works for me. Can you restart R
> session, and try again to be sure that's not it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/taxize/issues/537#issuecomment-220764261>
>
-- 
-- 
Ignasi Bartomeus PhD
www.bartomeuslab.com
@ibartomeus
Skype: nachobartomeus

Dpto. Ecología Integrativa
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio s/n
Isla de la Cartuja
41092, Sevilla (Spain)

**Comment by sckott** [comment]
so what version of Rcpp do you have now?

**Comment by ibartomeus** [comment]
Rcpp       0.12.5

On Sat, May 21, 2016 at 9:49 AM Scott Chamberlain <notifications@github.com>
wrote:

> so what version of Rcpp do you have now?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/taxize/issues/537#issuecomment-220764492>
>
-- 
-- 
Ignasi Bartomeus PhD
www.bartomeuslab.com
@ibartomeus
Skype: nachobartomeus

Dpto. Ecología Integrativa
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio s/n
Isla de la Cartuja
41092, Sevilla (Spain)

**Comment by sckott** [comment]
thx
