### ISSUE TITLE
ncbi_get_taxon_summary URI too long error

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#541]
via https://twitter.com/daattali/status/742451025852829696 @daattali 

> `taxize::ncbi_get_taxon_summary()` based on binary searching for length, it seems like at around 1000 ids it starts giving probs

**Comment by daattali** [comment]
Until this gets implemented, this is my hacky workaround code (I have a flight to catch in 3 hours so I don't care how ugly this code is at the moment, don't judge)

```
  total <- length(ids)
  start <- 1
  taxinfos <- list()
  while(TRUE) {
    end <- min(start + 499, total)
    taxinfo <- taxize::ncbi_get_taxon_summary(ids[start:end])
    taxinfos <- c(taxinfos, list(taxinfo))
    if (end >= total) {
      break()
    }
    start <- end + 1
  }
  taxinfos <- do.call(rbind, taxinfos) 
```

**Comment by sckott** [comment]
reinstall - though I didn't actually fix this as I think best users do their own chunking of ids - but added a message that's thrown if more than ~ 8000 characters long, and some notes to the man page.
