### ISSUE TITLE
iucn_summary() not able to find species

### ISSUE THREAD

**Issue by mcsiple** [ropensci/taxize#543]
When I use `iucn_summary()` with a scientific name, I get a new error that I haven't encountered before. For example, 

Input:
`xx <- iucn_summary("Thunnus thynnus")`

Resulting error message:

```r
In FUN(X[[i]], ...) : Species 'Thunnus thynnus' not found!
```
 Returning NA!

I'm using R version 3.3.0 on Mac OS 10.10.5 .

(I've also checked species from the code samples in the vignette)
I have used taxize before to look up the IUCN status for this species, so I'm wondering if there is might be a bug somewhere that is preventing them from being looked up. Again, this is something that worked great in the past.  Thank you in advance for checking it out!

**Comment by sckott** [comment]
thanks! I'll have a look

**Comment by sckott** [comment]
@mcsiple short answer is we know use `rredlist` package to get some Redlist data, and  you need an API key (authenticaiton) for that. just a sec

**Comment by sckott** [comment]
@mcsiple go here http://apiv3.iucnredlist.org/api/v3/token to request an API token

also, reinstall from github `devtools::install_github("ropensci/taxize")`  and you should now get an informative error message before you get your IUCN token, After you get your token, see ?iucn_summary manual file for details on how to use

**Comment by mcsiple** [comment]
Excellent, thank you Scott. I requested one and I'm looking forward to testing it out! I wonder if I had a key stored in my RProfile from before-- I somehow managed to get IUCN statuses with taxize before, without having an API key.

**Comment by sckott** [comment]
> I somehow managed to get IUCN statuses with taxize before, without having an API key.

we added this recently 

do let me know once you get the key if it works as expected

**Comment by mcsiple** [comment]
API key took 6 days from request (although I've been told it will take less time in the future) and worked like a charm. I now have the key in a separate file, and call it whenever I used iucn_summary. All is working smoothly. Thank you for answering my question so promptly!

FWIW, I did get the following error from ?iucn_summary:
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/taxize/help/taxize.rdb' is corrupt

**Comment by sckott** [comment]
@mcsiple glad it works now

that error  I think is often fixed by a restart of the R session, did you try that?

**Comment by mcsiple** [comment]
Yep! It's fixed now. Thank you!

**Comment by sckott** [comment]
great!

**Comment by mcsiple** [comment]
Hi Scott-- I noticed just one thing recently. I'm looping through several species and storing their IUCN status in a separate column. Sometimes (and not consistently on the same species) I get the error 

 ```
   Error in UseMethod("iucn_status") : 
      no applicable method for 'iucn_status' applied to an object of class "try-error"

```

When it happens, I have just been re-starting the loop from the index where it got stuck, and all goes well. Within the loop, I have:

```
      for(i in 1:length(ds.list$childtaxa_name)){
        # Get IUCN status for each species:
        s <- try(iucn_summary(ds.list$childtaxa_name[i],key=IUCN_key))
        newdf[i,'IUCNstatus'] <- iucn_status(s)
       }
```

where `newdf` is a dataframe containing all the species of interest, and `ds.list$childtaxa_name` is the 
list of species of interest. It only happens once in a while, and if I run just that species, there are never any problems. I'm wondering if it has to do with looking up the API key each time. 

I got the data that I needed, so this isn't urgent, just something I've noticed while using `iucn_summary()`.

**Comment by sckott** [comment]
@mcsiple how many requests did you do?, i.e. what is the length of `ds.lsit$childtaxa_name`

Just worked fine for me for about 20 species, but its possible you hit rate limiting if it was a lot. see this note in the docs (`?rredlist-package`)

> From the IUCN folks: Too many frequent calls, or too many calls per day might get your access blocked temporarily. If you're a heavy API user, the Red List Unit asked that you contact them, as there might be better options. They suggest a 2-second delay between your calls if you plan to make a lot of calls.

**Comment by mcsiple** [comment]
Oh, perhaps that is the issue. I am actually looking up the statuses of all the species within each of ~80 genera, so I must be getting blocked periodically, then it works once my two seconds are up.  It is clunky to periodically start the loop where I left off, but it's getting the job done.

**Comment by sckott** [comment]
It takes longer of course, but you can use e.g., `Sys.sleep(2)` to sleep for 2 seconds between each request. put that at top or bottom of for loop

**Comment by mcsiple** [comment]
Woohoo! You're a genius.

**Comment by sckott** [comment]
let me know if you have any other questions.
