### ISSUE TITLE
`rows` param usage in classification() with name not matched throws error 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#548]
from https://github.com/ropensci/taxize/issues/547

**Comment by sckott** [comment]
@ahhurlbert I can't replicate the problem you reported 

```r
classification("asdf", db = "itis", rows = 1)
#> Error in x[rows, ] : incorrect number of dimensions
```

with the current version on master. Install like `devtools::install_github("ropensci/taxize")` - and let me know of any examples of this error

**Comment by ahhurlbert** [comment]
Nope, I can't duplicate it either after installing from Github, so no bug to fix I guess!

**Comment by sckott** [comment]
okay, thanks for testing!
