### ISSUE TITLE
worms #newdatasource

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/taxize#553]
So, in working with `classification()`, frankly, itis and ncbi are a mess with respect to algae - missing whole species and having non-standard and conflicting classification schemes. More standard is the World Register of Marine Species - http://www.marinespecies.org/index.php - any chance that could be added as a db?

**Comment by jebyrnes** [comment]
Also I'm an idiot and realized that I asked soemthing similar on this package ages ago - but, well, consider this a bump? HA - sorry!

**Comment by sckott** [comment]
Sorry about itis and ncbi not cutting the mustard!  

worms is in `taxizesoap` pkg - see https://github.com/ropensci/taxizesoap#worms for examples - let me know if you have trouble installing

**Comment by sckott** [comment]
we can't add it in `taxize` proper because they use a web service technology that is hard to support across operating systems and R versions, so worms, pesi and mycobank are in a sep. package

**Comment by jebyrnes** [comment]
Amazing as always. Didn't totally realize there was another package. Onwards! And hopefully I'll have a good example for you in a bit!

**Comment by sckott** [comment]
sounds bueno
