### ISSUE TITLE
tax_name() fails with 'Galagoides demidovii'

### ISSUE THREAD

**Issue by ljvillanueva** [ropensci/taxize#560]
Running 
```
tax_name(query = 'Galagoides demidovii', get = "family", db = "itis")
```

Results in 

```
Retrieving data for taxon 'Galagoides demidovii'

Error in tt$rank : $ operator is invalid for atomic vectors
```

Tried looking into how tax_name() works and it seems that the problem is when classification() returns not an NA, but this:

```
> classification(get_tsn('Galagoides demidovii', verbose=TRUE), verbose=verbose)

Retrieving data for taxon 'Galagoides demidovii'

$`944094`
[1] NA

attr(,"class")
[1] "classification"
attr(,"db")
[1] "itis"
```

get_tsn() doesn't return an NA:

```
> tsn <- get_tsn( 'Galagoides demidovii', searchtype = "scientific", verbose = TRUE)

Retrieving data for taxon 'Galagoides demidovii'

> tsn
[1] "944094"
attr(,"match")
[1] "found"
attr(,"multiple_matches")
[1] TRUE
attr(,"pattern_match")
[1] TRUE
attr(,"uri")
[1] "http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=944094"
attr(,"class")
[1] "tsn"
> is.na(tsn)
[1] FALSE
```

So the check [here](https://github.com/ropensci/taxize/blob/master/R/tax_name.R#L86) doesn't see it as an NA. Seems to be an issue with what ITIS returns for this species.

**Comment by sckott** [comment]
thanks, @ljvillanueva  what version of taxize and R do you have

**Comment by sckott** [comment]
looks like that taxon is invalid http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=944094 

and the api call that `classification(get_tsn('Galagoides demidovii'))` makes is http://www.itis.gov/ITISWebService/services/ITISWebService/services/ITISService/getFullHierarchyFromTSN?tsn=944094

which returns no taxonomic classification data

so we should handle that better, and not fail when no classification data returned

**Comment by ljvillanueva** [comment]
I'm using taxize 0.7.9 in R 3.2.3.

**Comment by sckott** [comment]
@ljvillanueva reinstall and try again, should be fixed now

**Comment by ljvillanueva** [comment]
Yep, seems to be fixed now. Thanks!

**Comment by sckott** [comment]
great
