### ISSUE TITLE
Get all names from Index Fungorum?

### ISSUE THREAD

**Issue by wcornwell** [ropensci/taxize#562]
Thanks again for this awesome tool!  We're about to have a working group on fungal traits following [this meeting](http://ipmb.berkeley.edu/events/msa-2016), so will probably have some myco-querries coming for you.

Anyway first one.  I was trying to get a list of names that are in Index Fungorum to make a plot of number of binomials in each family and order.  My first attempt was:

```{r}
list.out <- lapply(1:10, taxize::fg_name_by_key)
```
But I don't know how many keys there are and the api seems to be returning different numbers of columns with each key.  

Am I on the right track? Any clever tips?

**Comment by sckott** [comment]
Thanks for your question. 

I'll have a look...

**Comment by sckott** [comment]
there's not a great solution here, but here's something

```r
out <- list()
for (i in seq_along(LETTERS)) {
  out[[i]] <- fg_name_search(q = LETTERS[i], anywhere = FALSE, limit = 10)
}
tibble::as_data_frame(dplyr::bind_rows(out))
#> # A tibble: 260 x 44
#>           name_of_fungus         authors infraspecific_rank
#>                    <chr>           <chr>              <chr>
#> 1              Aabaarnia       Diederich               gen.
#> 2  Aabaarnia siphulicola       Diederich                sp.
#> 3            Aaosphaeria         Aptroot               gen.
#> 4      Aaosphaeria arxii    (Aa) Aptroot                sp.
#> 5                Abacina          Norman               gen.
#> 6       Abacina alboatra (Hoffm.) Norman                sp.
#> 7      Abacina alpestris          Norman                sp.
#> 8       Abacina amphibia    (Fr.) Norman                sp.
#> 9       Abacina atroalba     (L.) Norman                sp.
#> 10    Abacina atrovirens     (L.) Norman                sp.
#> # ... with 250 more rows, and 41 more variables: typification_details <chr>, volume <chr>,
#> #   page <chr>, year_of_publication <chr>, literature_link <chr>, sts_flag <chr>,
#> #   record_number <chr>, basionym_record_number <chr>, protonym_record_number <chr>,
#> #   name_of_fungus_fundic_record_number <chr>, current_name <chr>,
#> #   current_name_record_number <chr>, current_name_fundic_record_number <chr>,
#> #   updatedby <chr>, updateddate <chr>, addeddate <chr>, uuid <chr>, specific_epithet <chr>,
#> #   part <chr>, bsm_link <chr>, ixf_record_number <chr>, addedby <chr>,
#> #   published_list_reference <chr>, cmicc_flag <chr>, gsd_flag <chr>,
#> #   taxonomic_referee <chr>, sqltimestamp <chr>, year_on_publication <chr>,
#> #   editorial_comment <chr>, nomenclatural_comment <chr>, correction <chr>,
#> #   publishing_authors <chr>, host <chr>, location <chr>, internet_link <chr>,
#> #   orthography_comment <chr>, synonymy <chr>, epithet_flag <chr>, sanctioning_author <chr>,
#> #   infraspecific_epithet <chr>, anamorph_teleomorph <chr>
```

that's with a low `limit` value just for demo purposes. You can set `limit` to max of 6000 I believe. but there's no way to say "i want to start at this name, then move from there", so you can probably get most, but maybe not all names

**Comment by wcornwell** [comment]
Nice. `fg_name_search` seems a better way to go.

As work around for the limit issue, I guess there could be a check if the limit got hit and then query on the first two letters? This sort of stuff is never elegant.

**Comment by sckott** [comment]
maybe e.g., this 

```r
out <- list()
starts <- paste(vapply(letters, function(x) paste0(x, letters), character(26)))
for (i in seq_along(starts)) {
  out[[i]] <- fg_name_search(q = starts[i], anywhere = FALSE, limit = 6000)
}
(df <- tibble::as_data_frame(dplyr::bind_rows(out)))
```

which makes all vector `aa`, `ab`, `ac`, etc. or maybe have to go to three letter combos as e.g., I ran just the first 10 with 6000 limit and `ag` had 6000, so that slot has more results

**Comment by wcornwell** [comment]
Makes sense.  Probably Agaricus.  I fiddle with this.  T

**Comment by wcornwell** [comment]
Here is where I've got to so far.  

```{r}
add.another.letter<-function(vec.in){
  vec.out <- paste(vapply(vec.in, function(x) paste0(x, letters), character(26)))
  return(vec.out)
}

get_all_fg_names<-function(){
  make3lettercode<-function(x) add.another.letter(add.another.letter(x))
  code3<-make3lettercode(letters)
  out<-list()
  #for (i in seq_along(code3)) {
  for (i in 1:100) {
    out[[i]] <- taxize::fg_name_search(q = code3[i], anywhere = FALSE, limit = 6000)
  }
  df <- tibble::as_data_frame(dplyr::bind_rows(out))
  return(df)
}

start.time <- Sys.time()
fungal_names<-get_all_fg_names()
end.time <- Sys.time()
time.taken <- end.time - start.time
```

seems to be working so far, but haven't tested it full yet

**Comment by wcornwell** [comment]
>6000 names within agaricus.  still not there yet.  bummer.

**Comment by sckott** [comment]
might be worth asking them if they can provide a dump, though that usually ends up with a `No`

**Comment by wcornwell** [comment]
As far as I can tell this hacky solution is working and there aren't any other problem genera:

```{r}
add.another.letter<-function(vec.in){
  vec.out <- paste(vapply(vec.in, function(x) paste0(x, letters), character(26)))
  return(vec.out)
}

get_all_fg_names<-function(){
  code3<- add.another.letter(add.another.letter(letters))
  out<-list()
  for (i in seq_along(code3)) {
    out[[i]] <- taxize::fg_name_search(q = code3[i], anywhere = FALSE, limit = 6000)
  }
  for (i in seq_along(letters)) {
    out[[length(code3)+i]] <- taxize::fg_name_search(q = paste0("Agaricus ",letters)[i], anywhere = FALSE, limit = 6000)
  }
  df.with.duplicates <- tibble::as_data_frame(dplyr::bind_rows(out))
  df.unique.names <- dplyr::distinct(df,name_of_fungus, .keep_all = TRUE)
  return(df.unique.names)
}

start.time <- Sys.time()
fungal_names<-get_all_fg_names()
readr::write_csv(fungal_names,"fungal_names.csv")
end.time <- Sys.time()
time.taken <- end.time - start.time
```

Takes about 8 hours.  Closing the issue, but hopefully people can find this if this issue ever comes up again.  Thanks for the help @sckott

**Comment by sckott** [comment]
@wcornwell glad something worked finally. and thanks for sharing the solution

**Comment by DoumCHAMBERS** [comment]
Is that a script that download all the scientific names (taxonIDs, taxonomic hierachy, parentID, Rank, etc?) (Accepted and synonyms). 215 347 names accordings to GBIF.

**Comment by sckott** [comment]
@DoumCHAMBERS is that a question for @wcornwell   ?

**Comment by DoumCHAMBERS** [comment]
Both of you. @sckott @wcornwell

**Comment by DoumCHAMBERS** [comment]
I'm looking to a script that I can download all the scientif names including synonyms, taxonIDs, taxonomic level, etc. of the Index Fungorum website.
I'm building a list of species (checklist) in my region of interest with the help of a local Mycologist.

**Comment by wcornwell** [comment]
Hi @DoumCHAMBERS,

>Is that a script that download all the scientific names (taxonIDs, taxonomic hierachy, parentID, Rank, etc?) (Accepted and synonyms). 215 347 names accordings to GBIF.

long time ago, but I *think* it's only accepted names according to Index Fungorum.  IF API might have changed in the last two years, so no guarantee it's still working..

**Comment by DoumCHAMBERS** [comment]
Thanks @wcornwell ! I ran the script yesterday and worked perfectly. I haven't touch R since my master degree in 2010... wooo. Happy that everthing worked well.... Thank you very much @wcornwell @sckott for your generousity. Greatly appreciated.
