### ISSUE TITLE
Strange xml errors popping up intermittently.

### ISSUE THREAD

**Issue by SimonGoring** [ropensci/taxize#566]
``` r
> sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.7.9  neotoma_1.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      cluster_2.0.4    xml2_1.0.0       magrittr_1.5     MASS_7.3-45     
 [6] rotl_3.0.1       lattice_0.20-34  ape_3.5          R6_2.1.3         foreach_1.4.3   
[11] rentrez_1.0.2    stringr_1.1.0    httr_1.2.1       plyr_1.8.4       tools_3.3.1     
[16] rredlist_0.1.0   parallel_3.3.1   bold_0.3.5       grid_3.3.1       data.table_1.9.6
[21] nlme_3.1-128     mgcv_1.8-15      vegan_2.4-1      iterators_1.0.8  assertthat_0.1  
[26] analogue_0.17-0  permute_0.9-4    Matrix_1.2-7.1   reshape2_1.4.1   codetools_0.2-14
[31] curl_2.0         princurve_1.1-12 stringi_1.1.1    rncl_0.6.0       XML_3.98-1.4    
[36] jsonlite_1.1     brglm_0.5-9      reshape_0.8.5    chron_2.3-47
```

I used the call:

``` r
classification("Eolimna", db = "itis", rows = 1)
```

and go this error:

```
Error in names(tmp) <- tolower(names(tmp)) : 
  attempt to set an attribute on NULL
In addition: Warning messages:
1: In xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
2: In xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
3: In xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
4: In xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
5: In xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) :
  Undefined namespace prefix [1219]
```

[_Eolimna_ is in the ITIS](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=970026), and the call does return, sometimes, but other times it seems to hang for a really long time, so I wonder if this isn't actually the side-effect of a time-out problem.

Raising it here in case other people get it, or if there's some workaround.

**Comment by sckott** [comment]
Thanks Simon, having a look

**Comment by SimonGoring** [comment]
I re-ran chunks of my code today and I only got one (presumably server side) related error:

```r
> classification("Arecaceae incertae sedis", db="itis", rows=1)

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Server returned nothing (no headers, no data)
```

The `curl` error turned up several times yesterday.  This makes me think that in general the issues had something to do with the ITIS server, rather than the package.  Not sure how reproducible it all is :)

**Comment by sckott** [comment]
@SimonGoring I think it was a temporary problem with ITIS services. Running those two egs now with `replicate()` and not getting any errors. Are you still getting errors?

**Comment by hmorzaria** [comment]
I got similar errors today when running.
```
replicate(3, synonyms("Pinus contorta", db="itis"))

> Error in names(tmp) <- tolower(names(tmp)) : 
  attempt to set an attribute on NULL
```
`
> itis_ping()
[1] TRUE
`
`synonyms()` works with Tropicos

The error was system independent, tried it in two different computers (Linux & Windows)

**Comment by hmorzaria** [comment]
The error occurred over ~30 minutes, works now

**Comment by sckott** [comment]
hmm, must have been a server problem on their end. works for me now as well

**Comment by hmorzaria** [comment]
Yes, just the resulting error message is confusing

**Comment by sckott** [comment]
right, that's probably a result of not stopping code execution when there's a problem with the data returned from server, as we don't want to stop in case someone is using the function across many taxa, but hard to account for all possible error scenarios
