### ISSUE TITLE
ncbi classification no longer working

### ISSUE THREAD

**Issue by nate-d-olson** [ropensci/taxize#570]
NCBI search functions are broken. I believe that the issue is related to NCBI switching from http to https but changing the URLs in the source code did not fix the issue.

**Comment by sckott** [comment]
can you share your sessioninfo and an example call and the error you get

**Comment by sckott** [comment]
ncbi urls now https, see #571

**Comment by sckott** [comment]
all sorted, and `ncbi_*` fxns moved to traits
