### ISSUE TITLE
worms is now restful

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#574]
http://www.marinespecies.org/rest/#/

coming soon ...

**Comment by sckott** [comment]
new pkg is at https://github.com/ropensci/worrms - will integrate here soon

ping: @jebyrnes @Alectoria @willgearty

**Comment by willgearty** [comment]
It's a Christmas miracle! Thanks, Scott!

**Comment by sckott** [comment]
working on branch `with-worrms`

**Comment by sckott** [comment]
chagnes in a283a97a74fe8078b297be678969e90bc778aec5

**Comment by sckott** [comment]
@jebyrnes @Alectoria @willgearty If you have a second to try this out, reinstall like `devtools::install_github("ropensci/taxize@worrms")` - see new functions:

`get_wormsid`, `get_wormsid_`, `as.wormsid`, and additions to `synonyms`, `classification`, `children`, `comm2sci`, `sci2comm`

let me know about any errors - features

**Comment by sckott** [comment]
sent to cran
