### ISSUE TITLE
Function get_eolid_help() doesn't pass eol API key as argument to eol_pages()

### ISSUE THREAD

**Issue by dschlaep** [ropensci/taxize#576]
The function get_eolid_help() has 'key' as one of its arguments. It passes 'key' to the call to eol_search() (line 299), but not to eol_pages() (line 309). Thus the warning 
> Using default key: Please get your own API key at http://eol.org/users/register

is issued even if a working personal API key is provided.

This refers to the latest commit e023483ea92e39f420ea3ee601216f38d3e18c1e on the master branch (Dec 16, 2016).

Suggestion: Replace current line 309
`y <- tryCatch(eol_pages(x), error = function(e) e)`
with 
`y <- tryCatch(eol_pages(x, key = key), error = function(e) e)`

Thank you!

**Comment by sckott** [comment]
@dschlaep thanks for the report!

fixing now

**Comment by sckott** [comment]
@dschlaep okay, reinstall and try again, let me know if it works

**Comment by dschlaep** [comment]
@sckott thanks for the fix! v0.8.0.9610 works like a charm
