### ISSUE TITLE
NBN data source likely will need fixes

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#582]
around March sometime heard the backend will change - see if anything needs to be fixed.

**Comment by robbriers** [comment]
Shut down of old NBN site on 31st March means that all NBN searches currently throw a 404 error.

**Comment by sckott** [comment]
woopsy, opened a different issue, so this is sorted now via https://github.com/ropensci/taxize/issues/597 - will go to CRAN soonish, maybe end of week
