### ISSUE TITLE
Reverse function for genbank2uid ?

### ISSUE THREAD

**Issue by antagomir** [ropensci/taxize#584]
The genbank2uid provides mapping from genbank to uid. Does the taxize package provide tools to make a reverse conversion, from uid to genbank IDs ?

**Comment by sckott** [comment]
thanks @antagomir - not at the moment, but i'll have a look - it will be a 1 UID to potentially A LOT of genbank ids, so not sure if it will be a good fit here

**Comment by antagomir** [comment]
Ok good to know, at least I know now that I was not missing something that is already available.

**Comment by sckott** [comment]
does this do what you want

```r
uidtogen <- function(id, ...) {
  url <- paste0("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=taxonomy&db=nucleotide&id=", id)
  res <- GET(url, ...)
  stop_for_status(res)
  result <- xml_text(xml_find_all(read_xml(con_utf8(res)), "//Link//Id"))
  Sys.sleep(0.34)
  return(result)
}

uid2genbank <- function(id, ...){
  stats::setNames(lapply(id, uidtogen, ...), id)
}
```

for example

```r
 uid2genbank(id = c(282199, 9696))
```

**Comment by antagomir** [comment]
Thanks ! Seems so but I could not run this yet - where does the con_utf8 come from - I could not locate any package with this.

**Comment by sckott** [comment]
oh sorry, edited above, try again.

**Comment by antagomir** [comment]
All output IDs in this new function seem to be numerics converted into a string. I was expecting the output "CP015409" following uid2genbank(239935), since the (reverse) genbank2uid("CP015409")[[1]] returns "239935". However, a rapid check indicates that the IDs returned by genbank2uid refer to the correct organism (Akkermansia) in Genbank. For some reason the original "CP015409" is just missing from that list although the mapping works to the other direction.

**Comment by sckott** [comment]
those are GI ids, e.g., https://www.ncbi.nlm.nih.gov/nuccore/CP015409.1

can see if i can get acces. numbers instead of GI's

**Comment by sckott** [comment]
i don't see any way to get acc ids instead of GI ids, let me know if you do

**Comment by antagomir** [comment]
Ok there is a ncbi [flat file](ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz) for ID conversions that could be downloaded but I have not found services that could be queried for this.

**Comment by sckott** [comment]
if you don't mind I'll reopen for a while as we may find something

**Comment by sckott** [comment]
closing, no leads on this yet
