### ISSUE TITLE
Regional assessments or stocks/subpop lookup available thru taxize?

### ISSUE THREAD

**Issue by mcsiple** [ropensci/taxize#589]
Hi Scott-- Can taxize report regional assessments for a species, if available? It would be excellent to be able to look at "downstream" statuses below the species level for different subpopulations. This isn't urgent, just thought it would be cool! Thank you for all the great work on this package.

**Comment by sckott** [comment]
hi @mcsiple - thanks for the question

> Can taxize report regional assessments for a species, if available? 

Can you clarify what you mean by regional assessment? 

> It would be excellent to be able to look at "downstream" statuses below the species level for different subpopulations.

What do you mean by _statuses_? And by _subpopulation_ do you literally mean a population of a species (e.g., a population of _Abies magnifica_ in XYZ park) OR a subspecific rank like _subspecies_ or _variety_?

**Comment by mcsiple** [comment]
Sure- IUCN sometimes does regional assessments for species that also have a global assessment (their description is [here](http://cmsdocs.s3.amazonaws.com/keydocuments/Reg_Guidelines_en_web%2Bcover%2Bbackcover.pdf)). If you are searching for a species on the IUCN site, there is a search option for including regional assessments or "stocks/subpopulations":
<img width="544" alt="screen shot 2017-02-26 at 2 27 17 pm" src="https://cloud.githubusercontent.com/assets/2936426/23344382/2b88f4c4-fc30-11e6-8857-1ae244b147aa.png">
...which I don't think are plentiful but they would be useful to include in the future. 
Re: statuses -- sorry, I meant IUCN status-- my brain was buried in my own project.

**Comment by sckott** [comment]
@mcsiple Do you know about the https://github.com/ropensci/rredlist package?  It's specifically for IUCN Red List data. It sounds like that would be a better fit?  Let me know if i'm off on my guess there. And if `rredlist` doesn't have what you need. looks like `rredlist::rl_history` has historical assessments

One way to do the downstream use case is to use `downstream()` in this package to get the names, then go to rredlist to get your assessment/status data if available for those taxa.

**Comment by mcsiple** [comment]
Hi @sckott -- thanks for the recommendation-- I will check that out (in the meantime, for whole species, taxize has done the trick!) I've been using downstream() to get all the statuses for species within a genus. Thank you!

**Comment by sckott** [comment]
@mcsiple glad it works for you. do open any issues you have with `rredlist` over in that repo
