### ISSUE TITLE
Error reported for `ncbi_get_taxon_summary`

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#591]
I was emailed the following. I am pasting it here so there is a record of the conversation.

> Good afternoon Zachary, 
I want to download taxonomic information for several thousand Genbank records.  I used Taxize to convert accession numbers to uids (using genbank2uid), but when I try to use ncbi_get_taxon_summary to get the associated taxonomic information for these uids (the data are stored as a data frame, for example, but this also fails with a list), I get the error  
"Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing
4: Opening and ending tag mismatch: p line 6 and a
5: Opening and ending tag mismatch: body line 4 and p
6: Opening and ending tag mismatch: html line 2 and body
7: Extra content at the end of the document"
> If I try the example listed in the R documentation (i.e.  ncbi_get_taxon_summary(c(1430660, 4751))), I still get
"Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing"
>Do you have any idea why the ncbi_get_taxon_summary​ function doesn't retrieve even a couple of records?
>Do you know of a better way to get the associated taxonomic information for thousands of uids?  To me it seems that Taxize is not really suited to this - but I was trying to avoid using NCBI's EUTILS directly.
>Many thanks in advance for any insights and help that you might be able to provide.
>Best wishes, 
>Phill

I could not replicate the error, so I am waiting to hear back from Phill for his `sessionInfo()`. I will update this issue when we have reached a conclusion.

```
> install.packages("taxize")
Installing package into ‘/home/fosterz/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/taxize_0.8.4.tar.gz'
Content type 'application/x-gzip' length 443292 bytes (432 KB)
==================================================
downloaded 432 KB

* installing *source* package ‘taxize’ ...
** package ‘taxize’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (taxize)

The downloaded source packages are in
	‘/tmp/RtmpsL3OI8/downloaded_packages’
> library(taxize)
> ncbi_get_taxon_summary(c(1430660, 4751))
      uid              name    rank
1 1430660 Satyrium favonius species
2    4751             Fungi kingdom
> 
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.8.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       codetools_0.2-15  lattice_0.20-34   ape_4.0           reshape_0.8.6     foreach_1.4.3     dplyr_0.5.0       assertthat_0.1    plyr_1.8.4       
[10] grid_3.3.1        R6_2.2.0          jsonlite_1.2      nlme_3.1-128      DBI_0.5-1         magrittr_1.5      taxa_0.0.2.9052   httr_1.2.1        stringi_1.1.2    
[19] curl_2.3          reshape2_1.4.2    data.table_1.10.0 xml2_1.1.1        iterators_1.0.8   tools_3.3.1       stringr_1.1.0     bold_0.4.0        parallel_3.3.1   
[28] tibble_1.2   
```

**Comment by zachary-foster** [comment]
It was an R version issue. It worked right once he updated to R 3.3.1.

**Comment by sckott** [comment]
thanks
