### ISSUE TITLE
Classification lineages and offline queries

### ISSUE THREAD

**Issue by davidvilanova** [ropensci/taxize#595]
Hello,
Is there a quick way to get the 6 lineages (Phylum, Class, Family, Order,Genus, Species) for a given list of ids ?

classification(list_of_ids, db="ncbi") will return  a dataframe with all found.

Also can the files be downloaded locally to grun offline queries ?

**Comment by sckott** [comment]
Not sure what you mean exactly. I assume `classification(list_of_ids, db="ncbi")` does not give you what you want, but what are you looking for?

> Also can the files be downloaded locally to grun offline queries ?

What exactly do you mean?  What files?

**Comment by davidvilanova** [comment]
Finally got everything.

**Comment by sckott** [comment]
okay, let me know if any other questions
