### ISSUE TITLE
Display more/all options in interactive session using classification()

### ISSUE THREAD

**Issue by ahhurlbert** [ropensci/taxize#596]
I'm wondering whether there is a simple way to display more rows of output during the interactive session when using `classification()`. That is, if I try `classification('Limnophila', db = 'itis')`, I get

```
Retrieving data for taxon 'Limnophila'

Source: local data frame [199 x 4]

      tsn                             target          commonNames    nameUsage
    (chr)                              (chr)                (chr)        (chr)
1  120037                   Austrolimnophila                   NA        valid
2  120038             Austrolimnophila badia                   NA        valid
3  120040         Austrolimnophila byersiana                   NA        valid
4  120041           Austrolimnophila harperi                   NA        valid
5  120043          Austrolimnophila subunica                   NA        valid
6  120045         Austrolimnophila toxoneura                   NA        valid
7  120047             Austrolimnophila unica                   NA        valid
8   30657  Calystegia sepium ssp. limnophila hedge false bindweed     accepted
9  527115 Carex lenticularis var. limnophila      lakeshore sedge     accepted
10  39673                   Carex limnophila                   NA not accepted
..    ...                                ...                  ...          ...

More than one TSN found for taxon 'Limnophila'!

            Enter rownumber of taxon (other inputs will return 'NA'):

1: 
```
Seems to be returning all potential matches in alphabetical order which is fair enough, but in this particular case I'm looking for a genus name which is clearly farther down the list. Problem is, I don't know exactly which row number to enter since I can't see all the options. Ideas?

```
R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.6.0   stringr_1.2.0 dplyr_0.4.3   taxize_0.8.4 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       xml2_1.1.1        magrittr_1.5      ape_4.1           lattice_0.20-33   R6_2.2.0          foreach_1.4.3    
 [8] httr_1.2.1        plyr_1.8.4        tools_3.3.1       parallel_3.3.1    bold_0.4.0        grid_3.3.1        data.table_1.10.4
[15] nlme_3.1-128      DBI_0.5-1         iterators_1.0.8   lazyeval_0.2.0    assertthat_0.1    tibble_1.2        reshape2_1.4.2   
[22] codetools_0.2-14  curl_2.3          stringi_1.1.2     ritis_0.5.4       jsonlite_1.3      reshape_0.8.5    
> 
```

**Comment by ahhurlbert** [comment]
I should add that I'm running this programmatically for many names, which won't always be at a particular known level (e.g. genus), or at least ideally I'd like to not have to specify that but in practice I probably could.

**Comment by sckott** [comment]
thanks @ahhurlbert 

Looks like in ritis we're using tibbles (compact data.frame's) - I'll change that to a regular data.frame before printing.

**Comment by sckott** [comment]
@ahhurlbert reinstall and try again

**Comment by ahhurlbert** [comment]
Yes, there's an interesting tradeoff here given that for some names that I have been entering there are 1,000+ options, so data.frame output will be ugly in some cases, but I think that's the only way to be able to scan all options.

A more complicated output feature would be to only display 20-50 results at a time, but then hit space bar to get the next 20-50?

**Comment by ahhurlbert** [comment]
Better. From the previous tibble version I know there are 1,101 options for 'Iris', but they can't all get displayed on screen.

Here's what happens at the bottom for an example with too many options,  `classification('Iris', db='itis')`:
```
247   515243                       Iris rhodantha                                                                 NA not accepted
248   515244                    Iris rhodochrysea                                                                 NA not accepted
249   515245                       Iris rivularis                                                                 NA not accepted
250   515246                       Iris rosiflora                                                                 NA not accepted
 [ reached getOption("max.print") -- omitted 851 rows ]

More than one TSN found for taxon 'iris'!

            Enter rownumber of taxon (other inputs will return 'NA'):

1: 
```

**Comment by sckott** [comment]
not heard of a way to scroll through a data.frame, but maybe will find something. 

thanks for the example. yeah, not sure what to do about that - Depending on the data source it's helpful to narrow your query so you get less results. e.g., with ITIS if you use `get_tsn` then pass to `classification` you could constrain to `accepted = TRUE`. Another way is to use the underscore methods, e.g., `get_tsn_` which gives you all the names, then you can process them yourself

any other ideas?

**Comment by ahhurlbert** [comment]
The ITIS website has options for their manual searches to specify "contains" versus "exactly for", and you can specify matching Scientific Name and/or Common Name. Can you make use of these features through taxize? 

In the Iris example, it was matching to both sci and common names with "iris" string embedded, it would greatly reduce the options by being able to restrict in these ways.

**Comment by sckott** [comment]
Hmm, we use their REST API and i'm pretty sure their website doesn't use their API, so we can't necessarily do what they do. We use one of the routes for `get_tsn` that doesn't have those options for contains vs. exactly - I'm pretty sure they query their SQL database directly - ANYWAY, will try

**Comment by sckott** [comment]
sorry about delay on this, getting to it soon

**Comment by ahhurlbert** [comment]
I'm fine now, and it turns out 'Iris' is pretty unique, so I don't expect this to be a very common problem for folks...

**Comment by sckott** [comment]
okay, still looking into it though :)

**Comment by sckott** [comment]
Although I'd like to provide a way to more interactively scroll through options, i think for now our advice to add to docs will be to refine your search if you are getting > results than will show at once 

caveat of course that some data sources don't allow you to refine your queries - not sure what to do in those cases

thx for raising this @ahhurlbert
