### ISSUE TITLE
Kew's plants of the world

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#598]
http://powo.science.kew.org/

via dev tools, reveals that there's an API behind web portal: eg., 

http://powo.science.kew.org/api/1/suggest?query=Quercus
http://powo.science.kew.org/api/1/suggest?query=sunflower 
http://powo.science.kew.org/api/1/search?sort=name_desc&f=accepted_names%2Chas_images%2Cgenus_f&q=Asteraceae
http://powo.science.kew.org/api/1/search?sort=name_desc&f=accepted_names%2Chas_images&q=Asteraceae
http://powo.science.kew.org/api/1/search?sort=name_desc&f=accepted_names&q=Asteraceae 

a bit hesitant to put in the pkg, since they don't document the API, and perhaps meaning it will change perhaps drastically

**Comment by sckott** [comment]
closing for now, no docs in sight

**Comment by jiacona** [comment]
Hi @sckott, I'm the lead developer for POWO and while we haven't officially published our API for public consumption yet, version 2 of the API should be stable. I think we will mostly be recommending people use our published libraries to interact with it (see https://github.com/RBGKew/pykew) so you can refer to pykew as the canonical way to interact with the API. It doesn't yet implement all the features of the API, but probably covers everything you would need for taxize.

I'd be really happy to get POWO integrated into taxize as we get people asking for it all the time. If there is anything I can do to help, or if you have any questions about powo and the api, please let me know.

**Comment by sckott** [comment]
thanks for the ping @jiacona 

I'll have a play soon on a branch and will let you know if I have any questions. Some immediate questions are:

- is there rate limiting?
- is there any way to know about API changes?

**Comment by jiacona** [comment]
Great, thanks for the reply.

We don't have much traffic at the moment so there is currently no rate limiting. However, it would be great if you could be conscientious with it. I have built rate limiting pykew which you can emulate. Also, if you need to use paging, please use the cursor based method -- also used in pykew.

Unfortunately I don't have a great answer for knowing about future API changes. I'll do my best to let you know if/when anything changes. I also am hoping to get the time to document the api properly and publish any changes, but have not done so yet.

**Comment by jiacona** [comment]
It is: https://github.com/RBGKew/powop

**Comment by sckott** [comment]
started work on branch `kew-api` https://github.com/ropensci/taxize/tree/kew-api - fxns `pow_search()`, `pow_lookup()`, `get_pow()`, and as an option in `classification()`

**Comment by sckott** [comment]
changes in b4d5800 and 4370d43

**Comment by sckott** [comment]
install latest

```r
remotes::install_github("ropensci/taxize")
library(taxize)
```

see functions `?get_pow`, `classification.pow`, `pow_search`, and `pow_lookup`

**Comment by jiacona** [comment]
Just to let you know, we have been getting some abuse of the API that meant I needed to implement rate limiting. Hopefully this won't impact legitimate use of the API, but if you want to handle it you can watch for 429 responses and wait a second before retrying.

**Comment by sckott** [comment]
thanks @jiacona what are the rate limits? Are there per sec, per min, per hour, per 24 hour rates?

**Comment by jiacona** [comment]
At the moment it is limited to 5 requests per second. We may have to revise in the future, but this should catch the current offending traffic and hopefully not impact anyone else.
________________________________

**Comment by sckott** [comment]
Okay, thanks
