### ISSUE TITLE
taxize + local copy of ncbi taxonomy for millions of queries

### ISSUE THREAD

**Issue by rossmounce** [ropensci/taxize#600]
I'd like to "re-identify" ~36.6 million NCBI land plant taxids using `ncbi_get_taxon_summary()`

You briefly mentioned that you might develop the ability to do queries of local copies of certain databases including NCBI in #271 ? 

Is that implemented? 
I think the package `taxonlookup` does this for ThePlantList and it is very helpful.

```

```

**Comment by rossmounce** [comment]
ah, I see this idea has morphed into it's own package: https://github.com/ropenscilabs/taxizedb

**Comment by sckott** [comment]
right, any reason to leave this open?

**Comment by rossmounce** [comment]
nope. sorry! closing.
