### ISSUE TITLE
Bad Gateway errors in tnrs and iplant_resolve

### ISSUE THREAD

**Issue by snsheth** [ropensci/taxize#601]
My sense is that there have been previous issues with accessing tnrs, but I am not sure if there is any way to address Bad Gateway problems or if this is one of the reasons tnrs may become defunct in the future. I have been receiving somewhat unpredictable errors when using the tnrs function. Sometimes I run a query on multiple species names at once and I get a Bad Gateway error, but when I re-run on a single species it works. Other times I cannot even perform a successful query on a single species name. See code below. Thanks in advance!

R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.8.4   gdata_2.17.0   reshape2_1.4.2 dplyr_0.5.0    plyr_1.8.4    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       xml2_1.1.1        magrittr_1.5      ape_4.1          
 [5] lattice_0.20-34   R6_2.2.0          foreach_1.4.3     stringr_1.2.0    
 [9] httr_1.2.1        tools_3.3.3       parallel_3.3.3    bold_0.4.0       
[13] grid_3.3.3        data.table_1.10.0 nlme_3.1-131      DBI_0.5-1        
[17] iterators_1.0.8   gtools_3.5.0      assertthat_0.1    tibble_1.2       
[21] codetools_0.2-15  curl_2.3          mime_0.5          stringi_1.1.2    
[25] jsonlite_1.2      reshape_0.8.6    

```
iplant_resolve(query="Mimulus cardinalis var. verbenaceus")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
In addition: Warning message:
In iplant_resolve(query = "Mimulus cardinalis var. verbenaceus") :
  Bad Gateway (HTTP 502).

plant_list_species=tnrs(query = "Mimulus cardinalis var. verbenaceus", source = "iPlant_TNRS")
Calling http://taxosaurus.org/retrieve/4c35da3516e9ee5b3fc9ced46ba762b5
Error: HTTP status 502 - Bad Gateway

```

**Comment by sckott** [comment]
thanks for your message @snsheth 

yes, this happens quite a lot. they seem to be up now, but the problems will likely persist. 

the issue with TNRS is that the maintainer doesn't have a lot of time to give to it, and ive offered to take over but its written in php, so I have no hope of doing that 

for iplant, they i didn't think were down too often, but i'll contact them now

**Comment by snsheth** [comment]
Thanks so much @sckott . Yes I also noticed that tnrs is working now. Too bad that they are down so often--it is a really great tool for resolving taxon names but it would be nice if it were more consistently reliable. Thanks again!

**Comment by sckott** [comment]
in your opinion is it worth using these two functions even if the data source are down sometimes. or would you prefer to not use them if they will be down sometimes?

**Comment by snsheth** [comment]
I tried other functions like gnr_resolve and am convinced that tnrs does a better job for many of my taxon names, so I would prefer irregular access to tnrs than no access at all. Of course it would be even better if the function were more reliable, as sometimes I want to re-run code and it won't work for some indefinite period of time.

**Comment by sckott** [comment]
thanks for the feedback @snsheth
