### ISSUE TITLE
Taxize: Conflicts in taxonomy

### ISSUE THREAD

**Issue by sariya** [ropensci/taxize#602]
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)
taxize_0.8.4 

```

I was eyeballing results and found that taxonomy that NCBI gives is different than what I get from taxize.

Accession number: AM420293
Attached its output from taxize. Taxonomy I get at NCBI for the respective accession number is at [link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=405948&lvl=3&keep=1&srchmode=1&unlock&lin=s&log_op=lineage_toggle).

Attached text file that has commands used to get taxonomy in taxize. Attaching session info details.
[sessioninfo.txt](https://github.com/ropensci/taxize/files/925863/sessioninfo.txt)

[command_taxize.txt](https://github.com/ropensci/taxize/files/925851/command_taxize.txt)
[issue_taxize.txt](https://github.com/ropensci/taxize/files/925850/issue_taxize.txt)

Thanks!

**Comment by sckott** [comment]
thanks for the issue @sariya !

Looks like `genbank2uid` is actually getting 3 taxonomic IDs for that accession number, but we only grab the first 

```r
xml_find_all(read_xml(con_utf8(res)), "//LinkSetDb//Link//Id")
#> {xml_nodeset (3)}
#> [1] <Id>417290</Id>
#> [2] <Id>417289</Id>
#> [3] <Id>405948</Id>
```

we use elink eutils service, which doesn't include any data except for the taxonomic IDs - so we can't include any more metadata with the taoxnomic IDs unless we do at least 1 more http request to get more metadata

**Comment by sariya** [comment]
Hi @sckott,   

Thanks for looking into it. Is there any makeshift solution to this?  
I definitely won't be able to dig into xml or play around with them for experience to R is really limited.

**Comment by sckott** [comment]
i'm working on a fix right now, will have something soon

**Comment by sckott** [comment]
@sariya reinstall `devtools::install_github("ropensci/taxize")` and try again, let me know

**Comment by sariya** [comment]
@sckott Thanks. 

taxize version: ` taxize_0.8.5.9113`
I get taxonomy that matches with NCBI in third element of list. The first two elements in list give me prophage as classification.

`uid<-genbank2uid(id = "AM420293")[3]`
`classification(uid, db = 'ncbi')`

**Comment by sckott** [comment]
@sariya we can't in the code determine which is the correct ID to give back from the function so we have to give all back. does that make sense?

**Comment by sariya** [comment]
@sckott Yes, it perfectly makes sense. I can understand it.  
Thanks again. :)

**Comment by sariya** [comment]
Hi @sckott ,  
Just something I ran into. If I use `devtools::install_github("ropensci/taxize")`   that is ` taxize_0.8.5.9113`

I get error with `tryCatch`. It fails to capture error for below command:

`uid<-tryCatch(genbank2uid(id = "gwa2_scaffold_1731_16S_1")[1],warning=function(w) NULL )`

Error: 
`Error in result[[1]][[1]] : subscript out of bounds`

tryCatch command works totally fine with `taxize_0.8.4` installed using `install.packages("taxize")`

`"gwa2_scaffold_1731_16S_1"` is dummy datum.

**Comment by sckott** [comment]
thanks, should fail better.

**Comment by sckott** [comment]
see #603
