### ISSUE TITLE
Fauna Europaea

### ISSUE THREAD

**Issue by fdschneider** [ropensci/taxize#605]
I am just exploring the taxize package for a data standardization project for animal traits. Great tool! thank you! 
 
Many of my colleagues apparently use [Fauna Europaea](http://www.fauna-eu.org/cdm_dataportal/taxon/dada6f44-b7b5-4c0a-9f32-980f54b02c36) as a reference. It uses the backend and [API of the EDIT Platform](https://cybertaxonomy.eu/cdmlib/rest-api.html), which seems to be well documented. Might be quite easy to implement for an expert.  

> Fauna Europaea is Europe's main zoological taxonomic index. Scientific names and distributions of all living, currently known, multicellular, European land and freshwater animal species are available in one authoritative database.
>
>Fauna Europaea offers key information on:
>
>-   Taxonomical index for European land and freshwater species 
>-   Information on the geographical distribution of many species 
>-   Database on taxonomic experts in Europe
>-   References on literature of European species taxonomy and distribution
>-  A browsable taxon tree
>
> [...]
> This site is powered by the [EDIT Platform for Cybertaxonomy](https://cybertaxonomy.eu/).

**Comment by sckott** [comment]
thx for the kind words. 

Good idea. I imagine this doesn't necessarily mean they expose the API that they use for their website. So far I don't see that it's exposed. Do you?  I've asked them about it. 

#443 may be related

**Comment by sckott** [comment]
any thoughts @fdschneider ?

**Comment by fdschneider** [comment]
Sorry, but no, I don't know how to access the API. It may not be open access at present. But thanks for checking it out. 
I will also try to get in touch with the maintainers at the National History Museum in Berlin and express my interest in an open API.

**Comment by sckott** [comment]
Thanks, sounds good

**Comment by sckott** [comment]
closing, unlikely to happen
