### ISSUE TITLE
Author names and homonymous

### ISSUE THREAD

**Issue by kamapu** [ropensci/taxize#610]
Dear people,
I'm trying to implement the function `tnrs` in an own package (`taxlist`) by writing a method. Since the data we are handling with may contain homonyms (same names by different authors, frequently pointing to different taxon concepts), I was wandering how they are managed in `taxize`.
I assume, the column `authority` corresponds to the author of the `acceptedname`, but I need also to know the author of the `matchedname` (see example below).
Are there some suggestions?

```r
# Just to put my question in context
sp_list <- tnrs(query=c("Bidens pilosa","Guizotia schultzii","Lactuca kenyensis"),
        source="iPlant_TNRS")
sp_list
```

**Comment by sckott** [comment]
thanks for this issue @kamapu 

Seems like the authority that is returned is in fact attached to the accepted name, not the matched name. for example, for the taxon _Lactuca kenyensis_, the accepted name returned _Lactuca inermis_ does have the authority _Forssk._, see  http://www.tropicos.org/Name/2740200 

I can ask the maintainer if its possible to return authority of the matched name as well

Another approach you can take is to use `taxize::gnr_resolve()` - uses http://resolver.globalnames.org/ - e.g., 

```r
> gnr_resolve(c("Bidens pilosa","Guizotia schultzii","Lactuca kenyensis"), data_source_ids=165, fields="all")
  user_supplied_name     submitted_name data_source_id
1      Bidens pilosa      Bidens pilosa            165
2 Guizotia schultzii Guizotia schultzii            165
3  Lactuca kenyensis  Lactuca kenyensis            165
                     data_source_title                             gni_uuid
1 Tropicos - Missouri Botanical Garden 8220dbdc-dd39-529b-9413-a437b1e1b8e8
2 Tropicos - Missouri Botanical Garden ed9ffc65-b6db-513e-b4ad-4db94d697cc2
3 Tropicos - Missouri Botanical Garden d0e73061-a69a-5b60-9128-1fc0974f0f52
                             matched_name classification_path
1                        Bidens pilosa L.
2 Guizotia schultzii Hochst. ex Sch. Bip.
3             Lactuca kenyaensis Stebbins
  classification_path_ranks classification_path_ids  taxon_id edit_distance
1                                                   144956750             0
2                                                   145403075             0
3                                                   145449062             1
                                   url          imported_at match_type
1 http://www.tropicos.org/Name/2700301 2012-02-09T14:48:21Z          2
2 http://www.tropicos.org/Name/2727481 2012-02-09T14:56:07Z          2
3 http://www.tropicos.org/Name/2735607 2012-02-09T14:56:55Z          3
                    match_value prescore score
1 Exact match by canonical form    3|0|0 0.988
2 Exact match by canonical form    3|0|0 0.988
3 Fuzzy match by canonical form    1|0|0 0.750
```

**Comment by kamapu** [comment]
Thank you, Sckott, for your prompt answer. I will check the alternative `gnr_resolve` with further examples, though the advantage of `tnrs` is that taxon name and author name are provided in separated columns.

**Comment by sckott** [comment]
> though the advantage of tnrs is that taxon name and author name are provided in separated columns

good to know.  this has been something I've been wanting to fix - be able to parse names in R, but it’s a very hard problem - there is a web service you can use from GBIF, see `taxize::gbif_parse`

**Comment by sckott** [comment]
email to maintainer sent

**Comment by sckott** [comment]
@nmatasci any thoughts on this question?

**Comment by nmatasci** [comment]
That's something that is not supported by design: the reason is the separation between the scrubbing/spellchecking and resolution (see my comment here: https://github.com/ropensci/taxize/issues/609). In the matching step, we are really just finding the string in the database that is the closest to the input string (given the structure of taxonomic names). If an author is provided, then that becomes part of the query. I'm not even sure it would be possible to return a single author in all cases, without already making a (subjective) call on which one is the correct one (which is something we tried very hard to avoid).

**Comment by kamapu** [comment]
Many thanks to both of you for this informative discussion, regarding the question #609 as well, although it seems to be that we may adapt our work-flow to the current outputs of queries done in `taxize`.

Perhaps it is important to aware users that the function **tnrs** won't provide any advice about the occurrence of homonyms when applying queries without indication of name's authority, at least in **Tropicos**. For an example:

```r
tnrs(query="Jussiaea linearis", source="iPlant_TNRS")

# BUT there is an homonym
tnrs(query="Jussiaea linearis Hochst.", source="iPlant_TNRS")
```

The first query does not tell anything about existence of the second one, although in my opinion both are "perfect matchings" (bad example, because the second option is apparently not resolved, but it is still possible to have two homonyms assigned to different taxon concepts).

Anyway, as mentioned by @sckott, a better alternative is in this case:

```r
gnr_resolve("Jussiaea linearis", data_source_ids=165, fields="all")
```

Only one final question regarding the output of `gnr_resolve`: which is the difference between the columns **user_supplied_name** and **submitted_name**?

Thank you again!

**Comment by sckott** [comment]
thanks @nmatasci for your response!

@kamapu yes, I will add  a note to the `tnrs` docs about this. 

> which is the difference between the columns `user_supplied_name` and `submitted_name`?

the `user_supplied_name` is the name the user passes into the function (unchanged); and the`submitted_name` is what is sent in the HTTP request to the global names resolver API.  The `submitted_name` may change from the user supplied name as in internally in `gnr_resolve` we cleanup the names a little bit, e..g, in the `cap_first` parameter -if user sets that to `TRUE` we capitalize the genus name and the rest lower case as the API is sensitive to case

**Comment by sckott** [comment]
to do:

- [ ] add note to `gnr_resolve` docs 
- [ ] describe columns of output data in `gnr_resolve` in its docs
