### ISSUE TITLE
itis_hierarchy unknown column: 'rankname'

### ISSUE THREAD

**Issue by dlenz1** [ropensci/taxize#617]
Dear All,

today I was trying to use the function itis_hierarchy().
But I got this error message:
> itis_hierarchy(tsn=180585)
\# A tibble: 0 x 1
\# ... with 1 variables: rankname <chr>
Warning message:
Unknown or uninitialised column: 'rankname'.

Since I realized there was a recent update, I also updated my package version (now 0.8.8), and tried again. Same error message. I also tried some older versions, just to see if this error is taxize version related. But unfortunately I get the same error.

I did nothing special, just loading the package and start using the function itis_hierarchy ...
library(taxize)
help(itis_hierarchy)
itis_hierarchy(tsn=180543)

@ taxize developers: Please, can you check if this is a bug in Taxize itself or a maybe a communication error with ITIS DB?

Thank You & Best Regards

**Comment by sckott** [comment]
thanks for the issue @dlenz1 - on vacation now, will respond next week

**Comment by dlenz1** [comment]
Now it works!
I changed nothing, I promise!

The error seems to be ITIS related ...
I already had some issues last week ...
Nothing to do for you.
