### ISSUE TITLE
`neworder_phylo` is not in `ape` NAMESPACE

### ISSUE THREAD

**Issue by ashiklom** [ropensci/taxize#618]
When trying to install package from CRAN, I get the following error:

```
Error : object ‘neworder_phylo’ is not exported by 'namespace:ape'
```

I looked through the `ape` package documentation and indeed, there is no `neworder_phylo` function in there.

The offending code in `taxize` is in [`R/taxize.package.R`][1] and the corresponding entry in the [`NAMESPACE`][2]. As far as I can tell, `neworder_phylo` isn't actually used anywhere, so there's no reason for it to be in either of these places.

[1]: https://github.com/ropensci/taxize/blob/3d4ba4927cb44b189a5c37afa4e041ced7f6d16b/R/taxize-package.R#L59
[2]: https://github.com/ropensci/taxize/blob/2042b28d5ba8005432c9410f7b0bc7b2d96717fe/NAMESPACE#L316

**Comment by sckott** [comment]
@ashiklom what version of `ape` do you have? the most recent version on CRAN does have `ape::neworder_phylo`

**Comment by sckott** [comment]
its possible `ape::neworder_phylo` is only in newer version of `ape`, and you have an older version of `ape`?

**Comment by ashiklom** [comment]
Ah yes, that was it. Strangely, my `ape` version was listed as the most current (4.1), but did not have the function, but after reinstalling from CRAN, it does even though the version number did not change. Given that such a recent version of `ape` is required, I would suggest adding a minimum version for `ape` to the description file (i.e. `ape (>=4.1)`).

All that being said, you never actually use the `neworder_phylo` anywhere in your package -- it only exists in the NAMESPACE and Roxygen directives. Why is that?

**Comment by sckott** [comment]
Weird that the fxn wasn't there.  I agree we should remove it, will merge your PR
