### ISSUE TITLE
Failing to find downstream taxa

### ISSUE THREAD

**Issue by cdeterman** [ropensci/taxize#620]
Hello, I have the current version of `taxize` (0.8.9) installed from CRAN.  I have been experimenting a little bit to familiarize myself with the functions.  I have encountered what seems to be an error to me.  For example, I can get the classification of a snake species just fine.

```r
classification("Eunectes murinus", db = "itis")
```

However, I cannot list taxa from the order, suborder or infraorder levels.  For example, lets say I want a list of all the suborders within Squamata.

```r
col_downstream("Squamata", downto = "suborder")
```

I get the error:

> Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  CData section not finished
<i>Hemidactylus adensis</i>  [63]
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  CData section not finished
Kindler, C., BÃ¶hme, W., Corti, C., Gvozdik, V., J [63]
These taxa with no data: Squamata
Try adjusting input parameters

Likewise, I cannot find any downstream taxa from Serpentes.  But instead of an error it just says 'These tax with no data: Serpentes'.

```r
col_downstream("Serpentes", downto = "infraorder")
col_downstream("Serpentes", downto = "family")
```

The only point at which the downstream search seems to work is when I get the the family level.

```r
col_downstream("boidae", downto = "genus")
```

Am I misunderstanding how the above searches should be working or is this a bug?

**Comment by sckott** [comment]
thanks @cdeterman seems like a bug - i'll look into it.

**Comment by sckott** [comment]
You'll notice that ITIS has the suborder _Serpentes_ 

```r
classification("Eunectes murinus", db = "itis")
#> $`Eunectes murinus`
#>                name         rank     id
#> 1          Animalia      kingdom 202423
#> 2         Bilateria   subkingdom 914154
#> 3     Deuterostomia infrakingdom 914156
#> 4          Chordata       phylum 158852
#> 5        Vertebrata    subphylum 331030
#> 6     Gnathostomata  infraphylum 914179
#> 7         Tetrapoda   superclass 914181
#> 8          Reptilia        class 173747
#> 9          Squamata        order 173861
#> 10        Serpentes     suborder 174118
#> 11   Alethinophidia   infraorder 634390
#> 12           Boidae       family 174321
#> 13         Eunectes        genus 209577
#> 14 Eunectes murinus      species 634802
```

but COL does not 

```r
classification("Eunectes murinus", db = "col")
#> $`Eunectes murinus`
#>               name    rank                               id
#> 1         Animalia kingdom 5ede24b0534ebd5e1f552d5b9f874a6a
#> 2         Chordata  phylum 4313bc7637e1fc1feb316a4dea2b668b
#> 3         Reptilia   class f2e91eb663bb9950c972474f65d2693b
#> 4         Squamata   order d324f3777e98688584cf8b68d0f06e5f
#> 5           Boidae  family b2e33abceaa54af9c3826b295dd69d2a
#> 6         Eunectes   genus f4a784e0bee6907d9479dd1b75026ff7
#> 7 Eunectes murinus species a97cd0d051262be8ea1c9b162f28b25f
```

So since you're trying downstream with COL data source you are running into no data as COL just doesn’t have Serpentes in it's database apparently. 

So, I think everything is working as expected, except for your example `col_downstream("Squamata", downto = "suborder")`, which was running into a problem due to COL using `infraspecies` as a taxonomic rank, which is a bit odd (since AFAIK is a sort of umbrella term for subspecific ranks), and we didn't have `infraspecies` in our taxonomic rank dataset that we use internally in the package. I just pushed a change to add `infraspecies` (reinstall to get it `devtools::install_github("ropensci/taxize")`)  - so that same call correctly now gives you no data because they apparently don't have suborder ranking data

You could however, due it with ITIS

```r
downstream("Squamata", db = "itis", downto = "suborder")
#> $Squamata
#>      tsn parentname parenttsn      taxonname rankid rankname
#> 1 174118   Squamata    173861      Serpentes    110 suborder
#> 2 209626   Squamata    173861   Amphisbaenia    110 suborder
#> 3 564528   Squamata    173861        Gekkota    110 suborder
#> 4 564529   Squamata    173861        Iguania    110 suborder
#> 5 564530   Squamata    173861 Autarchoglossa    110 suborder
```

**Comment by cdeterman** [comment]
@sckott thanks, that explains things.  Can't believe I missed that detail.  I need to be more careful with specifying the `db`.  Thanks.
