### ISSUE TITLE
Allow language selection in sci2comm, or provide language of each name in output

### ISSUE THREAD

**Issue by glaroc** [ropensci/taxize#623]
The output of sci2comm gives a vector with vernaculars in all languages combined. It would be nice if it would give a data frame as output that has a column giving the language of the common name, or a filter to select the language in the function call. I know that both EOL and ITIS identify the languages of the vernaculars, so this should be possible.

**Comment by sckott** [comment]
thanks @glaroc for opening the issue. 

have you seen the `simplify` parameter? e.g., 

```r
# simplify=TRUE by default
sci2comm(scinames='Helianthus annuus', db='eol') 
# vs. 
sci2comm(scinames='Helianthus annuus', db='eol', simplify=FALSE)
```

does that do what you want?

**Comment by glaroc** [comment]
Ah! Yes this is what I want! Maybe mention this in the simplify description? It seems pretty important to know the languages of the names you're getting in the output. 

Something like 

    (logical) If TRUE, simplify output to a vector of names. If FALSE, return variable formats from different sources, usually a data.frame. Only applies to eol and itis. Specify FALSE to obtain language of vernaculars in output.

Thanks for clarifying this.

**Comment by sckott** [comment]
sure, can do
