### ISSUE TITLE
Species name in sci2comm shouldn't be case sensitive

### ISSUE THREAD

**Issue by glaroc** [ropensci/taxize#625]
For example, 
sci2comm('Acer saccharinum') returns proper results
and 
sci2comm('acer saccharinum') returns nothing

**Comment by sckott** [comment]
thanks. 

to clarify, it's EOL that is being case sensitive. e.g. try ITIS instead of EOL, and you don't get the same problem. 

We can at least document the situation, and possibly correct names that need to be if the data provider requires it.

**Comment by glaroc** [comment]
Oddly, a direct call to the get api seems to be insensitive to case:

**Comment by sckott** [comment]
thanks - will have a look

**Comment by sckott** [comment]
should be fixed now, reinstall and try again
