### ISSUE TITLE
Error: get_wormsid produces missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by miriamgrace** [ropensci/taxize#629]
Hi, when I try to run the code below, querying WoRMS with a list of aphiaIDs "aphias".
```r
worms_records(ids = aphias, marine_only = TRUE)
```
I get the error:
```r
Error in if (els[1] != "SOAP" && els[1] != "SOAP-ENV") code <- NULL else code <- els[2] : missing value where TRUE/FALSE needed
```
Also confusing is that it was working a couple of days ago, but not a few weeks before that, and now again not. Thanks for any suggestions!

**Comment by sckott** [comment]
hi @miriamgrace - i think you're using `taxizesoap`, correct?

**Comment by miriamgrace** [comment]
Hi @sckott, yes, that's right.

**Comment by sckott** [comment]
okay - looks like you asked the same question maybe here https://github.com/ropensci/taxizesoap/issues/19 ?  

There is a new package https://cran.rstudio.com/web/packages/worrms/ to work with WoRMS - see functions in that package`worrms`

and you can use from `taxize` - but `worms_records` is not in `taxize`, but in `taxizesoap`

> Also confusing is that it was working a couple of days ago, but not a few weeks before that, and now again not

This is probably related to WorMS services sometimes not being available. (so out of our control)

**Comment by bart-v** [comment]
@miriamgrace can you tell me what list of AphiaID you are using? or on which one it fails?

**Comment by miriamgrace** [comment]
Hi @bart-v, I've been trying to reproduce the error, today that doesn't seem to happen but instead the command returns tibbles for each ID, perhaps this is related to the new package worrms somehow?

**Comment by sckott** [comment]
@miriamgrace are you still having trouble with this?
