### ISSUE TITLE
Add instructions for running tests 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#635]
to `.github/CONTRIBUTING.md` and `README`

and contributing tests

**Comment by gedankenstuecke** [comment]
Another thing that would be great for newcomers like me would be some words or links on how to package the whole thing if you contribute something new.

E.g. how to scope functions/add libraries, run `roxygen2` etc. I think @trvinh and I spent a good amount of time to figure that out this morning by going through a lot of trial-and-error and googling.

**Comment by sckott** [comment]
okay, thanks

**Comment by gedankenstuecke** [comment]
Thank you for all the kind help and support! 🎉

**Comment by sckott** [comment]
okay, see https://github.com/ropensci/taxize/blob/master/.github/CONTRIBUTING.md

shouldn't affect the PR as diff. files changed

**Comment by gedankenstuecke** [comment]
That’s great! Thanks so much for that! 😍
