### ISSUE TITLE
catalogue of life speed issue

### ISSUE THREAD

**Issue by andzandz11** [ropensci/taxize#637]
I need some advice on how to speed CoL up. I have a list of 3700 species and need to compare them to CoL. This list also includes author information. How can i incorporate this into the search query? GBIF for example has fuzzy matching for the author name. Does CoL support this?
The list matching service is too rough.
I tried:
<details> <summary><strong>code</strong></summary>

```r
cl <- makeCluster(100)
registerDoParallel(cl)

col_results <- vector(mode="list",length=nrow(fwf))

foreach (i=1:nrow(fwf)) %dopar%
{
  col_results[[i]] <- taxize::col_search(name=fwf[i,"sci_name"], response="full")
  #if (i%%10==0) print(paste0(i, " of ",nrow(fwf)))
  print(i)
}

```
</details>

but no speedup.

**Comment by sckott** [comment]
WRT speed, can you be more specific?  no speedup relative to what?

I would not include authorities with names in searches for COL - I am working on a tool for that ([pegax](https://github.com/ropenscilabs/pegax)) but it's not quite ready yet. For now, you can try `taxize::gbif_parse`, e.g., `taxize::gbif_parse("Apis alpina Linnaeus, 1758")`

If you look at the docs for `col_search`, you can see 

> Only exact matches found the name given will be returned, unless one or wildcards are included           in the search string. An * (asterisk) character denotes a wildcard; a character may also be used. The name must be at least 3 characters long, not counting wildcard characters. 

What does this mean?

>  The list matching service is too rough.

**Comment by andzandz11** [comment]
I thought if I use the parallel package with a cluster with one hundred nodes it would download 100 queries in parallel, but it didn't. I Need 3000 CoL queries to be processes within One Hour. At the Single Process Speed it would Take almost a day or so.

**Comment by sckott** [comment]
Something you may be interested in is https://github.com/ropensci/taxizedb/ which helps users get access to SQL dumps of some taxonomic databases, including COL, ITIS, GBIF taxonomic backbone, beware that COL SQL dump is quite large

**Comment by sckott** [comment]
closing - though happy to reopen if you still want to discuss this
