### ISSUE TITLE
tnrs(source = "NCBI") API reply fails to import/parse into R

### ISSUE THREAD

**Issue by wpetry** [ropensci/taxize#645]
<details> <summary><strong>Session Info Windows machine -- fails</strong></summary>

```r
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.9.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13        codetools_0.2-15    lattice_0.20-35     ape_5.0            
 [5] reshape_0.8.7       foreach_1.4.3       mime_0.5            grid_3.4.1         
 [9] crul_0.4.0          R6_2.2.2            plyr_1.8.4          jsonlite_1.5       
[13] nlme_3.1-131        magrittr_1.5        httr_1.3.1          stringi_1.1.6      
[17] reshape2_1.4.2      curl_3.0            data.table_1.10.4-3 xml2_1.1.1         
[21] iterators_1.0.8     tools_3.4.1         stringr_1.2.0       bold_0.5.0         
[25] yaml_2.1.14         parallel_3.4.1      compiler_3.4.1
```
</details>

<details> <summary><strong>Session Info Mac machine -- works</strong></summary>

```r
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.9.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13        codetools_0.2-15    lattice_0.20-35     ape_5.0            
 [5] reshape_0.8.7       foreach_1.4.3       mime_0.5            grid_3.4.1         
 [9] crul_0.4.0          R6_2.2.2            plyr_1.8.4          jsonlite_1.5       
[13] nlme_3.1-131        magrittr_1.5        httr_1.3.1          stringi_1.1.5      
[17] reshape2_1.4.2      curl_3.0            data.table_1.10.4-3 xml2_1.1.1         
[21] iterators_1.0.8     tools_3.4.1         stringr_1.2.0       bold_0.5.0         
[25] parallel_3.4.1      compiler_3.4.1 
```
</details>

I'm having trouble sharing code with a collaborator across platforms, where `tnrs()` fails on my collaborator's computer when attempting to clean names using the NCBI taxonomy. I *think* the problem is happening during the import/parsing of the API reply because:

1) setting `source = "iPlant_TNRS"` returns name matches on both machines
2) the API replies provided on taxosaurus.org appear to have worked on both machines

Reprex:
```r
library(taxize)

spp <- c("Quercus agrifolia", "Quercus cerris", "Quercus illex")

iplant_names <- tnrs(query = spp, source = "iPlant_TNRS")  # success on both machines!
ncbi_names <- tnrs(query = spp, source = "NCBI") # on Windows: successful API call, returns 0-row data frame; success on Mac
```

`ncbi_names` returns either:

On **Windows machine**:
```r
Calling http://taxosaurus.org/retrieve/8927037869e2d2ea909deb3affd29b28
[1] submittedname acceptedname  sourceid      score         matchedname  
[6] annotations   uri          
<0 rows> (or 0-length row.names)
```
<details> <summary><strong>API reply--Windows</strong></summary>
{"status":"OK","names":[{"matchCount":1,"matches":[{"acceptedName":"Quercus cerris","sourceId":"NCBI","score":"1","matchedName":"\"Quercus cerris\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/39468"}],"submittedName":"\"Quercus cerris\"\r"},{"matchCount":1,"matches":[{"acceptedName":"Quercus agrifolia","sourceId":"NCBI","score":"1","matchedName":"\"Quercus agrifolia\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/97693"}],"submittedName":"\"Quercus agrifolia\"\r"},{"matchCount":1,"matches":[{"acceptedName":"Illex","sourceId":"NCBI","score":"1","matchedName":"\"Quercus illex\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/6627"}],"submittedName":"\"Quercus illex\"\r"}],"metadata":{"spellcheckers":[{"name":"NCBI","description":"NCBI Spell Checker","annotations":{},"uri":"http://www.ncbi.nlm.nih.gov/","sourceId":1,"publication":"http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2578899/","call":"python2.6 tnrs_spellchecker/ncbi_spell.py","rank":1}],"sources":[{"status":"200: OK","name":"NCBI","description":"NCBI Taxonomy","uri":"http://www.ncbi.nlm.nih.gov/taxonomy","annotations":{},"sourceId":"NCBI","publication":"Federhen S. The Taxonomy Project.2002 Oct 9 [Updated 2003 Aug 13]. In: McEntyre J., Ostell J., editors. The NCBI Handbook [Internet]. Bethesda (MD): National Center for Biotechnology Information (US);2002.","rank":3,"code":"ICZN,ICN,ICNB"}],"sub_date":"Wed Nov 22 09:23:38 2017","resolver_version":"1.2.0","jobId":"8927037869e2d2ea909deb3affd29b28"}}
</details>

On **Mac machine**:
```r
Calling http://taxosaurus.org/retrieve/29d06d89ac0b695e3889bc132f58203f
      submittedname      acceptedname sourceid score       matchedname
1 Quercus agrifolia Quercus agrifolia     NCBI     1 Quercus agrifolia
2    Quercus cerris    Quercus cerris     NCBI     1    Quercus cerris
3     Quercus illex             Illex     NCBI     1     Quercus illex
  annotations                                         uri
1        none https://www.ncbi.nlm.nih.gov/taxonomy/97693
2        none https://www.ncbi.nlm.nih.gov/taxonomy/39468
3        none  https://www.ncbi.nlm.nih.gov/taxonomy/6627
```
<details> <summary><strong>API reply--Mac</strong></summary>
{"status":"OK","names":[{"matchCount":1,"matches":[{"acceptedName":"Quercus cerris","sourceId":"NCBI","score":"1","matchedName":"\"Quercus cerris\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/39468"}],"submittedName":"\"Quercus cerris\"\r"},{"matchCount":1,"matches":[{"acceptedName":"Quercus agrifolia","sourceId":"NCBI","score":"1","matchedName":"\"Quercus agrifolia\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/97693"}],"submittedName":"\"Quercus agrifolia\"\r"},{"matchCount":1,"matches":[{"acceptedName":"Illex","sourceId":"NCBI","score":"1","matchedName":"\"Quercus illex\"\r","annotations":{},"uri":"https://www.ncbi.nlm.nih.gov/taxonomy/6627"}],"submittedName":"\"Quercus illex\"\r"}],"metadata":{"spellcheckers":[{"name":"NCBI","description":"NCBI Spell Checker","annotations":{},"uri":"http://www.ncbi.nlm.nih.gov/","sourceId":1,"publication":"http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2578899/","call":"python2.6 tnrs_spellchecker/ncbi_spell.py","rank":1}],"sources":[{"status":"200: OK","name":"NCBI","description":"NCBI Taxonomy","uri":"http://www.ncbi.nlm.nih.gov/taxonomy","annotations":{},"sourceId":"NCBI","publication":"Federhen S. The Taxonomy Project.2002 Oct 9 [Updated 2003 Aug 13]. In: McEntyre J., Ostell J., editors. The NCBI Handbook [Internet]. Bethesda (MD): National Center for Biotechnology Information (US);2002.","rank":3,"code":"ICZN,ICN,ICNB"}],"sub_date":"Wed Nov 22 09:23:38 2017","resolver_version":"1.2.0","jobId":"8927037869e2d2ea909deb3affd29b28"}}
</details>

A huge thanks for looking into this!

**Comment by sckott** [comment]
@wpetry can you and your collaborator reinstall from github `devtools::install_github("ropensci/taxize")` and try again, i think i found the problem (somehow `\r` were ending up at the end of submitted names in data that comes back from TNRS ), let me know if it works.

**Comment by wpetry** [comment]
Thanks for such a fast response @sckott.

On Windows the data now import to R from the API reply, but all the rows of `submittedname` and `matchedname` have `\r` appended to them. We can clip those off with regex for now, but it still seems like something is amiss.

Mac is unaffected by the update—still working just fine.

**Comment by sckott** [comment]
thx @wpetry - that's weird, that didn't happen on the windows machine i tested on, will look into again, 

to be clear, the windows user did actually get data back though, yes? instead of an empty data.frame?

**Comment by wpetry** [comment]
Yes, data came back like this:

```r
      submittedname      acceptedname sourceid score       matchedname
1 Quercus agrifolia\r Quercus agrifolia     NCBI     1 Quercus agrifolia\r
2    Quercus cerris\r    Quercus cerris     NCBI     1    Quercus cerris\r
3     Quercus illex\r             Illex     NCBI     1     Quercus illex\r
  annotations                                         uri
1        none https://www.ncbi.nlm.nih.gov/taxonomy/97693
2        none https://www.ncbi.nlm.nih.gov/taxonomy/39468
3        none  https://www.ncbi.nlm.nih.gov/taxonomy/6627
```

**Comment by sckott** [comment]
thanks, progress at least. will see about those dang returns

**Comment by sckott** [comment]
if folks open issues about this we can follow up
