### ISSUE TITLE
Inconsistent types in `children` output

### ISSUE THREAD

**Issue by arendsee** [ropensci/taxize#648]
Apologies in advance for nitpicking, but column types in empty and non-empty dataframes returned by `children` are not the same:

``` R
> library(taxize)
> sapply(children(3702, db='ncbi')[[1]], class)
childtaxa_id childtaxa_name childtaxa_rank
   "numeric"       "factor"       "factor"
> sapply(children(3701, db='ncbi')[[1]], class)
  childtaxa_id childtaxa_name childtaxa_rank
   "character"    "character"    "character"
```

This can probably be fixed by justing swapping out the default, empty df with

``` R
  data.frame(
    childtaxa_id   = character(0),
    childtaxa_name = character(0),
    childtaxa_rank = character(0),
    stringsAsFactors=FALSE
  )
```

I think taxa IDs are not guaranteed to be integers in all databases, so the `character` type is probably appropriate.

**Comment by sckott** [comment]
thanks, always good to catch these things and make them consistent.

**Comment by arendsee** [comment]
I can fix this if you like. I think I've found the problem.

**Comment by sckott** [comment]
sounds good. can you check that worms is consistent with that?

**Comment by arendsee** [comment]
I've just pushed a second commit that tests and fixes itis. But worms are a bit tricky, I might open a new issue on them.

**Comment by arendsee** [comment]
I think I'll go ahead and make pull request, leaving worms for later

**Comment by sckott** [comment]
okay,
