### ISSUE TITLE
Lower number of outputs by classification()

### ISSUE THREAD

**Issue by tmkurobe** [ropensci/taxize#652]
<details> <summary><strong>
Session info
</strong></summary>

```r
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.10.4 plyr_1.8.4        ggplot2_2.2.1     taxize_0.9.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     xml2_1.1.1       magrittr_1.5     munsell_0.4.3    colorspace_1.3-2 ape_5.0          lattice_0.20-35  R6_2.2.2         rlang_0.1.1     
[10] foreach_1.4.3    stringr_1.2.0    httr_1.2.1       tools_3.3.3      parallel_3.3.3   bold_0.5.0       grid_3.3.3       nlme_3.1-131     gtable_0.2.0    
[19] iterators_1.0.8  lazyeval_0.2.0   tibble_1.3.4     reshape2_1.4.2   codetools_0.2-15 curl_2.8.1       crul_0.4.0       stringi_1.1.5    scales_0.4.1    
[28] jsonlite_1.5     reshape_0.8.7
```
</details>

Hi,
I'm trying to retrieve taxonomy information using "staxids" from blastn search results. classification() returns lower numbers of outputs than the query, so it's causing a problem with cbind. Could you give me suggestion to deal with the issue? A text file with staxids is attached.
[staxids.txt](https://github.com/ropensci/taxize/files/1560646/staxids.txt)

Here is the code.

```
library(taxize)
df1 = read.table(file = "staxids.txt", sep = "\t", header = TRUE)
df2 = cbind(classification(df1$staxids, db = 'ncbi'))
```

And the error message.
```
Error in `$<-.data.frame`(`*tmp*`, "query", value = c("758796", "1973481",  : 
  replacement has 250 rows, data has 249
```

Thank you,

**Comment by sckott** [comment]
thanks @tmkurobe looks like you didn't put your session info in though

<img width="212" alt="screen shot 2017-12-14 at 5 06 35 pm" src="https://user-images.githubusercontent.com/577668/34016793-33c784c4-e0f1-11e7-803c-1ffd91a17f02.png">

can you include that . you can just edit your issue

**Comment by tmkurobe** [comment]
It seems staxid 1361 returns "NA".

```
library(taxize)
df1 = read.table(file = "staxids.txt", sep = "\t", header = TRUE)
df2.0= df1[(120), ]
df2.1 = cbind(classification(df2.0$staxids, db = 'ncbi')) # This doesn't works. staxid 1361 is returning NA.

df3.0= df1[(119), ]
df3.1 = cbind(classification(df3.0$staxids, db = 'ncbi')) # This works.
```

**Comment by sckott** [comment]
thanks @tmkurobe will have a look

**Comment by sckott** [comment]
@tmkurobe hmm, what are staxid's ?  when using `db = 'ncbi'` (and `get_uid()` which is used inside `classification`) you need to pass a NCBI taxonomy identifier, which they call a UID. what are these staxid's?  if they map somehow to ncbi uid's then we can go from there. You can also pass names to `get_uid` or `classification`, but it looks like you only have those ids

**Comment by tmkurobe** [comment]
Hello. I just realized an error in my code. The classification() is working beautifully now! I'm sorry about the confusion.

staxid is from blastn search (http://www.metagenomics.wiki/tools/blast/blastn-output-format-6). When I was formatting blastn search result, my grep command accidentally removed a portion of staxid, which was causing the error.

I am so sorry. And thank you for your help!

**Comment by sckott** [comment]
glad it works now
