### ISSUE TITLE
downstream NCBI "Bryophyta" not responding

### ISSUE THREAD

**Issue by andzandz11** [ropensci/taxize#655]
`x <- downstream("Bryophyta", db = "ncbi", downto = "family")`

Nothing is happening for almost an hour, if I use "Tracheophyta" as query it is done in 20 minutes (I did this in June), although there are much more families.

PS: I have a API key, how can I include it in the query? Nothing popps up if I use ?downstream.

<details> <summary><strong>Session Info

</strong></summary>

```r

R version 3.4.2 (2017-09-28) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    [5] LC_TIME=German_Germany.1252      attached base packages:  [1] grid      stats4    parallel  stats     graphics  grDevices utils     datasets  methods   [10] base       other attached packages:  [1] seqLogo_1.42.0       doParallel_1.0.11    foreach_1.4.4        taxize_0.9.0.9219     [5] rentrez_1.1.0        ips_0.0-7            XML_3.98-1.9         colorspace_1.3-2      [9] ape_5.0              ggplot2_2.2.1        rBLAST_0.99.1        Biostrings_2.44.2    [13] XVector_0.16.0       IRanges_2.10.5       S4Vectors_0.14.7     BiocGenerics_0.22.1  [17] dplyr_0.7.4          data.table_1.10.4-3  iterators_1.0.9      magrittr_1.5         [21] stringi_1.1.6        reshape_0.8.7        Rcpp_0.12.14         assertthat_0.2.0     [25] devtools_1.13.4      BiocInstaller_1.26.1  loaded via a namespace (and not attached):  [1] compiler_3.4.2   git2r_0.20.0     plyr_1.8.4       bindr_0.1        tools_3.4.2       [6] zlibbioc_1.22.0  digest_0.6.13    jsonlite_1.5     nlme_3.1-131     lattice_0.20-35  [11] memoise_1.1.0    tibble_1.3.4     gtable_0.2.0     pkgconfig_2.0.1  rlang_0.1.4      [16] crul_0.4.0       curl_3.1         bindrcpp_0.2     xml2_1.1.1       stringr_1.2.0    [21] withr_2.1.1      httr_1.3.1       triebeard_0.3.0  glue_1.2.0       R6_2.2.2         [26] reshape2_1.4.3   urltools_1.6.0   codetools_0.2-15 scales_0.5.0     bold_0.5.0       [31] lazyeval_0.2.1   munsell_0.4.3    zoo_1.8-0
--
 
> | >
>



```
</details>

edit: 
Sys.setenv(ENTREZ_KEY="**********************************")
Still nothing after 50 minutes.

There is still internet traffic of RStudio of 4KB/s. Maybe the 10 queries per second are still not enough? Maybe downstream uses too many requests per second, so it will take forever with the new limits?

**Comment by sckott** [comment]
thanks for the report. Will check if using the API key will help here. It's implemented in `get_uid` but not in other fxns in the pkg that use NCBI (#640)

**Comment by sckott** [comment]
so i'm adding api key support to `ncbi_downstream` and `ncbi_children` which is inside of that fxn. 

started your query after those changes in case having the api key helps - was running for a long time, with no errors, but than one request hung up for a long time, not sure why - i imagine its a problem on NCBI side of things, but not sure. 

do you know about `taxizedb`?  https://github.com/ropensci/taxizedb Recently, it's gotten more features for NCBI specifically. so you can now do downstream with NCBI with the NCBI taxonomy locally on your machine. e.g., 

```r
devtools::install_github("ropensci/taxizedb")
x <- downstream("Bryophyta", db = "ncbi", downto="family")
tibble::as_tibble(x$Bryophyta)
```

```r
# A tibble: 115 x 3
   childtaxa_id     childtaxa_name   rank
          <chr>              <chr>  <chr>
 1      1966358     Roellobryaceae family
 2      1929020       Saelaniaceae family
 3      1929019    Flexitrichaceae family
 4      1107942    Micromitriaceae family
 5      1037559        Miyabeaceae family
 6      1032295    Pulchrinodaceae family
 7      1031712     Hypodontiaceae family
 8       879269     Flatbergiaceae family
 9       760211   Braithwaiteaceae family
10       404319 Pylaisiadelphaceae family
# ... with 105 more rows
```

i don't know if that's the right answer for families within _Bryophyta_, but it works very fast, just a few seconds

**Comment by andzandz11** [comment]
I love it. The taxziedb solution works flawlessly. 
Thanks for your help! My issue is resolved, nontheless maybe investigating the NCBI issue with the downstream request would help preventing further errors.

**Comment by sckott** [comment]
glad it works for you. I think that your query with `taxize` is better now with Entrez API keys supported, and because it takes a long time, a fast and stable internet connection is good to have. I think your query would work with `taxize` it would just take a while to finiish. but if `taxizedb` works, that's great.
