### ISSUE TITLE
gnr_resolve(..., preferred_data_sources = 1, fields = "all") returns only 5 fields

### ISSUE THREAD

**Issue by MikkoVihtakari** [ropensci/taxize#656]
Thank you for writing such a useful package! While trying to sort my messy species lists, I noticed that the `gnr_resolve` function returns only 5 fields when using the `preferred_data_sources` argument, even though `fields = "all"`

Compare:
```r
gnr_resolve("Homo sabiens", fields = "all", preferred_data_sources = 3)
gnr_resolve("Homo sabiens", fields = "all")[1,]
```
According to my interpretation, this behavior might be due to lines 249-257 in 2017-12-22 version of [`gnr_resolve`](https://github.com/ropensci/taxize/blob/master/R/gnr_resolve.R)

<details> <summary><strong>Session Info</strong></summary>

```r
devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Helsinki             
 date     2017-12-22                  

Packages ----------------------------------------------------------------------------------------------------------
 package    * version    date       source                          
 ape          5.0        2017-10-30 cran (@5.0)                     
 base       * 3.4.3      2017-12-07 local                           
 bold         0.5.0      2017-07-21 CRAN (R 3.4.1)                  
 codetools    0.2-15     2016-10-05 CRAN (R 3.4.3)                  
 compiler     3.4.3      2017-12-07 local                           
 crul         0.4.0      2017-10-02 CRAN (R 3.4.2)                  
 curl         3.1        2017-12-12 CRAN (R 3.4.3)                  
 data.table   1.10.4-3   2017-10-27 cran (@1.10.4-)                 
 datasets   * 3.4.3      2017-12-07 local                           
 devtools   * 1.13.4     2017-11-09 CRAN (R 3.4.2)                  
 digest       0.6.13     2017-12-14 cran (@0.6.13)                  
 evaluate     0.10.1     2017-06-24 cran (@0.10.1)                  
 foreach      1.4.4      2017-12-12 cran (@1.4.4)                   
 git2r        0.18.0     2017-01-01 CRAN (R 3.4.0)                  
 graphics   * 3.4.3      2017-12-07 local                           
 grDevices  * 3.4.3      2017-12-07 local                           
 grid         3.4.3      2017-12-07 local                           
 highr        0.6        2016-05-09 CRAN (R 3.4.0)                  
 httr         1.3.1      2017-08-20 cran (@1.3.1)                   
 iterators    1.0.9      2017-12-12 cran (@1.0.9)                   
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.0)                  
 knitr        1.17       2017-08-10 cran (@1.17)                    
 lattice      0.20-35    2017-03-25 CRAN (R 3.4.3)                  
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                  
 Matrix       1.2-12     2017-11-20 CRAN (R 3.4.3)                  
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                  
 methods    * 3.4.3      2017-12-07 local                           
 nlme         3.1-131    2017-02-06 CRAN (R 3.4.3)                  
 parallel     3.4.3      2017-12-07 local                           
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.0)                  
 R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                  
 Rcpp         0.12.14    2017-11-23 cran (@0.12.14)                 
 reshape      0.8.7      2017-08-06 CRAN (R 3.4.1)                  
 reshape2     1.4.3      2017-12-11 cran (@1.4.3)                   
 stats      * 3.4.3      2017-12-07 local                           
 stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                  
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                  
 taxize     * 0.9.0.9320 2017-12-22 Github (ropensci/taxize@8ce30a8)
 tools        3.4.3      2017-12-07 local                           
 utils      * 3.4.3      2017-12-07 local                           
 withr        2.1.1      2017-12-19 cran (@2.1.1)                   
 xml2         1.1.1      2017-01-24 CRAN (R 3.4.0)                  
 yaml         2.1.16     2017-12-12 cran (@2.1.16)                  
 zoo          1.8-0      2017-04-12 CRAN (R 3.4.0) 
```
</details>

**Comment by sckott** [comment]
(thx for the kind words)

thx for the report  - those lines might be it - i'll have a look

**Comment by sckott** [comment]
two issues:

1. when `preferred_data_sources` is given in the fxn call, we only return the preferred_data_sources data - e.g. see the request output at http://resolver.globalnames.org/name_resolvers.json?names=Homo%20sabiens&data_source_ids=&preferred_data_sources=3 - the `results` slot we don't return - not sure why we did that, or if we meant to include preferred with regular data but forgot. Seems we should return both for sure
2. our docs have very little info on the preferred param, and the API docs http://gnrd.globalnames.org/api have no information on the parameter. We def. need more clarity on that - any help on this @dimus ?

**Comment by sckott** [comment]
@dimus is there any more information on the `preferred_data_sources` parameter and what it does?

**Comment by dimus** [comment]
oups sorry missed this message with all the holiday mail. The `preferred_data_sources` parameter had been requested by Biodiversity Heritage Library folks. Their motivation as the following:

For simpicity and to avoid huge traffic they use `best_match_only` parameter and get only one 'best' match. However they also wanted to create a link to NameBank and EOL, so beside the best result, if the name did match either these two data sources, they also wanted to get results. So `preferred_data_source` tries to get a match in requested data sources, now matter what was the "best result"

**Comment by sckott** [comment]
thanks for the explanation @dimus  !

**Comment by MikkoVihtakari** [comment]
Have you found a solution for this? At least receiving URL or ID would together with matched_name2 and data_source_title be nice. I thought to use `gnr_resolve` to fix typos and extract the species IDs from a best fitting data source. If I had the ID, I could pass it to `get_*` functions potentially reducing the time needed to extract information and server pressure caused by hundreds of inquiries. 

Trying to do something like [here](https://gist.github.com/fdschneider/69e61b14c12ccdda780fbc1c5f0a4f1c), but using several data sources as the species I am working with are not consistently available in one source.

**Comment by sckott** [comment]
not yet - I plan to simply return all the data when `preferred_data_sources` is given. Does that work?

**Comment by MikkoVihtakari** [comment]
@sckott Yes, that would be perfect!

**Comment by sckott** [comment]
@MikkoVihtakari can you reinstall `devtools::install_github("ropensci/taxize")` and try again

**Comment by MikkoVihtakari** [comment]
Thank you!
