### ISSUE TITLE
Space required after the Public Identifier [65]

### ISSUE THREAD

**Issue by fgabriel1891** [ropensci/taxize#657]
Hi Scott, 

I have come across this new following error using a personal function which calls taxize : 

```r
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Space required after the Public Identifier [65] 
```

Debbuging I see that it relates to the `tax_name` part of the function. Does it have something to do with new ncbi database limits, I saw about it in other issues in taxize. 

Any ideas? The code below. I have tried with different paths to articles, and the problem arises even with articles that have worked before. 

Thanks for your response! 

Gabriel
```r
# Scrape scientific names in text with taxize 
names <- scrapenames(file = path2frug, return_content = T)

# Identify family names
families <- taxize::tax_name(names, get = "family", db = "ncbi",
                             verbose = F,
                             ask = F) # Look for families

```
</details>

**Comment by sckott** [comment]
thanks @fgabriel1891 

> I have come across this new following error:

in what function? is it `srapenames()` ?  if so, `tax_name` isn't called inside of `scrapenames`

can you share the `paths2frug` file so I can reproduce the problem?

**Comment by fgabriel1891** [comment]
Hello @sckott, sorry I was not explicit enough. I have edited the issue. 
I'm working on a custom function to help mine pairwise species-species interactions from literature. This function makes use of `scrapenames()` and `tax_name()` from taxize, I shared in the issue the part of the function that I see produces the error, specifically the `tax_name()` part. I was not getting this error in the past, and I have not modify the function or changed the test files. 

[Link](https://goo.gl/1mN3Tg) to the files so you can reproduce the error. 

Thanks for your response!

**Comment by sckott** [comment]
@fgabriel1891 i can't exactly reproduce that error. 

first thing is (and maybe you did this too but didn't show it) `tax_name` expects a character vector of taxonomic names - not a list or data.frame or anything else. 

second, seems to work for me:

```r
path_yaap <- "yaap_et_al_2015_MammalUseRaphia.pdf"
names_yaap <- scrapenames(file = path_yaap, return_content = TRUE)
families_yaap <- taxize::tax_name(names_yaap$data$scientificname[1:10], 
    get = "family", db = "ncbi", verbose = FALSE, ask = FALSE)
families_yaap
```

```r
     db                     query          family
1  ncbi                  Mammalia            <NA>
2  ncbi          Raphia taedigera            <NA>
3  ncbi          Raphia taedigera            <NA>
4  ncbi              R. taedigera            <NA>
5  ncbi              R. taedigera            <NA>
6  ncbi              Nasua narica     Procyonidae
7  ncbi Pecari tajacu) whitefaced            <NA>
8  ncbi           Cebus capucinus         Cebidae
9  ncbi        Leopardus pardalis         Felidae
10 ncbi         Tamandua mexicana Myrmecophagidae
```

```r
path_hawes <- "Hawes_et_al_FruitsFrugivoryNeotropics.pdf"
names_hawes <- scrapenames(file = path_hawes, return_content = TRUE)
families_hawes <- taxize::tax_name(names_hawes$data$scientificname[1:10], 
    get = "family", db = "ncbi", verbose = FALSE, ask = FALSE)
families_hawes
```

```r
     db        query      family
1  ncbi       Agenor        <NA>
2  ncbi Pesquisas da        <NA>
3  ncbi         Inpa        <NA>
4  ncbi       Manaus        <NA>
5  ncbi        Maira    Asilidae
6  ncbi      Vanessa Nymphalidae
7  ncbi        Anisa        <NA>
8  ncbi     Amazonia Meliolaceae
9  ncbi   Muscarella Orchidaceae
10 ncbi    Ficus spp        <NA>
```

---

curious if you'r writing a paper that includes this work?  if so, very curious what the use case is

**Comment by fgabriel1891** [comment]
Thanks! @sckott, it was a problem with the input vector of names. Is working fine now.  

Sorry the late reply, I'm not working 100% of my time on this, mostly on weekends.

Yes, I´m working on a method to optimize the search for specific pairwise interactions in published literature. 

I presented a [poster](https://sites.google.com/view/fgabriel1891/publications) recently, making use of a previous [tool](https://fgabriel1891.shinyapps.io/biodiversityobservationsminer/) written in shiny to help mine such information. Now I'm working on a new, simpler tool [SpeciesInteractionsMiner](https://github.com/fgabriel1891/SpeciesInteractionsMiner) to help on this search process of biodiversity data to make it digitally available. Ideally looking forward to closing (in some way) the data limitation for future predictive models on species interactions and finding knowledge gaps.  Focusing on frugivory mutualisms at the moment.  Publications will come out asap!

**Comment by sckott** [comment]
Great, glad its working now. 

That research sounds very cool.
