### ISSUE TITLE
switch pkg to use markdown docs 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#658]

**Comment by Alanocallaghan** [comment]
Can you elaborate on this a bit @sckott ?

**Comment by jarioksa** [comment]
Yeah, I'm baffled, too. **rmarkdown** is a tool: why should you change the final product (docs) just to use another tool for a similar result?

**Comment by Rekyt** [comment]
I think that @sckott means to change the documentation that is generated by `roxygen2` to use markdown format (see more about it [in this vignette of `roxygen2`](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html))

**Comment by sckott** [comment]
yes, to use markdown formatting instead of latex. i think it's easier for everyone to contribute when it's markdown. in addition, it usually takes up less characters so it's easier less text.  I'm not sure i see a downside other than the work that goes into it. 

the only caveat is markdown doesn't work in templates AFAIK https://github.com/ropensci/taxize/tree/master/man-roxygen

@Alanocallaghan if you're interested in contributing you can look at that link for how to use markdown

**Comment by Alanocallaghan** [comment]
You mean to change the roxygen docs to use Markdown formatting ("\`id\`") instead of latex ("\code{id}")?

**Comment by sckott** [comment]
@Alanocallaghan  Yes, that's one example.

**Comment by Alanocallaghan** [comment]
Alrighty, I'll try to get that done asap. Thanks for clarifying.

**Comment by sckott** [comment]
@Alanocallaghan thanks. i'd suggest doing a one or a few files in a small pull request instead of trying for all of them in 1 PR - and go from there if the first one goes well
