### ISSUE TITLE
Scope of taxonomies

### ISSUE THREAD

**Issue by jonmcalder** [ropensci/taxize#661]
Is this package specifically limited to/focussed on natural science taxonomies, or could it in theory be expanded to include taxonomies in other areas?

**Comment by sckott** [comment]
👋 Thanks for your question. 

It's focused on taxonomies of scientific names. To give an overview of the landscape here:

- `taxize` was the original thing in the family. it works with databases of biological taxonomy data with http requests
- [taxizedb](https://github.com/ropensci/taxizedb) - for working with SQL dumps of some of the data sources avail over web http requests in `taxize`
- [taxizesoap](https://github.com/ropensci/taxizesoap) - for data sources that only use SOAP protocol 
- [pytaxize](https://github.com/sckott/pytaxize) - python port of `taxize`, not really hitting it out of the park yet, still hoping to make time for it
- [taxize book](https://github.com/ropensci/taxize-book) just started, not much there yet

---

A few thoughts:

- R classes for taxonomic data and joint name/data manipulation of that data (a sort of taxonomically aware dplyr data munging), has been pulled out into https://github.com/ropensci/taxa and will be used inside taxize (ongoing dev branch)
- identifiers: not really any code per se maybe, but we've found it useful to focus work around identifiers. All data sources we work with have identifiers for each name. So we try to make it easy to get an identifier and then once that is acquired, make it simple to use the identifier to do something else 

---

What kind of taxonomies are you talking about?  That would help me in thinking about your question better

**Comment by jonmcalder** [comment]
Hi @sckott! Thanks for the prompt (and thorough!) feedback.

The kind of thing I had in mind would be global standards/taxonomies in the economic/legal space etc. An example of this would be the [**L**egal **E**ntity **I**identifier taxonomy](https://taxonomies.xbrl.org/taxonomy/14) which is now a freely available API [here](https://www.gleif.org/en/lei-data/gleif-lei-look-up-api/access-the-api#). There are more examples of similar taxonomies listed [here](https://taxonomies.xbrl.org/).

My guess is that these sorts of taxonomies have mostly commercial application and value but may be useful in some areas of social science research (economics, law etc). To me ROpenSci seems to be mostly focused on Natural Science but your mission statement just says "science" so I figured there's no harm in asking.

**Comment by sckott** [comment]
> My guess is that these sorts of taxonomies have mostly commercial application and value but may be useful in some areas of social science research (economics, law etc). To me ROpenSci seems to be mostly focused on Natural Science but your mission statement just says "science" so I figured there's no harm in asking.

definitely no harm in asking :) - We do focus on tools that have at least some application in academia, even if there's a lot of use outside of academia. So not just "science" per se, e.g., we have some pkgs in digital history. 

Do you know if anyone uses the taxonomies you linked to for research at all?

**Comment by jonmcalder** [comment]
I don't know of anyone at the moment - my (initial) research in this area is work related and thus commercial. Thanks for your openness in discussing the possibility though - I may be back in future depending on where my journey takes me 😄

**Comment by sckott** [comment]
Sounds good. it'd be really cool if there was some way to represent/manipulate/work with/etc. taxonomies across disciplines - i guess lower level tools/R pkg that help represent taxonomies in an abstract sense might be possible - then other taxonomys specific R pkgs could build on that as needed
