### ISSUE TITLE
Data source failing to respond - IUCN (81)

### ISSUE THREAD

**Issue by git-og** [ropensci/taxize#669]
<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] xlsx_0.5.7      xlsxjars_0.6.1  rJava_0.9-9     taxize_0.9.2    rredlist_0.4.0  plyr_1.8.4     
 [7] forcats_0.3.0   stringr_1.2.0   dplyr_0.7.4     purrr_0.2.4     readr_1.1.1     tidyr_0.8.0    
[13] tibble_1.4.2    ggplot2_2.2.1   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] zoo_1.8-0         reshape2_1.4.2    haven_1.1.1       lattice_0.20-35   colorspace_1.3-2  yaml_2.1.14      
 [7] utf8_1.1.3        rlang_0.2.0       pillar_1.2.1      foreign_0.8-69    glue_1.2.0        modelr_0.1.1     
[13] readxl_1.0.0      bindrcpp_0.2      foreach_1.4.3     bindr_0.1         munsell_0.4.3     gtable_0.2.0     
[19] cellranger_1.1.0  rvest_0.3.2       codetools_0.2-15  psych_1.7.8       parallel_3.4.3    curl_2.8.1       
[25] triebeard_0.3.0   urltools_1.6.0    broom_0.4.3       Rcpp_0.12.15      scales_0.4.1      jsonlite_1.5     
[31] mnormt_1.5-5      hms_0.4.1         stringi_1.1.5     grid_3.4.3        cli_1.0.0         tools_3.4.3      
[37] magrittr_1.5      lazyeval_0.2.0    bold_0.5.0        crul_0.4.0        crayon_1.3.4      ape_5.0          
[43] pkgconfig_2.0.1   data.table_1.10.4 xml2_1.1.1        lubridate_1.7.2   iterators_1.0.8   assertthat_0.2.0 
[49] reshape_0.8.7     httr_1.3.1        rstudioapi_0.7    R6_2.2.2          nlme_3.1-131      compiler_3.4.3   
> 
```
</details>

Using the IUCN datasource (81) results in a blank table. The same occurs when using ```preferred_data_sources```, and when the key is specified by ```options(iucn_redlist_key="KEYHERE")``` rather than in the function. Specifying the datasource works correctly for e.g. ```1```, the Catalogue of Life.

The API key used works when using the ```rredlist``` package so I assume it is valid.

```
resolved_names_test <- gnr_resolve(names = "Manis javanica", data_source_ids = '81', key = "HIDDEN", verbose = TRUE)

* Connection 1 seems to be dead!
* Closing connection 1
* timeout on name lookup is not supported
*   Trying 128.174.81.103...
* TCP_NODELAY set
* Connected to resolver.globalnames.org (128.174.81.103) port 80 (#2)
> GET /name_resolvers.json?names=Manis%20javanica&data_source_ids=81 HTTP/1.1
Host: resolver.globalnames.org
User-Agent: libcurl/7.54.1 r-curl/2.8.1 crul/0.4.0
Accept-Encoding: gzip, deflate
Accept: application/json, text/xml, application/xml, */*

< HTTP/1.1 200 OK
< Server: nginx/1.13.0
< Date: Fri, 16 Mar 2018 09:41:31 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-UA-Compatible: IE=Edge,chrome=1
< ETag: W/"4b1ed5b9f8f642414bbf9f8121e55091"
< Cache-Control: max-age=0, private, must-revalidate
< X-Request-Id: 0d50d4a5cbd9c207f3d6d8d89914b03a
< X-Runtime: 0.249408
< X-Rack-Cache: miss
< Access-Control-Allow-Origin: *
< Content-Encoding: gzip
< 
* Connection #2 to host resolver.globalnames.org left intact
```

**Comment by sckott** [comment]
thx for opening the issue @git-og !

> Using the IUCN datasource (81) results in a blank table. 

What do you mean by a blank table? And what is 81 referring to?

> The same occurs when using preferred_data_sources, and when the key is specified by options(iucn_redlist_key="KEYHERE") rather than in the function. Specifying the datasource works correctly for e.g. 1, the Catalogue of Life.

The same as what?

It's unclear what function you're talking about. Is this question about `gnr_resolve`? or some other function?

**Comment by git-og** [comment]
Sorry to be unclear - the full replicable code is in the code chunk below
the text in the original post, along with the verbose output. Yes, this is
in about gnr_resolve().

81 is the data source ID for the IUCN as listed by the gnr_datasources()
function.

In my case the blank table is a 0x0 tibble as I use the tidyverse packages.
By "the same occurs" I mean no results are returned in any of those
differing situations.


On 17 Mar 2018 00:52, "Scott Chamberlain" <notifications@github.com> wrote:

thx for opening the issue @git-og <https://github.com/git-og> !

Using the IUCN datasource (81) results in a blank table.

What do you mean by a blank table? And what is 81 referring to?

The same occurs when using preferred_data_sources, and when the key is
specified by options(iucn_redlist_key="KEYHERE") rather than in the
function. Specifying the datasource works correctly for e.g. 1, the
Catalogue of Life.

The same as what?

It's unclear what function you're talking about. Is this question about
gnr_resolve? or some other function?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ropensci/taxize/issues/669#issuecomment-373794140>, or mute
the thread

**Comment by sckott** [comment]
thanks @git-og 

looks like you were using the row number instead of the data source number itself. 

```r
gnr_datasources()[81,]
#>     id                               title
#> 81 163 IUCN Red List of Threatened Species
```

so the `id` number is the thing you want, not the row number. 

if we use `163` i think we get what you want?

```r
gnr_resolve(names = "Manis javanica", data_source_ids = 163, verbose = TRUE)
#> # A tibble: 1 x 5
#>   user_supplied_name submitted_name matched_name     data_source_title    score
#> * <chr>              <chr>          <chr>            <chr>                <dbl>
#> 1 Manis javanica     Manis javanica Manis javanica … IUCN Red List of Th… 0.988
```

**Comment by git-og** [comment]
You're right! Embarrassing. ....! Thanks for the help, and thanks for a
great tool.

**Comment by sckott** [comment]
glad it works!
