### ISSUE TITLE
Batch downloads in `classification`

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#678]
Hi @sckott, 

I was looking through the code for the `classification` functions to see if it would be  any slower to pass values to them one at a time (to make a progress bar work), and I noticed that all seem to query databases one ID at a time, like so: 

https://github.com/ropensci/taxize/blob/d23f2324a8d71806178a2ab55d4c4b73452aab89/R/classification.R#L296-L314

So it would not be slower to call `classification` once for each ID, which is convenient for adding progress bars in the `taxa` parsers, but I wonder if  `classification` could be faster if it made queries in batches?

Do you know how many of the databases' APIs support multiple IDs per query? Is this something worth looking into? Thanks

**Comment by sckott** [comment]
🤔 maybe. 

(the fastest thing may be to use `taxizedb` - but that's only for certain data sources - and requires setup locally which may not work on all machines - and we're still trying to work out differences between `taxize` and `taxizedb` for ncbi at least)

back to the issue at hand: (🚫 no  ----  ✔️ yes)

- bold: 🚫 
- col: 🚫 
- gbif: 🚫 
- eol:  🚫 
- iucn:  🚫 
- natserv: ✔️ 
- nbn: 🚫 
- tol: 🚫 (the `rotl` fxn that we use allows many ids, but internally it's just an `lapply` call over them)
- tropicos: 🚫 
- itis: 🚫 
- ncbi: ✔️ 
- wikipedia: (not sure, possibly, not super familiar with wikipedia api's - althoug this source probaby isn't used much anyway i'd imagine)
- worms:  🚫

**Comment by zachary-foster** [comment]
Thanks for all that info! Ahh yes, I always forget about taxizedb. I have not used it, but I should look into it. Maybe there is some potential for adding a database option like "taxizedb-ncbi" to the taxa parsers that will look for a current install of taxizedb and use that. 

I am surprised so many DBs dont allow for multiple queries. Oh well. Would you be interested in a PR to allow batch downloads for NCBI if I get around to it? It would probably have to change the current messages that are printed by `classification`

**Comment by sckott** [comment]
> Would you be interested in a PR to allow batch downloads for NCBI if I get around to it?

Yeah, sounds good

**Comment by sckott** [comment]
should I close this issue @zachary-foster or do you think you'll get around to this soon?

**Comment by zachary-foster** [comment]
Hi @sckott, oh yea, I forgot about this. I will look into it today and get back to you.

**Comment by sckott** [comment]
thx
