### ISSUE TITLE
Specify and API key for ncbi

### ISSUE THREAD

**Issue by DarrenObbard** [ropensci/taxize#681]
Hi,

How do I specify my API key for ncbi? 

tax_name(query = "Abalone herpesvirus Victoria/AUS/2009", get = "species", db = "ncbi")

I cannot find this in the manual, and when I try specifying it with key="<mykeystring>" I still get the error that no key was provided.

<details> <summary><strong>Session Info</strong></summary>

```r
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] taxize_0.9.3.9213

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      codetools_0.2-15  lattice_0.20-35   ape_5.1
 [5] zoo_1.8-1         reshape_0.8.7     foreach_1.4.4     grid_3.4.3
 [9] crul_0.5.2        R6_2.2.2          plyr_1.8.4        jsonlite_1.5
[13] nlme_3.1-131      magrittr_1.5      httr_1.3.1        stringi_1.1.7
[17] reshape2_1.4.3    curl_3.2          data.table_1.11.2 xml2_1.2.0
[21] urltools_1.7.0    iterators_1.0.9   tools_3.4.3       stringr_1.3.0
[25] bold_0.5.0        triebeard_0.3.0   parallel_3.4.3    compiler_3.4.3

```
</details>

**Comment by sckott** [comment]
thanks for your question @DarrenObbard 

see `?taxize-authentication` for help on authentication. Since there can sometimes be many layers of function calls, e.g., `tax_name` with ncbi data source calls `get_uid` and `classification` under the hood, so I think you'll find it easier in the end if you set your NCBI key as an environment variable that's set permanently. The `?taxize-authentication` manual file has help on how to do that. Let me know if that works. Make sure to restart your R session after setting your NCBI env var so that R knows about it

**Comment by DarrenObbard** [comment]
Thanks, I now have it working. Can I make some suggestions for the help? First, the fact that ?"taxize-authentication" takes you to a function called getKey() is confusing, since the purpose of getKey() is not explained. This part of the manual (which I'd already found) contains the information, but it seems to be suggesting that this use is in the context of getKey() - which was a function I had no interest in, since I was happy to specify it at each time of use. Second, both ?getKey and your answer above suggest that 'I might find it easier' or 'strongly recommend' to do it this way, but neither actually answers the question I had, which was "how do I set the key for a particular function?". The manual should say "Because there are many layers of function calls you must set the key as an environment variable" rather than implying it's optional and that there is another route. Finally, it would be helpful to tell people how to set an environment variable. For anyone else struggling with this, environment variables set in .bash_profile etc need an 'export ' , e.g. "export ENTREZ_KEY="

**Comment by paternogbc** [comment]
I had the exact same problem. Thanks!

**Comment by andzandz11** [comment]
I had the same problem. I cannot supply via function call although the manual suggets it is possible.

**Comment by sckott** [comment]
>  I cannot supply via function call although the manual suggets it is possible.

where does it say this? to what function?
