### ISSUE TITLE
tnrs() ; calling specific iPlant database?

### ISSUE THREAD

**Issue by toczydlowski** [ropensci/taxize#684]
Hello,

I am using tnrs() to match and standardize species names across vegetation surveys, trait databases, phylogenetic trees, etc.  I am calling iPlant as the source, but iPlant itself calls multiple databases.  Is there a way to specify one of the iPlant databases (e.g. USDA) or rank the preference of the databases that iPlant uses?  

If you run iPlant interactively online, you can rank the order of the databases.  Is there a way when running tnrs() to add an argument that ranks the databases within iPlant (if there is not a way to call one specifically)?  The USDA database seems to be the most accurate for this work of the databases that iPlant calls, but Tropicos is by default first in iPlant, so we get mainly Tropicos hits.

Thanks - Rachel

**Comment by sckott** [comment]
thanks for your question @toczydlowski !

Are you looking just for an iplant TNRS interface? If so, we do have a `iplant_resolve` function. Or is `tnrs` the function you definitely want?

**Comment by toczydlowski** [comment]
I think we need tnrs.  We want non-interactive, reproducible, handling of mis-spellings, and a final table that has the original submitted name, the final name (and if it is accepted or not), and the source that the final name came from.  Does that help to clarify?

**Comment by sckott** [comment]
Sort of. There's a variety of data sources. The `tnrs` function uses the service at http://www.taxosaurus.org/ and `iplant_resolve` uses http://tnrs.iplantcollaborative.org/ - Does either one work for you?

**Comment by toczydlowski** [comment]
No, neither currently works for us.  We need to be able to specify a specific database **within** iPlant (preferably from `tnrs` as opposed to `iplant_resolve`).  If you use iPlant from the online interface, you will see you can rank the 6 databases that iPlant draws on.  The default top ranked database online and in `tnrs` is Tropicos, so `tnrs`returns almost all Tropicos names.  We want `tnrs` to return the USDA names instead.  This can be accomplished using iPlant online (by changing the rank order so USDA is above Tropicos).  We want to do the same thing through R (preferably using `tnrs`).

**Comment by toczydlowski** [comment]
![screen shot 2018-06-06 at 5 17 06 pm](https://user-images.githubusercontent.com/23200404/41068089-a3eaa3b8-69ad-11e8-97f8-33bfaa0f74a6.png)

**Comment by sckott** [comment]
thanks for the clarifiation. 

Neither `tnrs` nor `iplant_resolve` allow setting the iplant data source to use. It's not this package - but rather the API's we use from tnrs and iplant projects don't allow it. 

Another approach is using global names via `taxize::gnr_resolve`, e.g. USA is data source id 150 in global names

```r
gnr_resolve(names = c("Helianthus annuus", "Poa annua"), data_source_ids=150)
# A tibble: 2 x 5
  user_supplied_name submitted_name    matched_name         data_source_title         score
* <chr>              <chr>             <chr>                <chr>                     <dbl>
1 Helianthus annuus  Helianthus annuus Helianthus annuus L. USDA NRCS PLANTS Database 0.988
2 Poa annua          Poa annua         Poa annua L.         USDA NRCS PLANTS Database 0.988
```

------

p.s. i also maintain an API for USDA plants database https://github.com/sckott/usdaplantsapi but it's from a dump of their data from a few years back

**Comment by toczydlowski** [comment]
Ahhh.  Ok.  Thanks for the scoop.  I'll try the `gnr_resolve` option.  Does iPlant online returning more results than `iplant_resolve` also have to do with the API issue (screen shots above)?

**Comment by sckott** [comment]
I think so.  @ojalaquellueva I can't remember, does the iplant website not use the API? see comment above https://github.com/ropensci/taxize/issues/684#issuecomment-395232190

I think it doesn't

**Comment by ojalaquellueva** [comment]
Unfortunately the TNRS API has only a subset of the functionality of the online UI. You cannot specify a particular database and it does not allow you to reorder the sources. Basically the API was tacked onto the UI as an afterthought, an unfortunate blunder in my opinion. IPlant should have built a full-featured API first, then built the UI on top of it. On the positive side, I've begun working with iPlant/Cyverse to build a new API which will have all the bells and whistles. Development has slowed down over the summer, but I'm hoping we can have something ready before the end of the year.

**Comment by toczydlowski** [comment]
Thanks for the update!  That's helpful info, and glad to hear a fully functional API is in the works.  Onwards.

**Comment by sckott** [comment]
closing for now
