### ISSUE TITLE
synonyms() function row error

### ISSUE THREAD

**Issue by pederengelstad** [ropensci/taxize#685]
I'm encountering this error running the synonyms() function on certain TSNs from ITIS. Was curious if this was a known issue.

```r
synonyms(184247, db = 'itis', ask=T)
Accepted name(s) is/are 'Amaranthus albus/Amaranthus blitoides'
Using tsn(s) 20719/20723

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 2, 5
```

<details> <summary><strong>
</strong></summary>

Session info --------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, mingw32             
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Denver              
 date     2018-06-06                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                         
 taxize     * 0.9.3      2018-03-20 CRAN (R 3.4.4)
</details>

**Comment by sckott** [comment]
thanks for this issue @pederengelstad having a look

**Comment by sckott** [comment]
@pederengelstad can you try again after reinstalling from github `remotes::install_github("ropensci/taxize")`

**Comment by pederengelstad** [comment]
Gave it a run. The data looks good but any of the autocompletes in taxize are now generating another error:

Error in fetch(key) : 
  lazy-load database '~/win-library/3.4/taxize/help/taxize.rdb' is corrupt

Tried deleting and reinstalling github version but the error persisted.

**Comment by sckott** [comment]
Try restarting the R session

**Comment by pederengelstad** [comment]
Ah yes, thank you. Everything looks good on my end. Much appreciated!
