### ISSUE TITLE
tax_name() rows argument

### ISSUE THREAD

**Issue by eregenyi** [ropensci/taxize#686]
Hi all!

I am trying to retrieve taxonomic information for a set of bacterial genera, using tax_name(). "Bacillus" occurs quite frequently, and it returns 2 hits, of which the second is the bacteria, I want. 

When trying to automate retrieval using the rows = 2 argument, I am still being queried, which requires me to stick around while the code is running.

Did someone have the same issue? How could I solve it? 

The code I am trying to run is just:

`tax_name("Bacillus", c("family", "order"), db = "ncbi" ,rows = 2)`

Thank you for your help! Awesome package by the way, super helpful!

**Comment by sckott** [comment]
@eregenyi thx for the report!  install from github and try again `remotes::install_github("ropensci/taxize")`
