### ISSUE TITLE
Easier setup?

### ISSUE THREAD

**Issue by maelle** [ropensci/taxize#691]
I've had a look at https://ropensci.github.io/taxize-book/authentication.html 

I'd like to offer to write functions for these packages à la `usethis` that would

* browse to the webpage where one needs to register (mostly because I am lazy and don't like to copy-paste URLs 👼 )

* print to screen instructions about where to store the key (and mentioning `usethis::edit_r_environ`).

Would you package authors be interested in that? I'm opening the issue here but my PRs would be to the different packages, and then to the `taxize` book.

**Comment by sckott** [comment]
👋 thanks for this. Yeah, would be nice to have some helper to go to where to get a key, and info on how to store it.
