### ISSUE TITLE
Suggestions for the taxize suite

### ISSUE THREAD

**Issue by maelle** [ropensci/taxize#697]
# Add a note about taxize in the packages it imports

I.e. similarly to the note about `spocc` in `rebird` docs, have a note about `taxize` in the docs of `rredlist` and co? In the README and vignette probably (since the README isn't accessible locally)? The note could also say what functionality of `rredlist` for instance are not available in `taxize`, if relevant.

# Add the "taxize" repo topic to all ropensci repos related to `taxize`?

Similarly to what's now done with "spocc". https://github.com/search?q=topic%3Aspocc+org%3Aropensci+fork%3Atrue (whereas currently the "taxize" topic has been used more specifically https://github.com/search?q=topic%3Ataxize+org%3Aropensci+fork%3Atrue )

**Comment by sckott** [comment]
1. would it be easier to just have a section in the taxize book about this? or do you think should also be in readmes/vignettes?
2. good point. ✔️ we should do that

**Comment by maelle** [comment]
> would it be easier to just have a section in the taxize book about this? or do you think should also be in readmes/vignettes?
yes, well at least a link to the book should be in all relevant READMEs/vignettes. 😉 

> good point. ✔️ we should do that
Should it go on my or your to-do list? 😸

**Comment by sckott** [comment]
I can do the topics

**Comment by sckott** [comment]
i think this is done now
