### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by maelle** [ropensci/taxize#703]
Does `taxize` implement any rate limiting?

I see that it does for `get_uid` when there is no ENTREZ API key (https://github.com/ropensci/taxize/blob/d23f2324a8d71806178a2ab55d4c4b73452aab89/R/get_uid.R#L183) but I don't see it does when there is one?

And what about `classification` for `uid` objects for instance? I'm unsure whether I have to implement rate limiting myself, and if I do, where to find the rate. Thanks in advance!

**Comment by maelle** [comment]
No I wanted to prevent that and present best practice in my post 😇 so the answer is that it's all handled by the API / package, right? For this workflow using 2 functions only

**Comment by sckott** [comment]
Yes, it should all be handled by the package, but I can't say for sure, there's always edge cases as you. know

**Comment by maelle** [comment]
Ok will close this if I don't encounter any

**Comment by maelle** [comment]
It worked perfectly, thanks!


```r
ids <- taxize::get_uid(unique(ebd$scientific_name))
classif <- taxize::classification(ids)
```

There were 212 species.
