### ISSUE TITLE
col_downstream - remove extinct species

### ISSUE THREAD

**Issue by ArielGreiner** [ropensci/taxize#714]
I want to use col_downstream to determine the # of extant orders/family/genera within a few specific classes - is there a way that I can tell col_downstream that I want to restrict the results to extant species? I've noticed that it gives extinct taxa as well.

Is there another function that you can suggest? Or another way to get at the information I'm after? I'm interested in knowing this information for Aves, Actinopterygii, Mammalia and Insecta.

**Comment by sckott** [comment]
thanks for your question @ArielGreiner 

can you give me some example queries that lead to results with extinct species and/or examples of extinct species 

For COL we are pretty limited in our options. They provide very little user inputs to query on, so we're mostly stuck with filtering on data that's returned. I can look into this more once you get back with some examples

**Comment by ArielGreiner** [comment]
For example: col_downstream(name = "Insecta", downto = "order") shows 44 orders but when I access the catalogue of life database online (http://www.catalogueoflife.org/col/browse/tree?cd4c8e371d3bfcc97dbe0b94fe9e3507) and turn off 'extinct species' I only see 28 orders. I looked up some of the extra orders and they were listed as being extinct. 

I was assuming since there is an option on the website version of the database to turn extinct species on/off that they've encoded which species are and are not extinct in the database that taxize is accessing?

**Comment by sckott** [comment]
thanks, i'll have a look at that example. 

> I was assuming since there is an option on the website version of the database to turn extinct species on/off that they've encoded which species are and are not extinct in the database that taxize is accessing?

not necessarily so, but I do see that extinction status is in the results now - not sure if it was always there or not ...

**Comment by ArielGreiner** [comment]
@sckott Thank you! That worked :) Much appreciated!

**Comment by sckott** [comment]
@ArielGreiner glad it works
