### ISSUE TITLE
Error using downstream to get bacterial species

### ISSUE THREAD

**Issue by fischhoff** [ropensci/taxize#727]
Hello! Thank you for creating this package. I'm running into an issue getting bacterial species with downstream. I get results when I use downstream to access "phyla" (and "order" and "family"), but not with "species". I've looked at related issues but didn't see a solution in one of those. 
 
<details> <summary><strong>Session Info</strong></summary>
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.9.4.9914

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        pillar_1.2.2      bindr_0.1.1       compiler_3.4.4   
 [5] git2r_0.23.0      plyr_1.8.4        ritis_0.7.2       iterators_1.0.9  
 [9] tools_3.4.4       digest_0.6.18     tibble_1.4.2      jsonlite_1.6     
[13] memoise_1.1.0     nlme_3.1-137      lattice_0.20-35   pkgconfig_2.0.2  
[17] rlang_0.3.1       foreach_1.4.4     crul_0.6.0        curl_3.2         
[21] yaml_2.2.0        parallel_3.4.4    xfun_0.4          bindrcpp_0.2.2   
[25] withr_2.1.2       httr_1.4.0        stringr_1.3.1     dplyr_0.7.8      
[29] knitr_1.21.6      xml2_1.2.0        devtools_1.13.6   tidyselect_0.2.5 
[33] triebeard_0.3.0   grid_3.4.4        glue_1.3.0        reshape_0.8.8    
[37] httpcode_0.2.0    data.table_1.11.8 R6_2.3.0          solrium_1.0.0    
[41] purrr_0.2.5       reshape2_1.4.3    magrittr_1.5      urltools_1.7.1   
[45] codetools_0.2-15  assertthat_0.2.0  bold_0.8.0        ape_5.2          
[49] stringi_1.2.4     zoo_1.8-4  
</details>

```r
devtools::install_github("ropensci/taxize")
library(taxize)

> phylum = downstream(2, db = "ncbi", downto = "phylum")
> print(phylum)
$`2`
   childtaxa_id        childtaxa_name   rank
1        508458         Synergistetes phylum
2        203691          Spirochaetes phylum
3        200940 Thermodesulfobacteria phylum
4        200938        Chrysiogenetes phylum
5        200930       Deferribacteres phylum
6        200918           Thermotogae phylum
7        200783             Aquificae phylum
8         74152         Elusimicrobia phylum
9         68297           Dictyoglomi phylum
10        57723         Acidobacteria phylum
11        40117           Nitrospirae phylum
12        32066          Fusobacteria phylum
13         1224        Proteobacteria phylum

attr(,"class")
[1] "downstream"
attr(,"db")
[1] "ncbi"
> species = downstream(2, db = "ncbi", downto = "species")
Error in data.table::rbindlist(x, use.names = TRUE, fill = TRUE, idcol = TRUE) : 
  Item 1 of list input is not a data.frame, data.table or list
In addition: Warning message:
In ncbi_get_taxon_summary(children_uid, key = key, ...) :
  query failed, proceeding to next if there is one
```

**Comment by sckott** [comment]
thanks for the report @fischhoff - i hope you don't mind I edited your issue just to collapse the session info to be able to focus on your question, and I put the code in an R code block

looking at it now

**Comment by sckott** [comment]
Drilling down, sorting out a few things, but still not fixed yet. Will let you know when this is fixed. 

In the meantime, do you know about `taxizedb`? It's probably a better fit for queries like these that go so far down the taxonomic tree, e.g., 

```r
library(taxizedb)
x <- downstream(2, db = "ncbi", downto = "species")
NROW(x[[1]])
#> [1] 97559

head(x[[1]])
#>   childtaxa_id                        childtaxa_name    rank
#> 1      2170428              Vulcanococcus limneticus species
#> 2      2164156     Rhodothermaeota bacterium MED-G64 species
#> 3      2163959     Candidatus Carbobacillus altaicus species
#> 4      2162616 Acidimicrobiales bacterium AG-414-N20 species
#> 5      2162615 Acidimicrobiales bacterium AG-410-K21 species
#> 6      2162614 Acidimicrobiales bacterium AG-410-I20 species
```

took only about 30 seconds or so

**Comment by fischhoff** [comment]
Hi @sckott Thanks for proposing this solution! This worked. 
I had actually tried to use taxizedb before but with "Bacteria". 
b <- downstream("Bacteria", db = "ncbi", downto="species", out_type = "summary")
 Error in name2taxid(x[is_named], db = "ncbi") : 
Some of the input names are ambiguous, try setting out_type to 'summary'
 
Using the taxid (bacteria = 2) worked, though!

**Comment by sckott** [comment]
glad it worked, and thanks for the bug report on `taxizedb`. i'll open an issue over there.

**Comment by arendsee** [comment]
@fischhoff FYI, the reason `taxizedb` is complaining about "Bacteria" is because the name actually is ambiguous. "Bacteria" is also the name of a genus of walking sticks.

```R
> taxizedb::name2taxid("Bacteria", out_type="summary")
# A tibble: 2 x 2
  name_txt tax_id
  <chr>    <chr>
1 Bacteria 2     
2 Bacteria 62939
```

**Comment by fischhoff** [comment]
Thanks for the explanation, @arendsee! There must have been a reason to call walking sticks "Bacteria", but it seems a confusing choice!

**Comment by arendsee** [comment]
@fischhoff, it looks like the walking stick may have had the name first, actually. The Bacteria genus was named in [1825](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=629395&lvl=3&lin=f&keep=1&srchmode=1&unlock). The word for the microbes was coined in [1847](https://www.etymonline.com/word/bacteria).

**Comment by fischhoff** [comment]
@arendsee Cool!  And the etymology (Latin/Green for rod/stick) fits both. https://www.etymonline.com/word/bacteria

**Comment by arendsee** [comment]
@fischhoff Yeah, good point.

**Comment by sckott** [comment]
@fischhoff should be working now
