### ISSUE TITLE
`classification()`: allow for exact matches of taxon name

### ISSUE THREAD

**Issue by ahhurlbert** [ropensci/taxize#734]
I use `classification` in bulk name cleaning, and would like to minimize the interactive feature as much as possible. Currently, let's say I search for 'Melospiza' from ITIS:
```
> classification('Melospiza', db = 'itis')

Retrieving data for taxon 'Melospiza'

      tsn                         target                                            commonNames nameUsage
1   55548     Leucochloridium melospizae                                                     NA     valid
2  179483                      Melospiza                                          Song Sparrows     valid
3  179488            Melospiza georgiana      Gorrión pantanero,Swamp Sparrow,bruant des marais     valid
4  179489  Melospiza georgiana ericrypta           Northern Swamp Sparrow,Western Swamp Sparrow     valid
5  179490  Melospiza georgiana georgiana                                 Southern Swamp Sparrow     valid
6  179491 Melospiza georgiana nigrescens                            Coastal Plain Swamp Sparrow   invalid
7  179484            Melospiza lincolnii Gorrión de Lincoln,Lincoln's Sparrow,bruant de Lincoln     valid
8  179486   Melospiza lincolnii alticola                                                     NA     valid
...
More than one TSN found for taxon 'Melospiza'!
```

In this case, an interactive session opens because of uncertainty in whether I meant another taxon entirely that happened to have the string 'melospiza' in its name, the genus itself, or any number of species or subspecies in the genus. This interactive session would be completely unnecessary if I were able to say, for example, exact = TRUE, in which case it would only return the second record without need for my input.

Does this kind of functionality already exist somehow (for `classification`)?

**Comment by sckott** [comment]
thanks @ahhurlbert 

see also related issue https://github.com/ropensci/taxize/issues/631

**Comment by sckott** [comment]
@ahhurlbert try again after reinstall `remotes::install_github("ropensci/taxize")`, and reloading sesssion

now I get 

```r
classification('Melospiza', db = 'itis')
#> $Melospiza
#>             name         rank     id
#> 1       Animalia      kingdom 202423
#> 2      Bilateria   subkingdom 914154
#> 3  Deuterostomia infrakingdom 914156
#> 4       Chordata       phylum 158852
#> 5     Vertebrata    subphylum 331030
#> 6  Gnathostomata  infraphylum 914179
#> 7      Tetrapoda   superclass 914181
#> 8           Aves        class 174371
#> 9  Passeriformes        order 178265
#> 10   Emberizidae       family 178838
#> 11     Melospiza        genus 179483
#> 
#> attr(,"class")
#> [1] "classification"
#> attr(,"db")
#> [1] "itis"
```

the actual changes were in the `get_*` functions which do that name negotiation

**Comment by ahhurlbert** [comment]
Thank you! This seems to have resolved the problem as expected for *most* of the names I've checked (several dozen), but two that still have the original problem are 'Columba' and 'Heterodon'.

**Comment by sckott** [comment]
thanks, will look

**Comment by sckott** [comment]
Looks like `get_tsn('Columba', accepted=TRUE)` and `get_tsn('Heterodon', accepted=TRUE)` work

**Comment by sckott** [comment]
both of those egs have a valid and invalid entry for each name

**Comment by ahhurlbert** [comment]
Great! `classification('Columba', db = 'itis', accepted = TRUE)` works perfectly! Thanks

**Comment by sckott** [comment]
note that not all `get_*` fxns have the same parameters though. e.g., `accepted` is in some but not others, but as long as you are just using itis, then you're good
