### ISSUE TITLE
update The Reptile Database

### ISSUE THREAD

**Issue by bienflorencia** [ropensci/taxize#737]
```r
# The db "The Reptile Database" is out of date, a new and updated version can be found in http://www.reptile-database.org/data/
```

**Comment by sckott** [comment]
Can you clarify? We don't include that database in this package.

**Comment by bienflorencia** [comment]
I did put it a little confussing, sorry for that. My first issue report and maybe is something I got wrong.

When running gnr_datasources() the id number 173 is The Reptile Database. When checking some names, I was getting different results from what was in the website of The Reptile Database. I checked the link "https://resolver.globalnames.org/data_sources.json" of the fuction gnr_datasources() and the website for the base seems to have been last updated in 2014 when the most recent is from Nov 2018.

**Comment by sckott** [comment]
thanks for the clarification. 

Global Names Resolver does indeed have older version of data than are available directly from the data sources. The trade off is that you get data from many sources through GNR, but they are not always up to date. 

I will add more to the documentation for this fxn about age of data to make it clear

**Comment by bienflorencia** [comment]
Yes, GNR is good to check for alternatives. Sadly, they don't retrieve the newest versions of the sources.
Indeed, it may be useful you could include that in the documentation.
Thanks for your time! (and patience)
