### ISSUE TITLE
cannot install in windows

### ISSUE THREAD

**Issue by binkySallly** [ropensci/taxize#747]
Hello,

  I can't install taxize in wondows. Three of the dependencies are not binary:

Des versions binaires sont disponibles mais les versions des sources sont plus récentes:
         binary source needs_compilation
curl        2.5    3.3              TRUE
solrium   0.4.0  1.0.2             FALSE
jsonlite    1.4    1.6              TRUE
tibble    1.3.0  2.0.1              TRUE
crul      0.3.4  0.7.0             FALSE
xml2      1.1.1  1.2.0              TRUE
bold      0.4.0  0.8.6             FALSE
ritis     0.5.4  0.7.6             FALSE
taxize    0.8.4  0.9.6             FALSE

  Binaries will be installed
Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘utf8’ ‘fansi’
  ‘rlang’
  These will not be installed

Thank you,

Bianca

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.2

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by sckott** [comment]
thanks for your report @binkySallly 

R 3.2.2 is a very old version of R. Are you willing to upgrade R?  I think that would be a good idea. Then `taxize` installation should work good.

**Comment by binkySallly** [comment]
Thank you !!
:-)
