### ISSUE TITLE
eol: no api key with new api (unless Cypher)

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#749]
update docs in pkg to remove api key needed for EOL, check to make sure that's true

**Comment by jhammock** [comment]
Thanks, @sckott . If anyone is waiting for confirmation, it is true. No key is required for the APIs currently in use by taxize.

**Comment by sckott** [comment]
thanks @jhammock - but Cypher does require a key, correct?

**Comment by jhammock** [comment]
Yes, for the moment. If it is incorporated into taxize, instructions for cypher service access are [here](https://github.com/EOL/eol_website/blob/master/doc/api.md#getting-a-token).

**Comment by sckott** [comment]
cypher's not used here, but it is in the traits pkg
