### ISSUE TITLE
Natrix natrix, "col", Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :    CData section not finished

### ISSUE THREAD

**Issue by dougwyu** [ropensci/taxize#755]
Throws an error
`mismatch_natrix <- classification("Natrix natrix", db="col", return_id=FALSE, rows=1)`

```
Retrieving data for taxon 'Natrix natrix'

Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  CData section not finished
Kindler, C., Böhme, W., Corti, C., Gvozdik, V., J [63]
```

Doesn't throw an error
`mismatch_natrix <- classification("Natrix natrix", db="itis", return_id=FALSE, rows=1)`

**Comment by sckott** [comment]
please include session info as requested

**Comment by dougwyu** [comment]
R 3.6.0
taxize 0.9.7

other species that throw the same error:
`classification("Hemidactylus adensis", db="col", return_id=FALSE, rows=1)`
`classification("Hemidactylus awashensis", db="col", return_id=FALSE, rows=1)`

**Comment by sckott** [comment]
it's an issue with `xml2` - opened an issue there https://github.com/r-lib/xml2/issues/256

**Comment by dougwyu** [comment]
https://en.m.wiktionary.org/wiki/široký

**Comment by sckott** [comment]
@dougwyu reinstall, reload R, and try again, should work now

**Comment by dougwyu** [comment]
I installed the development version
`remotes::install_github("ropensci/taxize")`

and these work now:
`taxize::classification("Natrix natrix", db="col", return_id=FALSE, rows=1)`
`taxize::classification("Hemidactylus adensis", db="col", return_id=FALSE, rows=1)`
`taxize::classification("Hemidactylus awashensis", db="col", return_id=FALSE, rows=1)`  

thanks!
