### ISSUE TITLE
timeout with downstream() to ITIS

### ISSUE THREAD

**Issue by dougwyu** [ropensci/taxize#759]
When I run the following, i get a timeout error.  

`taxon_list<-downstream(get_tsn("Tetrapoda"),db="itis",downto="species")`

> Retrieving data for taxon 'Tetrapoda'
> 
> Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
>   Failed to connect to www.itis.gov port 443: Operation timed out

`get_tsn("Tetrapoda")` works fine

<details> <summary><strong>Session Info</strong></summary>

```r
> R version 3.6.0 (2019-04-26)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.5
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] taxize_0.9.7
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1        rstudioapi_0.10   xml2_1.2.0        magrittr_1.5      tidyselect_0.2.5 
>  [6] ape_5.3           lattice_0.20-38   R6_2.4.0          rlang_0.3.4       foreach_1.4.4    
> [11] stringr_1.4.0     plyr_1.8.4        dplyr_0.8.1       tools_3.6.0       parallel_3.6.0   
> [16] bold_0.8.6        grid_3.6.0        solrium_1.0.2     data.table_1.12.2 nlme_3.1-140     
> [21] iterators_1.0.10  assertthat_0.2.1  tibble_2.1.1      httpcode_0.2.0    crayon_1.3.4     
> [26] purrr_0.3.2       reshape2_1.4.3    codetools_0.2-16  triebeard_0.3.0   curl_3.3         
> [31] crul_0.7.4        glue_1.3.1        stringi_1.4.3     pillar_1.4.0      compiler_3.6.0   
> [36] urltools_1.7.3    ritis_0.7.6       jsonlite_1.6      reshape_0.8.8     pkgconfig_2.0.2  
> [41] zoo_1.8-5        
```

</details>

**Comment by sckott** [comment]
thanks, checking. note that this should take a long time since it's coming from a high taxon, so likely that there was just a random timeout given lots and lots of requests

**Comment by sckott** [comment]
one option is to try `taxizedb::downstream`, but your only option there is ncbi

**Comment by sckott** [comment]
I could not replicate your problem. I expect that it was just an intermittent problem on the ITIS end of things.

**Comment by dougwyu** [comment]
hmm, i've replicated this multiple times.  it might be that i'm in the UK. i'll try on other systems

**Comment by sckott** [comment]
next time it errors run `traceback()` after the error so we can see where the error is coming from

**Comment by dougwyu** [comment]
it worked!  it just needs to have a fast internet connection, and even then, it took 8 hours

**Comment by sckott** [comment]
if you are okay with ncbi data, give taxizeb a try, its much faster.
