### ISSUE TITLE
`synonyms` return type for COL when no synonyms found

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxize#763]
Hi @sckott, I was using the `synonyms` function for my research (very useful by the way) and noticed some odd behavior when using COL as the db:

```
> synonyms(c("Aphanomyces euteiches"), db="col")
$`Aphanomyces euteiches`
$`Aphanomyces euteiches`$rank
character(0)


attr(,"class")
[1] "synonyms"
attr(,"db")
[1] "col"
```

It returns a list with an empty `rank`, instead of `NA` or `list()` like the other databases. 
I fixed it in my local version of `taxize` (cloned today), so that it returns `NA`, but is that the right output if the the query is found but there are no synonyms? Some DBs return `list()` and most `NA`:

```
> synonyms('Aphanomyces euteiches', db = 'tropicos')
══  1 queries  ═══════════════

Retrieving data for taxon 'Aphanomyces euteiches'

Using default key: Please get your own API key via taxize::use_tropicos()
Not found. Consider checking the spelling or alternate classification
✖  Not Found:  Aphanomyces euteiches
══  Results  ═════════════════

● Total: 1 
● Found: 0 
● Not Found: 1
$`Aphanomyces euteiches`
[1] NA

attr(,"class")
[1] "synonyms"
attr(,"db")
[1] "tropicos"
> synonyms('Aphanomyces euteiches', db = 'nbn')
══  1 queries  ═══════════════

Retrieving data for taxon 'Aphanomyces euteiches'

✔  Found:  Aphanomyces euteiches
══  Results  ═════════════════

● Total: 1 
● Found: 1 
● Not Found: 0
$`Aphanomyces euteiches`
list()

attr(,"class")
[1] "synonyms"
attr(,"db")
[1] "nbn"
```

Is `NA` is the intended result of no synonyms are found? Is `list()` for when the query is found but there is no synonyms, while `NA` is for when the query is not found? 

Interested in a PR to fix the COL issue? The problem is here, in case you want to fix it yourself:

https://github.com/ropensci/taxize/blob/ba158685e679131b0abf5b755af3f22f99902b1f/R/synonyms.R#L248

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxize_0.9.8.9124

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        compiler_3.6.0    pillar_1.4.1      plyr_1.8.4        ritis_0.7.6       iterators_1.0.10  tools_3.6.0      
 [8] zeallot_0.1.0     jsonlite_1.6      tibble_2.1.3      nlme_3.1-140      lattice_0.20-38   pkgconfig_2.0.2   rlang_0.3.99.9003
[15] foreach_1.4.4     cli_1.1.0         rstudioapi_0.10   crul_0.7.4        curl_3.3          yaml_2.2.0        parallel_3.6.0   
[22] stringr_1.4.0     dplyr_0.8.1       xml2_1.2.0        vctrs_0.1.0.9004  worrms_0.3.2      rredlist_0.5.0    tidyselect_0.2.5 
[29] triebeard_0.3.0   grid_3.6.0        reshape_0.8.8     glue_1.3.1        httpcode_0.2.0    data.table_1.12.2 R6_2.4.0         
[36] fansi_0.4.0       solrium_1.0.2     purrr_0.3.2       reshape2_1.4.3    magrittr_1.5      backports_1.1.4   urltools_1.7.3   
[43] codetools_0.2-16  assertthat_0.2.1  bold_0.8.6        ape_5.3           utf8_1.1.4        stringi_1.4.3     crayon_1.3.4     
[50] zoo_1.8-6      
```

**Comment by sckott** [comment]
thanks @zachary-foster 

Ideally the result from the fxn should be consistent (`NA`) across db options. So yeah, if you could send PR for that, that'd be great. 

> so that it returns NA, but is that the right output if the the query is found but there are no synonyms?

Not sure what you're asking here, can you clarify?

**Comment by zachary-foster** [comment]
Ok, I will send a PR. 

I mean in cases like:

```r
synonyms('Aphanomyces euteiches', db = 'nbn')
```

where 'Aphanomyces euteiches' exists in the database, but there are no synonyms, vs 

```r
synonyms('Not a name', db = 'nbn')
```
In my ideal world, in the first case, there would be a zero-length output in the format that is normally returned for things with synonyms, but in the latter case  `NA` would make sense. Users might want to treat each case differently, although they could use other functions in `taxize` to see if a taxon exists in a database first, so its not too important.  I don't know if you can differentiate between the two based on what all the database APIs return though.

**Comment by zachary-foster** [comment]
oops clicked wrong button

**Comment by sckott** [comment]
hmm, i see now. I think it's more important to return fewer different output types. So a data.frame for found synonyms, or if no synonyms, then NA. I think it makes more sense for users to first use a `get_*` fxn then pass to other fxns (synonyms, children, etc.) anyway, but i imagine most don't do that :) Maybe we could put in the attributes whether the taxon was not found OR was found but no synonymns OR was found and has synonyms

**Comment by zachary-foster** [comment]
> I think it's more important to return fewer different output types.

Yea, minimal output types is good. I was thinking same output type, but no length, so if the taxon is in the database but not found, it would return a data.frame with 0 rows and the same columns as when there are synonyms. A potential issue with this is that the API might not return information to indicate what column should be present if there are no synonyms and which columns each database will return might change over time so hard-coding the column names might be a maintenance hassle in the future. I like that it returns `NA` when the taxon is not found though. Either way, its a minor point, so whatever works.

> I think it makes more sense for users to first use a get_* fxn then pass to other fxns

Yea, people should be working with taxon IDs when possible to avoid this issue either way.


>  Maybe we could put in the attributes whether the taxon was not found OR was found but no synonymns OR was found and has synonyms

That would work fine as well

**Comment by sckott** [comment]
We're already not consistent it turns out. e.g, 

```r
synonyms("Pinus contorta", db="itis")
#> $`Pinus contorta`
#>   sub_tsn acc_tsn       message
#> 1  183327  183327 no syns found
```

So the name was found in ITIS, but no synonyms found. 

So maybe we should return zero row data.frames when the name is found, but no syn data found and NA when the name not found. 

Synonyms is kind of a mess since the data returned varies so widely, so hard to sort out a way to give common data fields back.

**Comment by zachary-foster** [comment]
Yea, I noticed that too when I was messing with different databases. To make them return the same columns would throw out a bunch of useful info for some databases.

**Comment by sckott** [comment]
okay, will fix this to be consistent

**Comment by sckott** [comment]
@zachary-foster  okay, outpus should be consistent now. 

- always NA for name not found
- always zero row data.frame w/o names when name found but no sysnonyms found

**Comment by zachary-foster** [comment]
Nice! That sounds good
