### ISSUE TITLE
get_id with multiple results: no prompt but return all rows with status and matchtype?

### ISSUE THREAD

**Issue by ocstringham** [ropensci/taxize#764]
I would like to obtain all rows in the get_*id function. For, example

`temp = get_gbifid(sciname = 'Ctenosaura palearis', ask = TRUE)` gives the prompt

> Retrieving data for taxon 'Ctenosaura palearis'
>
>
>
>
>
>More than one GBIF ID found for taxon 'Ctenosaura palearis'!
>
>            Enter rownumber of taxon (other inputs will return 'NA'):
>
>   gbifid                          scientificname    rank   status matchtype
>1 2459601     Ctenosaura palearis Stejneger, 1899 species ACCEPTED     EXACT
>2 7929575 Ctenosaura palearis Köhler Et Al., 2000 species  SYNONYM     EXACT
>1: 

And I must select one row and it only returns the one row I select. If I change ask to `ask = FALSE`, then it returns an `NA` because there is more than one result.

Is it possible to add an additional parameter that returns all results? And also include the `status` and `matchtype` for each result? That way I could loop through many species (1000s) and not have to rely on the prompt for each one that has more than one result.

**Comment by sckott** [comment]
thanks for your question @ocstringham 

have you tried the underscore methods? e.g., try `get_gbifid_(sciname = 'Ctenosaura palearis')`

**Comment by ocstringham** [comment]
Oh, that is excellent. Yes, that works perfectly. I was looking in the manual but didn't see the underscore function. Thanks @sckott :)

**Comment by sckott** [comment]
great, glad it works
