### ISSUE TITLE
GBIF grab the type of synonym (ie "heterotypic synonyms")

### ISSUE THREAD

**Issue by ocstringham** [ropensci/taxize#789]
It is possible to get the type of synonym supplied by GBIF using _taxize_? This is the field called "taxonomicStatus" provided by the GBIF API (see code below). In some cases, it reveals that the name is a heterotypic synonym and this is useful to me.

```r
library(httr)
library(jsonlite)

call1 = "http://api.gbif.org/v1/species/2467883/synonyms"
testget = GET(call1)

test_text = content(testget, "text")
test_text_json = fromJSON(test_text, flatten = TRUE)
testdf = as.data.frame(test_text_json$results, stringsAsFactors = FALSE)
testdf
```

**Comment by sckott** [comment]
thanks for your question @ocstringham 

i think this is what you want:

```r
x = name_usage(2467883, data = "synonyms")
x$data$taxonomicStatus
library(dplyr)
filter(x$data, taxonomicStatus == "HETEROTYPIC_SYNONYM")
```

does that do what you want?

**Comment by ocstringham** [comment]
Thanks @sckott - that works for me!

For anyone who wants the results of `*_name_usage` in a df use this code:

```r
library(taxize)
library(dplyr)
library(purrr)
library(tibble)
library(tidyr)

x = gbif_name_usage(2467883, data = "synonyms")

df = map(x$results, 
         function(y){
            y %>% 
              enframe() %>% 
              as_tibble() %>% 
              pivot_wider(names_from = name, values_from = value)
          } 
         ) %>% 
      bind_rows()
```

**Comment by sckott** [comment]
thanks @ocstringham  - I forgot to note that my eg above is using rgbif. `gbif_name_usage` is an out of date copy of `rgbif::name_usage` - so if you want functionality of `gbif_name_usage` probably best to use `rgbif::name_usage`
