### ISSUE TITLE
Object loaded on attach

### ISSUE THREAD

**Issue by kamapu** [ropensci/taxize#792]
I was experiencing some weird behavior in the package [`taxlist`](https://cran.r-project.org/package=taxlist) and realized, it is coming from `taxize` (I'm importing the function `tnrs()` into `taxlist`): Each time I load the package in an R-Session, the objects (data frames) **apg_families**, **apg_orders**, **rank_ref**, and **theplantlist** get automatically loaded in the workspace. The same happens either loading `taxlist` or `taxize` with the function `library()`.

**Comment by sckott** [comment]
they were added to onload recently https://github.com/ropensci/taxize/issues/777 so that one can call taxize functions that require those datasets without having to load the package first, e.g., `taxize::fxn()`

**Comment by kamapu** [comment]
OK, I found this behavior a bit annoying and not really desirable in `taxlist`. Is it there a way to suppress it in packages using `taxize` as dependency?

**Comment by sckott** [comment]
What problem is it causing? I don't see any datasets, objects, etc. in your pkg of the same name.

**Comment by kamapu** [comment]
It's not really a problem, but the objects appear once I load `taxlist` in an R-session using `library()`, just because `taxlist` depends on `taxize` (function `tnrs()` is imported in the package).

When I noticed the behavior, I spend days to find out, where those data are coming from, since it was not evident that they are not in the source of `taxlist`. On the other side, we use to work with such kind of data sets and therefore my first guess was that I have inserted those objects in the source of the package by mistake.

**Comment by kamapu** [comment]
I'm wondering if I can use `rm(apg_families, apg_orders, rank_ref, theplantlist)` in the function `.onAttach()` defined in **R/StartMessage.R** at the source of `taxlist`.

**Comment by sckott** [comment]
That sounds like a good solution.

**Comment by kamapu** [comment]
> I'm wondering if I can use `rm(apg_families, apg_orders, rank_ref, theplantlist)` in the function `.onAttach()` defined in **R/StartMessage.R** at the source of `taxlist`.

Unfortunately this solution didn't worked.

I know, it may sound too strict, but those objects are still disturbing me during some sessions, for instance when you work with one object but you have five in your workspace or when you name an object in a similar way and then confuse them...

An alternative could be to locate those data frames in an .RData file at **inst/extdata** at the package source.
Provided that the package is installed, the data could be accessed within a function's workspace by:

    load(file.path(find.package("taxize"), "extdata", "file.RData"))

**Comment by EDiLD** [comment]
> they were added to onload recently #777 so that one can call taxize functions that require those datasets without having to load the package first, e.g., `taxize::fxn()`

Would calling the datasets used in the functions with prefixed namespace, e.g. `taxize::rank_ref` fix the problem?

**Comment by sckott** [comment]
@EDiLD good idea, but that doesn't work.

**Comment by kamapu** [comment]
What about my suggestion?

**Comment by sckott** [comment]
I don't want to change the setup for loading the datasets

**Comment by kamapu** [comment]
WHAT!?

You say, I may have found the solution, but you just don't like to make any change?

Honestly, I don't get the logic of having every ones workspaces loading data, that are not needed because someone need it but does not like to load the package (???).

On the other side, I have never experienced this behavior in any package, especially because it is caused by a package that is not loaded in the session.

Anyway, I think, it is not fear...

**Comment by kamapu** [comment]
Here, another solution:
You could call the objects:
`.apg_families`,  `.apg_orders`, `.rank_ref`, and `.theplantlist`, and they won't be visible...

**Comment by kamapu** [comment]
Thanks, now I'm happy :)
