### ISSUE TITLE
remove COL

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#796]
the rate limiting is not worth dealing with

**Comment by andzandz11** [comment]
I have a bunch of scripts from early 2019 that completely build on CoL and are now kinda unusable. I can not find any information about the rate limit on the Col Webpage, they say that by end 2019 a new API should be in place. I am a little confused about the actual rate limit. Can you provide more information?

**Comment by sckott** [comment]
thanks for your question @andzandz11 

One of the problems that lead me to remove col functions was the lack of documentation - they do not have any documentation on the rate limits. If you wanted to use the old COL service, you could just use an older taxize version than the newest and put Sys.sleep calls in between subsequent COL requests, but I've no idea how long you need to wait between requests.  

COL+ is replacing COL - and we have an in development package at https://github.com/ropensci/colpluz - it's sort of useable - i will integrate it into taxize when it's more stable.
