### ISSUE TITLE
use_eol() unneeded now

### ISSUE THREAD

**Issue by padpadpadpad** [ropensci/taxize#803]
Hi

Once again thank you for the package.

Just thought I would highlight that the eol database does not need a token key anymore. I used `use_eol()` after trying to use `comm2sci('black brant', db = 'eol')`.

I could not find how to request a key so emailed and received a reply "That relies on our “Classic” APIs, which do not require a token".

Let me know how I can help if I can
Cheers
Dan

**Comment by sckott** [comment]
thanks for the report - see also #749

**Comment by sckott** [comment]
use_eol is now defunct, removed all requirement for a key for eol fxns
