### ISSUE TITLE
Downstream rank duplicates

### ISSUE THREAD

**Issue by sunray1** [ropensci/taxize#807]
Recently I've been trying to get taxonomic information for a variety of taxa and I've noticed that taxize gets 'stuck' and eventually times out when there are different downstream taxonomic ranks with the same names.

For example, using the family 'Pieridae':

```sh
$ sp_out <- downstream("Pieridae", downto = "species", db = "ncbi", ambiguous=FALSE)
```

will not run because there is a subgenus and a genus (the genus containing the subgenus) called "Euchloe". 

Running
```sh
$ sp_out <- downstream("Euchloe", downto = "species", db = "ncbi", ambiguous=FALSE)
```

returns 

```sh
$ More than one UID found for taxon 'Euchloe'!

            Enter rownumber of taxon (other inputs will return 'NA'):

  status     rank    division scientificname    commonname    uid genus
1 active subgenus butterflies        Euchloe               415320      
2 active    genus butterflies        Euchloe little whites  72254      
  species subsp modificationdate
1               2016/01/21 00:00
2               2017/06/14 00:00
```

Neither choice will work and eventually a time out occurs. All other ranks within 'Pieridae' seem to work with the 'downstream' command just fine.

Thanks!

**Comment by sckott** [comment]
thanks for your question @sunray1 

i can replicate the issue. I'll have a look

**Comment by sckott** [comment]
please try again after restarting R, then reinstalling like `remotes::install_github("ropensci/taxize")` 

ncbi was doing a weird thing where when searching on the two subgenera within _Euchloe_, it always returned the subgenera themsleves and the species below them, and repeated it so it was stuck indefinitely. should work now

**Comment by sunray1** [comment]
Wonderful thank you so much!!

**Comment by sckott** [comment]
glad it works. let me know if what it returns is not correct
