### ISSUE TITLE
classification doesn't return subspecies for GBIF

### ISSUE THREAD

**Issue by ocstringham** [ropensci/taxize#809]
When I input a GBIF ID for a subspecies (example: https://www.gbif.org/species/6162875) in the classification function, it doesn't return anything about the subspecies. Is there a way to return the subspecies name and GBIF ID? 

```r
classification(6162875, db = 'gbif')

$`6162875`
             name    rank      id
1        Animalia kingdom       1
2        Chordata  phylum      44
7        Reptilia   class 2464899
3        Squamata   order     358
4          Boidae  family     715
5             Boa   genus 2464897
6 Boa constrictor species 2444141

attr(,"class")
[1] "classification"
attr(,"db")
[1] "gbif"
```

**Comment by sckott** [comment]
what version of `taxize` do you have?

**Comment by sckott** [comment]
@ocstringham reinstall and try again, should work now

**Comment by ocstringham** [comment]
Yes, it shows the subspecies now. Thanks @sckott !!!

**Comment by sckott** [comment]
great, glad it works
