### ISSUE TITLE
Add a lot more tests for class2tree and it's internal fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#819]
@trvinh Given how complex `class2tree()` function is, I think we need a lot more tests for `class2tree()` itself, but also for the internal helper fxns used therein. Do you have time to work on this soon?  

there is somewhat good coverage of the class2tree file https://codecov.io/gh/ropensci/taxize/src/664f3ff63465f04362b8ab6e1f8cfaef69880cb3/R/class2tree.R but given how many lines of code there are, there's a lot of things that can go wrong.

**Comment by trvinh** [comment]
Yes, I will work on that soon.

**Comment by trvinh** [comment]
Hi @sckott , I've already implemented more tests for the internal functions of the `class2tree`. I couldn't, however, split any helper functions out of them. I found no independent or duplicated code blocks that can be written as helper functions :( 
The issue #818 was a bug in the algorithm, which can not be covered by checking the in/output. I have fixed that with the PR #820

**Comment by sckott** [comment]
Thanks @trvinh  - so you think there's sufficient code coverage now?

**Comment by trvinh** [comment]
Hi @sckott , I hope so. We are using the functions with different taxon sets since the last update until Adrian found a bug #818 . Currently I cannot find anything that needs to be tested.

**Comment by sckott** [comment]
okay, thanks!
