### ISSUE TITLE
error with worms_downstream for higher taxa

### ISSUE THREAD

**Issue by msweetlove** [ropensci/taxize#821]
I have a similar problem with worms_downstream as I read in issue 758 for the gif_downstream function:

When using worms_downstream to get the genera and intermediate taxa of a higher taxon (e.g. phylum, kingdom), I get an error.

For example for Fungi (urn:lsid:marinespecies.org:taxname:4):

> taxize::worms_downstream(4, "genus", intermediate = TRUE)

gives the following error:

Error in vapply(x$rank, function(z) which_rank(z), 1) : 
  values must be length 1,
 but FUN(X[[11]]) result is length 0

Is there also a fix possible for this function as was done with gif_downstream?

My session info:
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS
taxize: taxize_0.9.95.91

**Comment by sckott** [comment]
thanks for the issue @msweetlove 

it is indeed a rank name we haven't dealt with

`phylum (division)`

**Comment by sckott** [comment]
@msweetlove  Please try again after reinstalling like `remotes::install_github("ropensci/taxize")`, should work now
