### ISSUE TITLE
Rank error with worms_downstream

### ISSUE THREAD

**Issue by cgallut** [ropensci/taxize#824]
Hi,
I encountered the same problem as in issue #821 with the following command:
```r
Pedinidae <- worms_downstream(id = 123165, downto = "species")
```
It yields this error:
Error in vapply(x$rank, function(z) which_rank(z), 1) : 
  les valeurs doivent être d'une longueur 1,
 mais FUN(X[[14]]) a une longueur 0

I retrieved all children from AphiaID 123165 and it seems that the problem comes from the rank 
id = 155 , rank = "supertribe" which appears to be missing in worrms_ranks.

The following commands also yield an error:
```r
Heteroconchia <- worms_downstream(id = 1424949, downto = "species")
Caenogastropoda <- worms_downstream(id = 224570, downto = "species")
```
Error in vapply(x$rank, function(z) which_rank(z), 1) : 
  les valeurs doivent être d'une longueur 1,
 mais FUN(X[[1]]) a une longueur 0

Here it seems that rank: id = 85, rank = "Subterclass" is the reason.

Thanks for the great work, it saved me days of work!!

<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6
taxize_0.9.96 worrms_0.4.0 
```
</details>

**Comment by sckott** [comment]
thanks very much for the report!  surely many others have this issue, so many people will benefit from this. 

fix coming

**Comment by sckott** [comment]
try again after reinstalling `remotes::install_github("ropensci/taxize")`
