### ISSUE TITLE
taxonomic databases update

### ISSUE THREAD

**Issue by pecard** [ropensci/taxize#826]
The taxonomic databases seem to be provided by globalnames.org. Some of the reference tables are not up to date. Is it something that can be easily adjusted or added manually?

**Comment by sckott** [comment]
The only data provided by global names is through the functions prefixed with `gnr` or `gni`, see https://github.com/ropensci/taxize#currently-implemented-in-taxize for a summary of data sources and functions they map to. 

I don't run global names, so I can't update any data. @dimus  would be the one to talk to - Dmitry, is there info somewhere on when data sources are/will be updated?

**Comment by dimus** [comment]
@sckott I am going to finish updating data sources next week (hopefully). It depends on CoL now. CoL team is planning to release a new version next week. After that major datasets will be updated. @pecard, I did not update some datasets for a while either because they are too small and nobody asked for their update, or because I only had access to them once, and lost it now. What are you looking for?

**Comment by sckott** [comment]
thanks @dimus !

**Comment by pecard** [comment]
looking for harmonizing data for vertebrates. I'm not being able to find a workflow to deal with data from different sources. I have data from eBird, gbif, different national (PT) atlas and a single reference list for vertebrates. There are several reference lists on taxize seems to be outdated (IUCN, eBird, Reptile DataBase).

**Comment by sckott** [comment]
@dimus Did you update datasets yet?

**Comment by dimus** [comment]
@sckott yes, both resolver.globalnames.org and index.globanames.org are updated 3 days ago

**Comment by dimus** [comment]
the following datasets are updated

2020 May-June
[x] 1   CoL (once a year)

[x] 3   ITIS

[x] 4   NCBI

[x] 9   WoRMS

[x] 11  GBIF

[x] 12  EOL

[x] 167 IPNI

[x] 172 PaleoBioDB

[x] 179 OpenTreeTaxonomy (3.2)

[x] 181 IRMNG (once a year)

[x] 184 ASM Mammal Diversity Database

[x] 185 IOC World Bird List v10.1 is current

[x] 186 MCZbase

[x] 187 eBird/Clements

[x] 188 American Ornithological Society

[x] 189 Howard and Moore Complete Checklist of the Birds of the World

[x] 193 Myriatrix

**Comment by sckott** [comment]
awesome, thanks @dimus

**Comment by sckott** [comment]
@pecard databases updated, closing for now as this is not a taxize issue
