### ISSUE TITLE
lowest_common fails with merged NCBI taxid

### ISSUE THREAD

**Issue by cgallut** [ropensci/taxize#828]
Hi,

As an example the following command fails:
```r
ids <- c('668400', '668405')
lowest_common(ids, db = 'ncbi')
```
and returns this error:

Error in x[1, 1] : incorrect number of dimensions.

A search for 668400[uid] on NCI taxonomy returns the following:
Entry Merged. Taxid 668400 was merged into taxid 668482 on June 2, 2020.

Would it be possible that lowest_common() gets the new taxid and returns the lowest common with it? It then could issue a warning about the merged taxid.

Thanks for your attention!!

<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6
other attached packages: taxize_0.9.96.93
```
</details>

**Comment by sckott** [comment]
thanks, i'll have a look

**Comment by sckott** [comment]
should work now. I don't think NCBI tells us that the taxon is merged - but I did fix something in `classification()` which fixes this use case in `lowest_common`
