### ISSUE TITLE
Unseen rank name

### ISSUE THREAD

**Issue by sunray1** [ropensci/taxize#830]
Hi,

I'm having a problem when trying to get the downstream names from GenBank for 'Magnoliopsida'. Looking at similar issues, it's looking like it's just a rank name that hasn't been seen before.

Code:
```
downstream("Magnoliopsida", downto = "Species", db = "ncbi", ambiguous_nodes=TRUE, ambiguous_species=FALSE)
```
Error:
```
Error in vapply(x$rank, function(z) which_rank(z), 1) : 
  values must be length 1,
 but FUN(X[[2285]]) result is length 0
```
If I could get some help here, that'd be great! Note: this is a particularly large taxa and took a few hours and retries to get to this error.

**Comment by sckott** [comment]
Thanks for your question @sunray1  I'll have a look

Indeed, that would take a while, going to species from Magnoliopsida.

**Comment by sckott** [comment]
note to self:

```r
traceback() # after the failure
#> 12: vapply(x$rank, function(z) which_rank(z), 1)
#> 11: `[.data.frame`(taxize_ds$rank_ref, vapply(x$rank, function(z) which_rank(z),
#>         1), "rankid") at downstream-utils.R#11
#> 10: taxize_ds$rank_ref[vapply(x$rank, function(z) which_rank(z),
#>         1), "rankid"] at downstream-utils.R#11
#> 9: prune_too_low(tt, downto, ignore_no_rank = TRUE) at ncbi_downstream.R#64
#> 8: ncbi_downstream(id = y, downto = downto, intermediate = intermediate,
#>        ...) at downstream.R#199
#> 7: FUN(X[[i]], ...)
#> 6: lapply(sci_id, fun, downto = downto, intermediate = intermediate,
#>        ...) at downstream.R#203
#> 5: downstream.uid(id, downto = tolower(downto), intermediate = intermediate,
#>        ...) at downstream.R#92
#> 4: downstream(id, downto = tolower(downto), intermediate = intermediate,
#>        ...)
#> 3: stats::setNames(downstream(id, downto = tolower(downto), intermediate = intermediate,
#>        ...), sci_id) at downstream.R#117
#> 2: downstream.default("Magnoliopsida", downto = "Species", db = "ncbi",
#>        ambiguous_nodes = TRUE, ambiguous_species = FALSE) at downstream.R#92
#> 1: downstream("Magnoliopsida", downto = "Species", db = "ncbi",
#>        ambiguous_nodes = TRUE, ambiguous_species = FALSE)
```

**Comment by sckott** [comment]
@sunray1 I'm still sorting out what rank name is causing the issue. For big queries like this you may want to try [taxizedb](https://docs.ropensci.org/taxizedb/) - which has a `downstream()` function matching the one in this package, but is much much faster once you have downloaded the NCBI or ITIS database, 

```r
remotes::install_github("ropensci/taxizedb")
```

```r
# get the id for Magnoliopsida
id <- taxize::get_uid("Magnoliopsida")
library(taxizedb)

# download the NCBI taxonomy database; takes 5 minutes or so
db_download_ncbi()

# downstream
x <- downstream(id, downto = "species", db = "ncbi",
  ambiguous_nodes=TRUE, ambiguous_species=FALSE)
NROW(x[[1]])
head(x[[1]])
tail(x[[1]])
unique(x[[1]]$rank)
```

**Comment by sckott** [comment]
Tracked down the rank that caused the error: `series`

There are others though - looking at the dump of NCBI taxonomy dat: 

- biotype
- forma specialis
- isolate
- pathogroup
- series
- serogroup
- serotype
- strain

Not sure where to put some of these in the reference rank dataset `rank_ref`. Asking around

**Comment by sunray1** [comment]
Cool thanks!

No rush on this, just figured I'd let you know.

**Comment by sckott** [comment]
@sunray1 your example should work now after reinstalling like `remotes::install_github("ropensci/taxize")` - having said that you may want to use taxizedb instead for such very large queries - taxize is still fine for smaller queries
