### ISSUE TITLE
Obtaining specific taxonomic information for a specie list

### ISSUE THREAD

**Issue by adrianamordente** [ropensci/taxize#832]

**Comment by adrianamordente** [comment]
Hi! I have a vector with a species list I’d like to obtain phylum, order, family, genus for, using the tax_name function however I cannot seem to obtain any of the information required! Any info in the right direction is much appreciated! Thanks! :)

**Comment by sckott** [comment]
thanks for your question, try this:

```r
library(taxize)
x <- c("Helianthus annuus","Baetis rhodani")
tax_name(x, get = c("phylum", "order", "family", "genus"), db = "ncbi")
```
