### ISSUE TITLE
rank_ref: may need specific lookups per data source

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#833]
noticed via user email question about `worms_downstream` ... 

- WORMS uses `section` and `subsection` ranks between `order` and `family`, like `Kingdom Phylum Subphylum Superclass Class Subclass Superorder Order Suborder Infraorder Section Subsection Superfamily Family Subfamily Genus Species `
- other sources I've seen (NCBI for one) uses at least for some taxa `section` and `subsection` between `genus` and `species`
- [wikipedia says](https://en.wikipedia.org/wiki/Taxonomic_rank) zoology puts section/subsection between order/family, while botany puts section/subection between genus/species

So this isn't great. Some data sources we use only do animals or only plants, while others to a combination (some include fungi too)

section/subsection between order/genus

```r
library(taxize)
library(dplyr)
x = downstream("Scleria", db="ncbi", downto="species", intermediate = TRUE)
bind_rows(x$Scleria$intermediate) %>% filter(grepl("section", rank)) %>% head
#>   childtaxa_id              childtaxa_name    rank
#> 1      1916844       Scleria sect. Scleria section
#> 2      1916843  Scleria sect. Naumannianae section
#> 3      1916816   Scleria sect. Schizolepis section
#> 4      1916815 Scleria sect. Ophryoscleria section
#> 5      1916814 Scleria sect. Melanomphalae section
#> 6      1916813     Scleria sect. Margaleia section
```

If alternatively we put section/subsection in `rank_ref` between  order/family like

```r
rank_ref[21:28,]
#>   rankid       ranks
#> 21    100       order
#> 22    110    suborder
#> 23    120  infraorder
#> 24    125   parvorder
#> 25    126     section
#> 26    127  subsection
#> 27    130 superfamily
#> 28    140      family
```

then the worms query works (but did not work with the current `rank_ref`)

```r
x = downstream("Brachyura", db="worms", downto="superfamily", intermediate = TRUE)
bind_rows(x$Brachyura$intermediate) %>% filter(grepl("section", rank)) %>% head
#>       id           name       rank
#> 1 106678      Dromiacea    section
#> 2 106679    Eubrachyura    section
#> 3 345796    Podotremata    section
#> 4 106680  Heterotremata subsection
#> 5 106682 Thoracotremata subsection
#> 6 877398      Homolidea subsection
```

**Comment by dongzhang0725** [comment]
Could you please give me a method to add section/subsection in rank_ref between order/family?

**Comment by dongzhang0725** [comment]
I tried to use the following code to insert section/subsection:
```
> insertRow <- function(existingDF, newrow, r) {
  existingDF[seq(r+1,nrow(existingDF)+1),] <- existingDF[seq(r,nrow(existingDF)),]
  existingDF[r,] <- newrow
  existingDF
}
> rank_ref <- insertRow(rank_ref, c(126, "section"), 25)
> rank_ref <- insertRow(rank_ref, c(127, "subsection"), 26)

> rank_ref[21:28,]
   rankid       ranks
21    100       order
22    110    suborder
23    120  infraorder
24    125   parvorder
25    126     section
26    127  subsection
27    130 superfamily
28    140      family
```
However, I can't get any result from your code:
```
> x = downstream("Brachyura", db="worms", downto="superfamily", intermediate = TRUE)
> x
$Brachyura
$Brachyura$target
data frame with 0 columns and 0 rows

$Brachyura$intermediate
list()


attr(,"class")
[1] "downstream"
attr(,"db")
[1] "worms"
```
Am I wrong?

**Comment by sckott** [comment]
Note: The above change won't be the final solution I use because we still need this to work in cases where section/subsection are between genus/species. 

I'm not sure why that didn't work. I'll push a branch soon with a fix you can try

**Comment by dongzhang0725** [comment]
Thank you, maybe you can add a parameter for user to specify whether section/subsection are between genus/species or between order/family.

**Comment by sckott** [comment]
@dongzhang0725 reinstall `remotes::install_github("ropensci/taxize@rank-ref-changes)` and try again. On trying the example I actually got more than the additional 25 families, let me know if you get what you expect now

**Comment by dongzhang0725** [comment]
Hi, sckott, 

I am sorry for the late reply, the new branch works perfectly, thank you for your help.

**Comment by sckott** [comment]
great, did you get more families than you expected though?

**Comment by dongzhang0725** [comment]
Sorry, I thought I had replied, but it seems I am wrong. Yeah, I think I get all the families in Crustacea this time. Thank you! It's a great tool.

**Comment by sckott** [comment]
great, glad it works
