### ISSUE TITLE
taxize::downstream() results for db = "ncbi" differ from online NCBI. 

### ISSUE THREAD

**Issue by cparsania** [ropensci/taxize#834]
Hi, 

I want to know all the `phylum` given under the kingdom Fungi. The command I run below gave me just 2 phyla. However, when I cross-check with NCBI taxonomy, I can easily find few more such as   Zoopagomycota and Chytridiomycota which are not returned by function downstream. 

I wonder why this is so different than what I see online. 

--

``` r
library(tidyverse)
cc <- taxize::downstream(c("Fungi"), downto =c("phylum"), db = "ncbi")
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> ══  1 queries  ═══════════════
#> 
#> Retrieving data for taxon 'Fungi'
#> ✔  Found:  Fungi
#> ══  Results  ═════════════════
#> 
#> ● Total: 1 
#> ● Found: 1 
#> ● Not Found: 0
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
#> No ENTREZ API key provided
#>  Get one via taxize::use_entrez()
#> See https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/

cc[[1]]  %>% as.data.frame() %>% as_tibble()
#> # A tibble: 2 x 3
#>   childtaxa_id childtaxa_name rank  
#>   <chr>        <chr>          <chr> 
#> 1 5204         Basidiomycota  phylum
#> 2 4890         Ascomycota     phylum
```

<sup>Created on 2020-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sckott** [comment]
thanks for the issue @cparsania 

It may not be documented very well, but you can pass down the `ambiguous` parameter to [ncbi_downstream()](https://docs.ropensci.org/taxize/reference/ncbi_downstream), then to [ncbi_children()](https://docs.ropensci.org/taxize/reference/ncbi_children) which decides whether to include so-called ambiguous taxa or not. 

```r
downstream("Fungi", downto = "phylum", db = "ncbi", ambiguous = TRUE)
```

that should give 9 rows. is that the output you expect?  if not, let me know

**Comment by cparsania** [comment]
Thanks for your reply. It worked as you mentioned. May I know what does `ambiguous = TRUE` means?

**Comment by sckott** [comment]
See https://docs.ropensci.org/taxize/reference/ncbi_children.html#arguments

**Comment by sckott** [comment]
still waiting on a reply from NCBI
