### ISSUE TITLE
new rank of NCBI taxonomy

### ISSUE THREAD

**Issue by trvinh** [ropensci/taxize#835]
Hi,

I recognised that NCBI taxonomy has a new systematic rank called *"clade"*, which used to be named as *"no rank"*. This could cause trouble for the `class2tree` function, since some of its sub-functions work only with *"no rank"*. However, when I used `classification` to get the taxonomy of a species, it still delivered *"no rank"* ranks. 

```r
> outTaxize <- classification('Chiloscyllium punctatum', db='ncbi')
> outTaxize$`Chiloscyllium punctatum`
                      name         rank     id
1       cellular organisms      no rank 131567
2                Eukaryota superkingdom   2759
3             Opisthokonta      no rank  33154
4                  Metazoa      kingdom  33208
5                Eumetazoa      no rank   6072
6                Bilateria      no rank  33213
7            Deuterostomia      no rank  33511
8                 Chordata       phylum   7711
9                 Craniata    subphylum  89593
10              Vertebrata      no rank   7742
11           Gnathostomata      no rank   7776
12          Chondrichthyes        class   7777
13          Elasmobranchii     subclass   7778
14                Selachii   infraclass 119203
15            Galeomorphii      no rank 119197
16               Galeoidea   superorder 119195
17        Orectolobiformes        order  30503
18          Hemiscylliidae       family  40580
19           Chiloscyllium        genus  34767
20 Chiloscyllium punctatum      species 137246
```
As you can see in the NCBI taxonomy website for this species, some *"no rank"* ranks such as Opisthokonta, Eumetazoa,..., or Galeomorphii are *clades*. I have checked some other taxa, NCBI seems to use *"no rank"* only for *"cellular organisms"*. All other *"no rank"* ranks have been replaced by *"clade"*.

Are you planning to replace those *"no rank"* ranks by *"clade"*? If yes, please let me know so that I can adapt the sub functions of `class2tree`. Otherwise, it will be safe :)

Best,
Vinh

**Comment by trvinh** [comment]
I think it is related to #830

**Comment by sckott** [comment]
thanks @trvinh yes, related to #830 

This is good timing since I'm thinking about a new `rank_ref` setup (see #833) triggered by the fact that `section`/`subsection` ranks are used in completely different parts of the classification tree for animals vs. plants. That is, we need to rework how we lookup the ordering of ranks based on the data source.

For the `classification()` example you give above, NCBI is giving back "no rank" even though the website gives "clade". So it's not a problem on the taxize side AFAICT. I imagine perhaps the data source version being used for the website is slightly different version from that supplying the NCBI Entrez web service. Any ideas?

**Comment by trvinh** [comment]
Hi @sckott,

It could be as you said, that Entrez and the website are not consistent.

For the `class2tree()`, I can also add the new ranks to their positions according to the `rank_ref`. In case of *"section/subsection"* and *"clade"*, since they can be placed in different positions in the taxonomy string, I will treat them the same as *"no rank"*. Since I am using the rank names only as a tag for sorting the taxa, it is only important to know their relative positions in the taxonomy string, not how they are called. 

What are you using the `rank_ref` data frame for, except the downstream functions?

**Comment by sckott** [comment]
using `rank_ref` in the following functions:

- worms_downstream
- ncbi_downstream
- itis_downstream
- gbif_downstream
- bold_downstream
- classification
- tax_name

**Comment by sckott** [comment]
i've emailed NCBI about this, but who knows if i'll get a response

**Comment by trvinh** [comment]
Great! Let hope that they will give an answer so that we can plan how to modify the code :) Anyway, if it is needed, I think I already have an idea how to adapt it to the `class2tree` function.

**Comment by sckott** [comment]
@trvinh  I got a reply. they said the the esummary entrez method does give the clade designation for our eg taxon - compare these

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=taxonomy&ID=7776
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&ID=7776

And said

> If the "clade" is new, it is likely that the E-Utilities are behind the web version and will be seen with the next backend update.  But hopefully this can get you by as a workaround.  If this is holding up your workflow, please write back next week if the rank is still missing, as there should be an update to the E-Utilities index for E-Fetch this weekend.

So perhaps this will be resolved soon, but not yet.

**Comment by trvinh** [comment]
ok, let see when they solve this inconsistency. The current `class2tree` function still works correctly. Please let me know if you got anything new from NCBI, so that I can adapt the function accordingly. 
Or, if you want to be in the safe side, I will modify `class2tree` based on the current `rank_ref`, so it will be ready even if the `classification` fn can output the new taxonomy ranks later. 
So, which do you prefer? Waiting until NCBI make changes or I will modify the fn now?

**Comment by sckott** [comment]
I've replied to the NCBI email thread asking when that update will happen

**Comment by sckott** [comment]
@trvinh i think the change has been made - compare the two links in the above comment https://github.com/ropensci/taxize/issues/835#issuecomment-664676578 - and I think the change, as you expected, is causing issues in `class2tree` - see #838
