### ISSUE TITLE
Error with taxosaurus.org ?

### ISSUE THREAD

**Issue by diegodaem** [ropensci/taxize#841]
Hello

I´m beginner so my question may be basic, although I could not find the answer on Google. I am trying to access through the tnrs function, but I get the following error: 

library(taxize)

species = c ("Epidendrum arachnoides", "Epidendrum nocturnum", "Epidendrum ciliaris")

(name_query = tnrs(sci = species,
                   source = "iPlant_TNRS"))

Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  Timeout was reached: [**taxosaurus.org**] Connection timed out after 10003 milliseconds

--------
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

any idea what the problem is?

Thanks in advance

**Comment by sckott** [comment]
That site is down right now. "connection time out" is a general way to indicate that a server is not responding within some time limit. considering dropping tnrs fxn, see #842

**Comment by diegodaem** [comment]
Thank you very much @sckott

**Comment by sckott** [comment]
tnrs is defunct now (in the dev branch `taxa-work`)
