### ISSUE TITLE
upstream() error: "The provided db value was not recognised" for NCBI

### ISSUE THREAD

**Issue by eray-sahin** [ropensci/taxize#853]
Hello,

I am trying to extract upper taxonomic level information for the taxa I have in genus level. For 'itis', the function upstream() works, but for some levels it produces incorrect results. When I attempted to use 'ncbi', I am getting the error;

>upstream('Escherichia', db = 'ncbi', upto='phylum')
Error: the provided db value was not recognised

Thank you for your help,

Eray

**Comment by sckott** [comment]
thanks for your question. I don't remember if upstream ever supported ncbi. it used to support col but that was removed a while back. Not all functions in taxize support NCBI. the only db supported right now for upstream is itis. 

> but for some levels it produces incorrect results

i assume this is when using `db="itis"`?  please share those problems so i can help

**Comment by eray-sahin** [comment]
Dear sckott,

Thank you for your help,

I can give two examples that may illustrate the problem I am having:

For genus 'Escherichia', the ITIS database gives that taxonomic info https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=280#null. For taxize;
> upstream('Escherichia', db = 'itis', upto='phylum')
==  1 queries  ===============

Retrieving data for taxon 'Escherichia'

√  Found:  Escherichia
==  Results  =================

* Total: 1 
* Found: 1 
* Not Found: 0
$Escherichia
      tsn   parentname parenttsn rankname             taxonname rankid
1  956098 Negibacteria    956096   phylum         Acidobacteria     30
2  956100 Negibacteria    956096   phylum             Aquificae     30
3  956101 Negibacteria    956096   phylum       Armatimonadetes     30
4  956102 Negibacteria    956096   phylum         Bacteroidetes     30
5  956103 Negibacteria    956096   phylum           Caldiserica     30
6  956104 Negibacteria    956096   phylum            Chlamydiae     30
7  956105 Negibacteria    956096   phylum              Chlorobi     30
8  956107 Negibacteria    956096   phylum        Chrysiogenetes     30
9  956108 Negibacteria    956096   phylum         Cyanobacteria     30
10 956109 Negibacteria    956096   phylum       Deferribacteres     30
11 956110 Negibacteria    956096   phylum   Deinococcus-Thermus     30
12 956111 Negibacteria    956096   phylum           Dictyoglomi     30
13 956112 Negibacteria    956096   phylum         Elusimicrobia     30
14 956113 Negibacteria    956096   phylum         Fibrobacteres     30
15 956115 Negibacteria    956096   phylum          Fusobacteria     30
16 956116 Negibacteria    956096   phylum      Gemmatimonadetes     30
17 956117 Negibacteria    956096   phylum         Lentisphaerae     30
18 956118 Negibacteria    956096   phylum            Nitrospira     30
19 956119 Negibacteria    956096   phylum        Planctomycetes     30
20 956120 Negibacteria    956096   phylum        Proteobacteria     30
21 956121 Negibacteria    956096   phylum          Spirochaetae     30
22 956122 Negibacteria    956096   phylum         Synergistetes     30
23 956124 Negibacteria    956096   phylum Thermodesulfobacteria     30
24 956125 Negibacteria    956096   phylum           Thermotogae     30
25 956126 Negibacteria    956096   phylum       Verrucomicrobia     30

attr(,"class")
[1] "upstream"
attr(,"db")
[1] "itis"

For another genus names 'Akkermansia', the ITIS database gives that taxonomic info https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=956657#null
For taxize;
> upstream('Akkermansia', db = 'itis', upto='phylum')
==  1 queries  ===============

Retrieving data for taxon 'Akkermansia'

√  Found:  Akkermansia
==  Results  =================

* Total: 1 
* Found: 1 
* Not Found: 0
$Akkermansia
      tsn   parentname parenttsn rankname             taxonname rankid
1  956098 Negibacteria    956096   phylum         Acidobacteria     30
2  956100 Negibacteria    956096   phylum             Aquificae     30
3  956101 Negibacteria    956096   phylum       Armatimonadetes     30
4  956102 Negibacteria    956096   phylum         Bacteroidetes     30
5  956103 Negibacteria    956096   phylum           Caldiserica     30
6  956104 Negibacteria    956096   phylum            Chlamydiae     30
7  956105 Negibacteria    956096   phylum              Chlorobi     30
8  956107 Negibacteria    956096   phylum        Chrysiogenetes     30
9  956108 Negibacteria    956096   phylum         Cyanobacteria     30
10 956109 Negibacteria    956096   phylum       Deferribacteres     30
11 956110 Negibacteria    956096   phylum   Deinococcus-Thermus     30
12 956111 Negibacteria    956096   phylum           Dictyoglomi     30
13 956112 Negibacteria    956096   phylum         Elusimicrobia     30
14 956113 Negibacteria    956096   phylum         Fibrobacteres     30
15 956115 Negibacteria    956096   phylum          Fusobacteria     30
16 956116 Negibacteria    956096   phylum      Gemmatimonadetes     30
17 956117 Negibacteria    956096   phylum         Lentisphaerae     30
18 956118 Negibacteria    956096   phylum            Nitrospira     30
19 956119 Negibacteria    956096   phylum        Planctomycetes     30
20 956120 Negibacteria    956096   phylum        Proteobacteria     30
21 956121 Negibacteria    956096   phylum          Spirochaetae     30
22 956122 Negibacteria    956096   phylum         Synergistetes     30
23 956124 Negibacteria    956096   phylum Thermodesulfobacteria     30
24 956125 Negibacteria    956096   phylum           Thermotogae     30
25 956126 Negibacteria    956096   phylum       Verrucomicrobia     30

attr(,"class")
[1] "upstream"
attr(,"db")
[1] "itis"

Best regards,

Eray

**Comment by sckott** [comment]
You have not stated what the problem is? Please be specific.

**Comment by eray-sahin** [comment]
Dear sckott,

While I was trying to use 'itis' database to find the phylum of the genus of my interest, it produces more than one result, and when I check ITIS database, there is only one respective phylum record.

For example, for genus 'Escherichia' the phylum is 'Proteobacteria' , but the output gives 25 results , and the correct one is the 20th in the list.

For another genus named 'Akkermensia', the phylum is 'Verrucomicrobia', which is the 25th in the same 25 results.

I hope I could clarify my problem.

Thank you,

Best regards,

Eray

**Comment by sckott** [comment]
Ah okay. `upstream()` is not meant for that use case. It's equivalent to `downstream()`, where each get all names up or downstream from the input name. 

Try `tax_name(sci = "Escherichia", get = "phylum", db = "ncbi")`, see `?tax_name`

**Comment by eray-sahin** [comment]
Thank you so much,

Best regards,

eray
