### ISSUE TITLE
Error in names - db='tropicos'

### ISSUE THREAD

**Issue by cRonFer** [ropensci/taxize#865]
I am trying to get some species ids from tropicos and the following error appears. The same call works fine for db= 'pow' and others so it seems that something happens with tropicos db.

![error taxize-tropicos](https://user-images.githubusercontent.com/76005368/102117049-1d930180-3e3e-11eb-993d-34f03f49278b.JPG)

sessionInfo():

![image](https://user-images.githubusercontent.com/76005368/102117276-6a76d800-3e3e-11eb-9242-08e6e2bf8566.png)

**Comment by sckott** [comment]
Thanks for the report and including session info! Please in the future copy/paste the text from R instead of taking screen shots. 

Please run that example again, but then after it errors run `traceback()`, then share the output of that here.

**Comment by cRonFer** [comment]
Thanks! Here you have the traceback() call after the error:

> traceback()
7: getkey(key, "TROPICOS_KEY")
6: tp_search(sci = sci[i], key = key, ...)
5: get_tpsid(sci_com, ...)
4: foo(x, sci_com = sci_com, ...)
3: FUN(X[[i]], ...)
2: lapply(db, function(x) foo(x, sci_com = sci_com, ...))
1: get_ids("Aldina paulberryi", db = "tropicos", rows = NA)

**Comment by sckott** [comment]
Should be fixed now. Please try again after reinstalling like `remotes::install_github("ropensci/taxize")`
