### ISSUE TITLE
retrival limit downstram/gbif_downstream, documentation

### ISSUE THREAD

**Issue by azizka** [ropensci/taxize#867]
Hi Scott,
I am teaching a course using taxize (still awesome, thanks!), we are trying to use `downstream`/`gbif_downstream` to get species names in different taxa from the GBIF backbone. 

1. Would it be possible to add to the documentation of gbif_downstream, that there is a hard limit of 1000 names to be returned (See code below for Piper, which stops at 1000 names with epitheton f*)? We figured out to use the `at` argument after a while as a workaround, but it would be nice if the limit and the solution were clear from the documentation.

2. If possible it would be nice to learn from the `downstream` documentation already that downstream has a default limit of 100 names (via the default in gbif_downstream.

Thanks & sorry if we missed anything

# code example
```r
library(taxize)
library(tidyverse)

ID<- get_gbifid_("Piper", method="backbone")%>% 
  bind_rows() %>%
  filter(matchtype == "EXACT" & status == "ACCEPTED") 

splist <- gbif_downstream(id = ID$usagekey,
                          limit = 2000,
                          method = "lookup",
                          downto = "species",
                          rows = NA)[[1]]
```

**Comment by sckott** [comment]
Thanks, having a look

**Comment by sckott** [comment]
thanks, docs updated, see https://docs.ropensci.org/taxize/reference/gbif_downstream.html and https://docs.ropensci.org/taxize/reference/downstream.html
