### ISSUE TITLE
Truncated taxonomy list

### ISSUE THREAD

**Issue by KFeye** [ropensci/taxize#871]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

Hello!  

I am using the following code (adjusted for privacy):
 df <- Blueplate3
df$species_taxid <- as.numeric(as.character(df$species_taxid))
df <- df[order(df$species_taxid),] 
head(df)
           
taxonomy <- df[,c("species_taxid"), drop=FALSE]
head(taxonomy)
#upload data and add it to data.frame
taxonomy <- as.data.frame(taxonomy)
head(taxonomy)

#to remove duplicates
taxa <- unique(taxonomy)
print(taxa)
write.csv(taxa, file="taxablue2.txt", row.names=TRUE )

#Enters key information but that is withheld and working well

library("taxize")
library("myTAI")
library("dplyr")

Taxa 
taxa$species_taxid <- as.character(taxa$species_taxid)

taxon_summary <- ncbi_get_taxon_summary(id = taxa$species_taxid)

df_list <- list()
for (i in 1:nrow(taxon_summary)){
    tax  <- taxonomy(organism = taxon_summary[i,]$name, db = "ncbi",output = "classification")
    df <- data.frame(lapply(tax$name, function(x) data.frame(x)))
    colnames(df) <- tax$rank
    df_list[[i]] <- df
    Sys.sleep(0.5)
}
taxonomylistzp3bluetry2 = data.table::rbindlist(df_list, fill=TRUE)writing
write.csv(taxonomylist, file="taxblue2.txt", row.names=TRUE)

#Then...

#To pull out Barcode v. taxonomy 
frequency <- Blueplate3[,c("barcode", "species_taxid"), drop=FALSE]
Frequency <- order(frequency$species_taxid, decreasing=FALSE)
head(frequency)
colnames(frequency)
frequency$ID <- seq.int(nrow(frequency))
head(frequency)
frequency <- frequency[,c()]
head(frequency)

To create frequency Table
library(tidyverse)
library(readxl)
library(here)
library(skimr)
library(kableExtra)

rawsfreqtable <- as.data.frame(df)  #creates data frames
skimr:: skim(rawsfreqtable) #check out structure and whatnot
tabley <- rawsfreqtable %>% group_by(barcode,species_taxid, ) %>% summarize(count_by_barcodespecies_taxid=n()) #this creates a frequency distribution of the barcodes vs. species_taxid
finalfrequencytable <- tabley %>% pivot_wider (names_from= barcode, values_from= count_by_barcodespecies_taxid, values_fill=0)
freqtable   #this should create the final frequency table necessary to move on
write.csv(freqtable, file="frequencytable.txt")

**ISSUE: My initial species list (TAXID, NCBI) is 2442 entries long. It always returns 2422.  The list of what was not blasted is not present (No NA output) and I have no idea where the errors are unless I go through 2442 entries and backtrack.  I shortened the lists and it keeps truncating.  Is there a list size that is preferable?  I have about 3 files ranging from a length of taxid numbers from 2442 to 4000.**

**Comment by sckott** [comment]
I assume this is a duplicate issue of the email you sent?

**Comment by KFeye** [comment]
Hey!  Yes.  We resolved it by removing the brackets from incoming NCBI
blast returns.  Thanks!
