### ISSUE TITLE
How to write class2tree tree to file?

### ISSUE THREAD

**Issue by vragh** [ropensci/taxize#872]
Apologies if this is a silly question, but how do I write the tree generated by `taxize::class2tree` to file? I'd like to save the tree in the Newick format if possible.

I can't seem to find a function in the package for this, and I'm not sure what kind of an object `classtree` is supposed to be (so I'm unsure what non-`taxize` functions I can use to write its contents out to a file).

**Comment by vragh** [comment]
Just managed to figure it out. All I needed to do was write out the `objname$phylo` slot out to file using `ape::write.tree`.

**Comment by sckott** [comment]
nice work! yep, thats it
