### ISSUE TITLE
How to retrieve just the kingdom or super-kingdom for a particular species

### ISSUE THREAD

**Issue by pbpayal** [ropensci/taxize#882]
Hello,

I have a list of species names. They are bacteria, fungi, allergens etc. I need to stratify them into basic kingdom categories according to NCBI taxonomy. Is there a way to just extract that information using taxize?

Thanks,
Payal

**Comment by zachary-foster** [comment]
How about this?

```r
library(taxize)
library(purrr)
sp_class <- classification(c("Pinus contorta", "Malus domestica"), db = "ncbi")
map_chr(sp_class, function(x) x$name[x$rank == "superkingdom"])
```

**Comment by pbpayal** [comment]
Thanks. This works
