### ISSUE TITLE
Error: {"error":"API rate limit exceeded","api-key":"85.250.39.10","count":"4","limit":"3"}

### ISSUE THREAD

**Issue by Noa164** [ropensci/taxize#896]
when trying to use classification on 151 species names, I get "Error: {"error":"API rate limit exceeded","api-key":"85.250.39.10","count":"4","limit":"3"}".
It doesn't appear on other datasets I use the function on. It did appear on another dataset where I had 3490 species names. 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/87242141/180192334-ec4721d6-c746-4848-a7db-22cace6545d8.png">

`Retrieving data for taxon 'apis melifera'

**Comment by zachary-foster** [comment]
I noticed you closed the issue. Did you solve your problem?

**Comment by Noa164** [comment]
Yes thanks! I just didn't get an API key.

Noa Frydman

בתאריך יום ה׳, 21 ביולי 2022, 19:11, מאת Zachary Foster ‏<
***@***.***>:
