### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/taxize#897]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: taxize_options
```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
@zachary-foster

**Comment by zachary-foster** [comment]
Thanks for the report! I just got back from vacation so I have not had a change to look at this yet.  I will look into this tomorrow.

**Comment by zachary-foster** [comment]
Ok, should be fixed. I assume that pkgdown is being run automatically by ropensci to produce this?

https://docs.ropensci.org/taxize/reference/index.html

**Comment by maelle** [comment]
Thank you!!

Yes, by R-universe: https://ropensci.org/blog/2021/09/03/runiverse-docs/

You can see the status in each commit status (screenshot below) and on the dashboard: https://ropensci.r-universe.dev/ui#builds

![image](https://user-images.githubusercontent.com/8360597/189051191-9c246d74-28a6-46c8-9474-a3f166cda0c5.png)

(By the way I see a GHA failure)
