### ISSUE TITLE
Change to new cran checks badge URL

### ISSUE THREAD

**Issue by sckott** [ropensci/taxize#903]
@zachary-foster 

👋🏽  I maintain the cran checks badges. Please change to the new cran checks badge URL (e.g., `https://badges.cranchecks.info/worst/taxize.svg`). Old badges at (e.g. `https://cranchecks.info/badges/worst/taxize`) will be **unavailable** as of Jan 1st 2023.

- Blog post announcing the change: https://recology.info/2022/06/cran-checks-badges/
- New badges repo: https://github.com/r-hub/cchecksbadges
- Old badges repo: https://github.com/sckott/cchecksapi

**Comment by sckott** [comment]
👋🏽  Shutting down the old cran checks badges tomorrow

**Comment by zachary-foster** [comment]
Done. Thanks for the reminder!

**Comment by sckott** [comment]
great, np!
