### ISSUE TITLE
Could taxize do without {conditionz}?

### ISSUE THREAD

**Issue by maelle** [ropensci/taxize#908]
:wave: @zachary-foster! {conditionz} has been archived on GitHub (not archived on CRAN yet) because it is no longer maintained. Do you think rgbif could do without it? Would you need help, for instance a PR keeping the same kind of functionality? If I am reading the conditionz usage correctly, it could be replaced with https://lifecycle.r-lib.org/ functions

**Comment by zachary-foster** [comment]
Thanks for the info! I am not sure. Let me take a look and I will get back to you.

**Comment by salix-d** [comment]
It's only used in one function (`pchk` in R/zzz.R) that is only used by deprecated arguments and was gonna be removed.

**Comment by zachary-foster** [comment]
Ok, `conditionz` is no longer a dependency. I adapted the code to use `lifecycle` instead.

**Comment by maelle** [comment]
Thank you!! Could you please tell me when approximately you plan taxize's next CRAN release?

**Comment by zachary-foster** [comment]
I did not have a distinct time in mind. Do you think I should release a new version soon to avoid issues with `conditionz`?

**Comment by maelle** [comment]
my hope is to archive it on CRAN soon-ish together with other similar packages, there's no particular hurry but if I wait too much maybe new rev deps will appear. :sweat_smile:
